Description of RayTraceResult
RayTraceResult
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
RayTraceResult
This function is called by:
tracePolarizedRay tracePolarizedRay: main function of polarized ray tracer
RayTraceResult
SUBFUNCTIONS
function traceResult = RayTraceResult(RayIntersectionPoint,SurfaceNormal,
SOURCE CODE
classdef RayTraceResult
    % RayTraceResult Class:
    %   Store ray trace results in the form of arrays
    %   Constructors can construct multiple RayTraceResult objects for
    %   multiple ray trace.
    % Properties:
    %     % All properties are arrays of the corresponding properties of the
    %     % ray traced for each surfces in the system
    %     RayIntersectionPoint
    %     SurfaceNormal
    %     IncidentRayDirection
    %     IncidenceAngle
    %     ExitRayDirection
    %     ExitAngle
    %     PathLength
    %     OpticalPathLength
    %     PolarizationVectorBeforeCoating
    %     PolarizationVectorAfterCoating
    %
    %     CoatingJonesMatrix
    %     CoatingPMatrix
    %     CoatingQMatrix
    %     TotalPMatrix
    %     TotalQMatrix
    %     % Failure cases
    %     NoIntersectionPoint
    %     OutOfAperture
    %     TotalInternalReflection
    % Methods:
    %     [PolEllipseBeforeCoating,PolEllipseAfterCoating] = ...
    %                      getPolarizationEllipseParameters(RayTraceResult)
    %                  % getPolarizationEllipseParameters: Returns polarization ellipse
    %                  % parameters of the ray before and after the coating of a surf
    %     [IntensityBeforeCoating,IntensityAfterCoating] =  ...
    %                      getIntensity(RayTraceResult)
    %                  % getIntensity: Returns intensity parameters of the ray before
    %                  % and after the coating of a surf
    % <<<<<<<<<<<<<<<<<<<<<<< Algorithm Section>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %
    % <<<<<<<<<<<<<<<<<<<<<<<<< Example Usage>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %
    % <<<<<<<<<<<<<<<<<<<<<<<<< Author Section >>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %   Written By: Worku, Norman Girma
    %   Advisor: Prof. Herbert Gross
    %   Part of the RAYTRACE_TOOLBOX V3.0 (OOP Version)
    %    Optical System Design and Simulation Research Group
    %   Institute of Applied Physics
    %   Friedrich-Schiller-University of Jena
    % <<<<<<<<<<<<<<<<<<< Change History Section >>>>>>>>>>>>>>>>>>>>>>>>>>
    % Date----------Modified By ---------Modification Detail--------Remark
    % Oct 14,2013   Worku, Norman G.     Original Version       Version 3.0
    % Jan 18,2014   Worku, Norman G.     Vectorized constructor
    % <<<<<<<<<<<<<<<<<<<<< Main Code Section >>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    properties
        % All properties are arrays of the corresponding properties of the
        % ray traced for each surfces in the system
        RayIntersectionPoint
        SurfaceNormal
        IncidentRayDirection
        IncidenceAngle
        ExitRayDirection
        ExitAngle
        PathLength
        OpticalPathLength
        PolarizationVectorBeforeCoating
        PolarizationVectorAfterCoating
        CoatingJonesMatrix
        CoatingPMatrix
        CoatingQMatrix
        TotalPMatrix
        TotalQMatrix
        % Failure cases
        NoIntersectionPoint
        OutOfAperture
        TotalInternalReflection
    end
    methods
        % Constructor
        function traceResult = RayTraceResult(RayIntersectionPoint,SurfaceNormal,...
        IncidentRayDirection,IncidenceAngle,ExitRayDirection,ExitAngle,...
        NoIntersectionPoint,OutOfAperture,TotalInternalReflection,PathLength,OpticalPathLength,...
        PolarizationVectorBeforeCoating,PolarizationVectorAfterCoating,...
        CoatingJonesMatrix,CoatingPMatrix,CoatingQMatrix,TotalPMatrix,TotalQMatrix)
            % Assume all inputs are valid and of equal size
            if nargin == 0
                traceResult.RayIntersectionPoint = [0;0;0];
                traceResult.SurfaceNormal  = [0;0;0];
                traceResult.IncidentRayDirection = [0;0;1];
                traceResult.IncidenceAngle = 0;
                traceResult.ExitRayDirection = [0;0;1];
                traceResult.ExitAngle = 0;
                traceResult.PathLength = 0;
                traceResult.OpticalPathLength = 0;
                traceResult.PolarizationVectorBeforeCoating = [1;0;0];
                traceResult.PolarizationVectorAfterCoating = [1;0;0];
                traceResult.CoatingJonesMatrix = eye(2);
                traceResult.CoatingPMatrix  = eye(3);
                traceResult.CoatingQMatrix  = eye(3);
                traceResult.TotalPMatrix  = eye(3);
                traceResult.TotalQMatrix  = eye(3);
                % Failure cases
                traceResult.NoIntersectionPoint = 0;
                traceResult.OutOfAperture = 0;
                traceResult.TotalInternalReflection = 0;
            else
                % Preallocate the array object
                nRay = size(RayIntersectionPoint,2);
                traceResult(nRay) = RayTraceResult;
                for kk = 1:nRay
                    traceResult(kk).RayIntersectionPoint = RayIntersectionPoint(:,kk);
                    traceResult(kk).SurfaceNormal  = SurfaceNormal(:,kk);
                    traceResult(kk).IncidentRayDirection = IncidentRayDirection(:,kk);
                    traceResult(kk).IncidenceAngle = IncidenceAngle(kk);
                    traceResult(kk).ExitRayDirection = ExitRayDirection(:,kk);
                    traceResult(kk).ExitAngle = ExitAngle(kk);
                    traceResult(kk).PathLength = PathLength(kk);
                    traceResult(kk).OpticalPathLength = OpticalPathLength(kk);
                    % Failure cases
                    traceResult(kk).NoIntersectionPoint = NoIntersectionPoint(kk);
                    traceResult(kk).OutOfAperture = OutOfAperture(kk);
                    traceResult(kk).TotalInternalReflection = TotalInternalReflection(kk);
                    if nargin > 11
                        % polarization related
                        traceResult(kk).PolarizationVectorBeforeCoating = ...
                            PolarizationVectorBeforeCoating(:,kk);
                        traceResult(kk).PolarizationVectorAfterCoating = ...
                            PolarizationVectorAfterCoating(:,kk);
                        traceResult(kk).CoatingJonesMatrix = CoatingJonesMatrix(:,:,kk);
                        traceResult(kk).CoatingPMatrix  = CoatingPMatrix(:,:,kk);
                        traceResult(kk).CoatingQMatrix  = CoatingQMatrix(:,:,kk);
                        traceResult(kk).TotalPMatrix  = TotalPMatrix(:,:,kk);
                        traceResult(kk).TotalQMatrix  = TotalQMatrix(:,:,kk);
                    end
                end
            end
        end
    end
end