function [ outputGaussianPulse ] = propagateGaussianPulsedBeam( optSystem,...
        inputGaussianPulse,startSurfIndex,startSurfInclusive,...
        endSurfIndex, endSurfInclusive,pilotRay )
    %PROPAGATEGAUSSIANPULSEDBEAM Summary of this function goes here
    %   Detailed explanation goes here
    
    % Compute Kostenbauder matrix
    finalKostenbauderMatrix = computeKostenbauderMatrix(...
        optSystem,startSurfIndex,startSurfInclusive,...
        endSurfIndex, endSurfInclusive,pilotRay );
    
    outputGaussianPulse = propagateUsingKostenbauder(inputGaussianPulse,...
        finalKostenbauderMatrix);
end

