function InitializeMenuAndToolbarItems(parentWindow)
    % Defines all menu items and toolbar commands and all callbacks related
    % with the menu commands.
    % Member of ParentWindow class
    
    aodHandles = parentWindow.ParentHandles;
    %   fontSize = str2double(get(aodHandles.fontSize,'String'));
    fontSize = aodHandles.FontSize;
    nMainTab = aodHandles.nMainTab;
    aodHandles.menuTry = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuTry', ...
        'Label', 'Try', ...
        'Checked', 'off', ...
        'visible', 'off', ...
        'Callback', {@menuTry_Callback,parentWindow});
    function menuTry_Callback(~,~,parentWindow)
        aodHandles = parentWindow.ParentHandles;
        disp('try clicked');
    end
    %% Menu Items
    aodHandles.menuFile = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuFile', ...
        'Label', 'File', ...
        'Checked', 'off', ...
        'Callback', {@menuFile_Callback,parentWindow});
    
    aodHandles.menuNew = uimenu( ...
        'Parent', aodHandles.menuFile, ...
        'Tag', 'menuNew', ...
        'Label', 'New...', ...
        'Checked', 'off', ...
        'Callback', {@menuNew_Callback,parentWindow});
    
    aodHandles.menuOpen = uimenu( ...
        'Parent', aodHandles.menuFile, ...
        'Tag', 'menuOpen', ...
        'Label', 'Open', ...
        'Checked', 'off', ...
        'Callback', {@menuOpen_Callback,parentWindow});
    
    aodHandles.menuSave = uimenu( ...
        'Parent', aodHandles.menuFile, ...
        'Tag', 'menuSave', ...
        'Label', 'Save', ...
        'Checked', 'off', ...
        'Callback', {@menuSave_Callback,parentWindow});
    
    aodHandles.menuSavaAs = uimenu( ...
        'Parent', aodHandles.menuFile, ...
        'Tag', 'menuSavaAs', ...
        'Label', 'Save As...', ...
        'Checked', 'off', ...
        'Callback', {@menuSavaAs_Callback,parentWindow});
    
    aodHandles.menuClose = uimenu( ...
        'Parent', aodHandles.menuFile, ...
        'Tag', 'menuClose', ...
        'Label', 'Close', ...
        'Checked', 'off', ...
        'Callback', {@menuClose_Callback,parentWindow});
    
    aodHandles.menuEdit = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuEdit', ...
        'Label', 'Edit', ...
        'Checked', 'off', ...
        'Callback', {@menuEdit_Callback,parentWindow});
    
    %     aodHandles.menuSurfaceProperties = uimenu( ...
    %         'Parent', aodHandles.menuEdit, ...
    %         'Tag', 'menuSurfaceProperties', ...
    %         'Label', 'Surface Properties', ...
    %         'Checked', 'off', ...
    %         'Callback', {@menuSurfaceProperties_Callback,parentWindow});
    
    aodHandles.menuSystemConfiguration = uimenu( ...
        'Parent', aodHandles.menuEdit, ...
        'Tag', 'menuSystemConfiguration', ...
        'Label', 'System Configuration', ...
        'Checked', 'off', ...
        'Callback', {@menuSystemConfiguration_Callback,parentWindow});
    
    %     aodHandles.menuComponents = uimenu( ...
    %         'Parent', aodHandles.menuEdit, ...
    %         'Tag', 'menuSystemConfiguration', ...
    %         'Label', 'System Configuration', ...
    %         'Checked', 'off', ...
    %         'Callback', {@menuComponents_Callback,parentWindow});
    
    aodHandles.menuView = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuView', ...
        'Label', 'View', ...
        'Checked', 'off', ...
        'Callback', {@menuView_Callback,parentWindow});
    
    aodHandles.menu2DSystemLayout = uimenu( ...
        'Parent', aodHandles.menuView, ...
        'Tag', 'menu2DSystemLayout', ...
        'Label', '2D System Layout', ...
        'Checked', 'off', ...
        'Callback', {@menu2DSystemLayout_Callback,parentWindow});
    
    aodHandles.menu3DSystemLayout = uimenu( ...
        'Parent', aodHandles.menuView, ...
        'Tag', 'menu3DSystemLayout', ...
        'Label', '3D System Layout', ...
        'Checked', 'off', ...
        'Callback', {@menu3DSystemLayout_Callback,parentWindow});
    %---------------------------------------------------------------------
    
    %---------------------------------------------------------------------
    aodHandles.menuOptimization = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuOptimization', ...
        'Label', 'Optimization', ...
        'Checked', 'off', ...
        'visible', 'off', ...
        'Callback', {@menuOptimization_Callback,parentWindow});
    
    aodHandles.menuImageAtBfp = uimenu( ...
        'Parent', aodHandles.menuOptimization, ...
        'Tag', 'menuImageAtBfp', ...
        'Label', 'Image @ BFP', ...
        'Checked', 'off', ...
        'Callback', {@menuImageAtBfp_Callback,parentWindow});
    
    aodHandles.menuOpticalSystem = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuOpticalSystem', ...
        'Label', 'Optical System', ...
        'Checked', 'off', ...
        'Callback', {@menuOpticalSystem_Callback,parentWindow});
    
    aodHandles.menuImportOpticalSystem = uimenu( ...
        'Parent', aodHandles.menuOpticalSystem, ...
        'Tag', 'menuImportOpticalSystem', ...
        'Label', 'Import', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuImportOpticalSystem_Callback,parentWindow});
    
    aodHandles.menuImportZMXFile = uimenu( ...
        'Parent', aodHandles.menuImportOpticalSystem, ...
        'Tag', 'menuImportZMXFile', ...
        'Label', 'From ZMX File', ...
        'Checked', 'off', ...
        'Callback', {@menuImportZMXFile_Callback,parentWindow});
    
    aodHandles.menuExportOpticalSystem = uimenu( ...
        'Parent', aodHandles.menuOpticalSystem, ...
        'Tag', 'menuExportOpticalSystem', ...
        'Visible', 'off', ...
        'Label', 'Export Optical System', ...
        'Checked', 'off', ...
        'Callback', {@menuExportOpticalSystem_Callback,parentWindow});
    
    aodHandles.menuOpticalSystemAnalysis = uimenu( ...
        'Parent', aodHandles.menuOpticalSystem, ...
        'Tag', 'menuOpticalSystemAnalysis', ...
        'Label', 'Analysis', ...
        'Checked', 'off', ...
        'Callback', {@menuOpticalSystemAnalysis_Callback,parentWindow});
    
    aodHandles.menuParaxialAnalysis = uimenu( ...
        'Parent', aodHandles.menuOpticalSystemAnalysis, ...
        'Tag', 'menuParaxialAnalysis', ...
        'Label', 'Paraxial Analysis', ...
        'Checked', 'off', ...
        'Callback', {@menuParaxialAnalysis_Callback,parentWindow});
    
    aodHandles.menuScalarRayTrace = uimenu( ...
        'Parent', aodHandles.menuOpticalSystemAnalysis, ...
        'Tag', 'menuScalarRayTrace', ...
        'Label', 'Scalar Ray Trace', ...
        'Checked', 'off', ...
        'Callback', {@menuScalarRayTrace_Callback,parentWindow});
    
    aodHandles.menuFootprintDiagram = uimenu( ...
        'Parent', aodHandles.menuOpticalSystemAnalysis, ...
        'Tag', 'menuFootprintDiagram', ...
        'Label', 'Footprint Diagram', ...
        'Checked', 'off', ...
        'Callback', {@menuFootprintDiagram_Callback,parentWindow});
    %---------------------------------------------------------------------
    % Ray Aberration Analysis
    aodHandles.menuRayAberration = uimenu( ...
        'Parent', aodHandles.menuOpticalSystemAnalysis, ...
        'Tag', 'menuRayAberration', ...
        'Label', 'Ray Aberration', ...
        'Checked', 'off', ...
        'Callback', {@menuRayAberration_Callback,parentWindow});
    aodHandles.menuTransverseRayAberration = uimenu( ...
        'Parent', aodHandles.menuRayAberration, ...
        'Tag', 'menuTransverseRayAberration', ...
        'Label', 'Transverse Ray Aberration', ...
        'Checked', 'off', ...
        'Callback', {@menuTransverseRayAberration_Callback,parentWindow});
    aodHandles.menuLongitudinalRayAberration = uimenu( ...
        'Parent', aodHandles.menuRayAberration, ...
        'Tag', 'menuLongitudinalRayAberration', ...
        'Label', 'Longitudinal Ray Aberration', ...
        'Checked', 'off', ...
        'Callback', {@menuLongitudinalRayAberration_Callback,parentWindow});
    
    %---------------------------------------------------------------------
    % Hybrid Diffraction Analysis
    aodHandles.menuHybridDiffraction = uimenu( ...
        'Parent', aodHandles.menuOpticalSystemAnalysis, ...
        'Tag', 'menuHybridDiffraction', ...
        'Label', 'Hybrid Diffraction', ...
        'Checked', 'off', ...
        'Callback', {@menuHybridDiffraction_Callback,parentWindow});
    aodHandles.menuWavefrontAtExitPupil = uimenu( ...
        'Parent', aodHandles.menuHybridDiffraction, ...
        'Tag', 'menuWavefrontAtExitPupil', ...
        'Label', 'Wavefront At Exit Pupil', ...
        'Checked', 'off', ...
        'Callback', {@menuWavefrontAtExitPupil_Callback,parentWindow});
    
    aodHandles.menuPupilApodization = uimenu( ...
        'Parent', aodHandles.menuHybridDiffraction, ...
        'Tag', 'menuPupilApodization', ...
        'Label', 'Pupil Apodization', ...
        'Checked', 'off', ...
        'Callback', {@menuPupilApodization_Callback,parentWindow});
    aodHandles.menuFFTPSF = uimenu( ...
        'Parent', aodHandles.menuHybridDiffraction, ...
        'Tag', 'menuFFTPSF', ...
        'Label', 'FFT PSF', ...
        'Checked', 'off', ...
        'Callback', {@menuFFTPSF_Callback,parentWindow});
    
    %----------------------------------------------------------------------
    % Polarization analysis
    aodHandles.menuPolarizationAnalysis = uimenu( ...
        'Parent', aodHandles.menuOpticalSystemAnalysis, ...
        'Tag', 'menuRayTrace', ...
        'Label', 'Polarization', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuPolarizationAnalysis_Callback,parentWindow});
    
    
    aodHandles.menuPolarizationRayTrace = uimenu( ...
        'Parent', aodHandles.menuPolarizationAnalysis, ...
        'Tag', 'menuPolarizationRayTrace', ...
        'Label', 'Polarization Ray Trace', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuPolarizationRayTrace_Callback,parentWindow});
    
    aodHandles.menuPolarizationEllipseMap = uimenu( ...
        'Parent', aodHandles.menuPolarizationAnalysis, ...
        'Tag', 'menuPolarizationEllipseMap', ...
        'Label', 'Polarization Ellipse Map', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuPolarizationEllipseMap_Callback,parentWindow});
    
    aodHandles.menuPolarizationAberration = uimenu( ...
        'Parent', aodHandles.menuPolarizationAnalysis, ...
        'Tag', 'menuPolarizationAberration', ...
        'Label', 'Polarization Aberration', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuPolarizationAberration_Callback,parentWindow});
    
    aodHandles.menuAmplitudeTransmissionMap = uimenu( ...
        'Parent', aodHandles.menuPolarizationAberration, ...
        'Tag', 'menuAmplitudeTransmissionMap', ...
        'Label', 'Amplitude Transmission Map', ...
        'Checked', 'off', ...
        'Callback', {@menuAmplitudeTransmissionMap_Callback,parentWindow});
    
    aodHandles.menuPhaseMap = uimenu( ...
        'Parent', aodHandles.menuPolarizationAberration, ...
        'Tag', 'menuPhaseMap', ...
        'Label', 'Phase Map', ...
        'Checked', 'off', ...
        'Callback', {@menuPhaseMap_Callback,parentWindow});
    
    aodHandles.menuWavefrontDiattenuationMap = uimenu( ...
        'Parent', aodHandles.menuPolarizationAberration, ...
        'Tag', 'menuWavefrontDiattenuationMap', ...
        'Label', 'Wavefront Diattenuation Map', ...
        'Checked', 'off', ...
        'Callback', {@menuWavefrontDiattenuationMap_Callback,parentWindow});
    
    aodHandles.menuWavefrontRetardanceMap = uimenu( ...
        'Parent', aodHandles.menuPolarizationAberration, ...
        'Tag', 'menuWavefrontRetardanceMap', ...
        'Label', 'Wavefront Retardance Map', ...
        'Checked', 'off', ...
        'Callback', {@menuWavefrontRetardanceMap_Callback,parentWindow});
    
    %----------------------------------------------------------------------
    % Pulse analysis
    aodHandles.menuPulseAnalysis = uimenu( ...
        'Parent', aodHandles.menuOpticalSystemAnalysis, ...
        'Tag', 'menuPulseAnalysis', ...
        'Label', 'Pulse Analysis', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuPulseAnalysis_Callback,parentWindow});
    
    
    aodHandles.menuPulseAnalysisParaxial = uimenu( ...
        'Parent', aodHandles.menuPulseAnalysis, ...
        'Tag', 'menuPulseAnalysisParaxial', ...
        'Label', 'Paraxial', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuPulseAnalysisParaxial_Callback,parentWindow});
    
    aodHandles.menuKostenbauderMatrix = uimenu( ...
        'Parent', aodHandles.menuPulseAnalysisParaxial, ...
        'Tag', 'menuKostenbauderMatrix', ...
        'Label', 'Kostenbauder Matrix', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuKostenbauderMatrix_Callback,parentWindow});
    
    aodHandles.menuGDDVsWavelength = uimenu( ...
        'Parent', aodHandles.menuPulseAnalysisParaxial, ...
        'Tag', 'menuGDDVsWavelength', ...
        'Label', 'GDD Vs Wavelength', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuGDDVsWavelength_Callback,parentWindow});
    
    aodHandles.menuSpatialChirpVsWavelength = uimenu( ...
        'Parent', aodHandles.menuPulseAnalysisParaxial, ...
        'Tag', 'menuSpatialChirpVsWavelength', ...
        'Label', 'Spatial Chirp Vs Wavelength', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuSpatialChirpVsWavelength_Callback,parentWindow});
    
    aodHandles.menuAngularDispersionVsWavelength = uimenu( ...
        'Parent', aodHandles.menuPulseAnalysisParaxial, ...
        'Tag', 'menuAngularDispersionVsWavelength', ...
        'Label', 'Angular Dispersion Vs Wavelength', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuAngularDispersionVsWavelength_Callback,parentWindow});
    
    aodHandles.menuGaussianPulsePropagation = uimenu( ...
        'Parent', aodHandles.menuPulseAnalysisParaxial, ...
        'Tag', 'menuGaussianPulsePropagation', ...
        'Label', 'Gaussian Pulse Propagation', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuGaussianPulsePropagation_Callback,parentWindow});
    
    aodHandles.menuPulseAnalysisGeometric = uimenu( ...
        'Parent', aodHandles.menuPulseAnalysis, ...
        'Tag', 'menuPulseAnalysisGeometric', ...
        'Label', 'Geometric', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuPulseAnalysisGeometric_Callback,parentWindow});
    
    aodHandles.menuPulseFrontEvolutionGeometric = uimenu( ...
        'Parent', aodHandles.menuPulseAnalysisGeometric, ...
        'Tag', 'menuPulseFrontEvolutionGeometric', ...
        'Label', 'Pulse Front Evolution', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuPulseFrontEvolutionGeometric_Callback,parentWindow});
    
    aodHandles.menuPulseAnalysisHybridDiffraction = uimenu( ...
        'Parent', aodHandles.menuPulseAnalysis, ...
        'Tag', 'menuPulseAnalysisHybridDiffraction', ...
        'Label', 'Hybrid Diffraction', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuPulseAnalysisHybridDiffraction_Callback,parentWindow});
    
    aodHandles.menuFFTFocusedPulse = uimenu( ...
        'Parent', aodHandles.menuPulseAnalysisHybridDiffraction, ...
        'Tag', 'menuFFTFocusedPulse', ...
        'Label', 'FFT Focused Pulse', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuFFTFocusedPulse_Callback,parentWindow});
    
    
    %-----------------------------------------------------------------------
    aodHandles.menuCoating = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuCoating', ...
        'Label', 'Coating', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuCoating_Callback,parentWindow});
    
    aodHandles.menuCoatingDataEditor = uimenu( ...
        'Parent', aodHandles.menuCoating, ...
        'Tag', 'menuNewCoating', ...
        'Visible', 'on', ...
        'Label', 'Coating Data Editor', ...
        'Checked', 'off', ...
        'Callback', {@menuCoatingDataEditor_Callback,parentWindow});
    
    aodHandles.menuCoatingAnalysis = uimenu( ...
        'Parent', aodHandles.menuCoating, ...
        'Tag', 'menuCoatingAnalysis', ...
        'Label', 'CoatingAnalysis', ...
        'Checked', 'off', ...
        'Callback', {@menuCoatingAnalysis_Callback,parentWindow});
    
    aodHandles.menuRefractiveIndexProfile = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuRefractiveIndexProfile', ...
        'Label', 'Refractive Index Profile', ...
        'Checked', 'off', ...
        'Callback', {@menuRefractiveIndexProfile_Callback,parentWindow});
    
    aodHandles.menuTransmissionVsAngle = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuTransmissionVsAngle', ...
        'Label', 'Transmission Vs Angle', ...
        'Checked', 'off', ...
        'Callback', {@menuTransmissionVsAngle_Callback,parentWindow});
    
    aodHandles.menuReflectionVsAngle = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuReflectionVsAngle', ...
        'Label', 'Reflection Vs Angle', ...
        'Checked', 'off', ...
        'Callback', {@menuReflectionVsAngle_Callback,parentWindow});
    
    aodHandles.menuDiattenuationVsAngle = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuDiattenuationVsAngle', ...
        'Label', 'Diattenuation Vs Angle', ...
        'Checked', 'off', ...
        'Callback', {@menuDiattenuationVsAngle_Callback,parentWindow});
    
    aodHandles.menuRetardanceVsAngle = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuRetardanceVsAngle', ...
        'Label', 'Retardance Vs Angle', ...
        'Checked', 'off', ...
        'Callback', {@menuRetardanceVsAngle_Callback,parentWindow});
    
    aodHandles.menuTransmissionVsWavelength = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuTransmissionVsWavelength', ...
        'Label', 'Transmission Vs Wavelength', ...
        'Checked', 'off', ...
        'Callback', {@menuTransmissionVsWavelength_Callback,parentWindow});
    
    aodHandles.menuReflectionVsWavelength = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuReflectionVsWavelength', ...
        'Label', 'Reflection Vs Wavelength', ...
        'Checked', 'off', ...
        'Callback', {@menuReflectionVsWavelength_Callback,parentWindow});
    
    aodHandles.menuDiattenuationVsWavelength = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuDiattenuationVsWavelength', ...
        'Label', 'Diattenuation Vs Wavelength', ...
        'Checked', 'off', ...
        'Callback', {@menuDiattenuationVsWavelength_Callback,parentWindow});
    
    aodHandles.menRetardanceVsWavelength = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menRetardanceVsWavelength', ...
        'Label', 'Retardance Vs Wavelength', ...
        'Checked', 'off', ...
        'Callback', {@menRetardanceVsWavelength_Callback,parentWindow});
    
    aodHandles.menuCoatingCatalogue = uimenu( ...
        'Parent', aodHandles.menuCoating, ...
        'Tag', 'menuCoatingCatalogue', ...
        'Visible', 'on', ...
        'Label', 'Coating Catalogue', ...
        'Checked', 'off', ...
        'Callback', {@menuCoatingCatalogue_Callback,parentWindow});
    
    aodHandles.menuNewCoatingCatalogue = uimenu( ...
        'Parent', aodHandles.menuCoatingCatalogue, ...
        'Tag', 'menuNewCoatingCatalogue', ...
        'Visible', 'on', ...
        'Label', 'New Coating Catalogue', ...
        'Checked', 'off', ...
        'Callback', {@menuNewCoatingCatalogue_Callback,parentWindow});
    
    aodHandles.menuCoatingCatalogueAnalysis = uimenu( ...
        'Parent', aodHandles.menuCoatingCatalogue, ...
        'Tag', 'menuCoatingCatalogueAnalysis', ...
        'Visible', 'off', ...
        'Label', 'Coating Catalogue Analysis', ...
        'Checked', 'off', ...
        'Callback', {@menuCoatingCatalogueAnalysis_Callback,parentWindow});
    
    aodHandles.menuImportCoatingCatalogue = uimenu( ...
        'Parent', aodHandles.menuCoatingCatalogue, ...
        'Tag', 'menuImportCoatingCatalogue', ...
        'Visible', 'off', ...
        'Label', 'Import Coating Catalogue', ...
        'Checked', 'off', ...
        'Callback', {@menuImportCoatingCatalogue_Callback,parentWindow});
    
    aodHandles.menuExportCoatingCatalogue = uimenu( ...
        'Parent', aodHandles.menuCoatingCatalogue, ...
        'Tag', 'menuExportCoatingCatalogue', ...
        'Visible', 'off', ...
        'Label', 'Export Coating Catalogue', ...
        'Checked', 'off', ...
        'Callback', {@menuExportCoatingCatalogue_Callback,parentWindow});
    
    aodHandles.menuGlass = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuGlass', ...
        'Label', 'Glass', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuGlass_Callback,parentWindow});
    
    aodHandles.menuGlassDataEditor = uimenu( ...
        'Parent', aodHandles.menuGlass, ...
        'Tag', 'menuGlassDataEditor', ...
        'Label', 'Glass Data Editor', ...
        'Checked', 'off', ...
        'Callback', {@menuGlassDataEditor_Callback,parentWindow});
    
    aodHandles.menuGlassAnalysis = uimenu( ...
        'Parent', aodHandles.menuGlass, ...
        'Tag', 'menuGlassAnalysis', ...
        'Visible', 'off', ...
        'Label', 'Glass Analysis', ...
        'Checked', 'off', ...
        'Callback', {@menuGlassAnalysis_Callback,parentWindow});
    
    aodHandles.menuDispersionGraph = uimenu( ...
        'Parent', aodHandles.menuGlassAnalysis, ...
        'Tag', 'menuDispersionGraph', ...
        'Visible', 'off', ...
        'Label', 'Dispersion Graph', ...
        'Checked', 'off', ...
        'Callback', {@menuDispersionGraph_Callback,parentWindow});
    
    aodHandles.menuGlassCatalogue = uimenu( ...
        'Parent', aodHandles.menuGlass, ...
        'Tag', 'menuGlassCatalogue', ...
        'Label', 'Glass Catalogue', ...
        'Visible','on',...
        'Checked', 'off', ...
        'Callback', {@menuGlassCatalogue_Callback,parentWindow});
    
    aodHandles.menuNewGlassCatalogue = uimenu( ...
        'Parent', aodHandles.menuGlassCatalogue, ...
        'Tag', 'menuNewGlassCatalogue', ...
        'Visible', 'on', ...
        'Label', 'New Glass Catalogue', ...
        'Checked', 'off', ...
        'Callback', {@menuNewGlassCatalogue_Callback,parentWindow});
    
    aodHandles.menuImportGlassCatalogue = uimenu( ...
        'Parent', aodHandles.menuGlassCatalogue, ...
        'Tag', 'menuImportGlassCatalogue', ...
        'Label', 'Import Glass Catalogue', ...
        'Checked', 'off', ...
        'Visible', 'on', ...
        'Callback', {@menuImportGlassCatalogue_Callback,parentWindow});
    aodHandles.menuImportGlassCatalogueFromSchottXls = uimenu( ...
        'Parent', aodHandles.menuImportGlassCatalogue, ...
        'Tag', 'menuImportGlassCatalogueFromSchottXls', ...
        'Label', 'From Schott XLS', ...
        'Checked', 'off', ...
        'Visible', 'on', ...
        'Callback', {@menuImportGlassCatalogueFromSchottXLS_Callback,parentWindow});
    aodHandles.menuImportGlassCatalogueFromZemaxAgf = uimenu( ...
        'Parent', aodHandles.menuImportGlassCatalogue, ...
        'Tag', 'menuImportGlassCatalogueFromZemaxAgf', ...
        'Label', 'From Zemax AGF', ...
        'Checked', 'off', ...
        'Visible', 'on', ...
        'Callback', {@menuImportGlassCatalogueFromZemaxAGF_Callback,parentWindow});
    
    aodHandles.menuExportGlassCatalogue = uimenu( ...
        'Parent', aodHandles.menuGlassCatalogue, ...
        'Tag', 'menuExportGlassCatalogue', ...
        'Visible', 'off', ...
        'Label', 'Export Glass Catalogue', ...
        'Checked', 'off', ...
        'Callback', {@menuExportGlassCatalogue_Callback,parentWindow});
    
    aodHandles.menuGlassCatalogueAnalysis = uimenu( ...
        'Parent', aodHandles.menuGlassCatalogue, ...
        'Tag', 'menuGlassCatalogueAnalysis', ...
        'Visible', 'off', ...
        'Label', 'Glass Catalogue Analysis', ...
        'Checked', 'off', ...
        'Callback', {@menuGlassCatalogueAnalysis_Callback,parentWindow});
    %------------------------------------------------------------------------
    aodHandles.menuWindows = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuWindows', ...
        'Label', 'Windows', ...
        'Checked', 'off', ...
        'Callback', {@menuWindows_Callback,parentWindow});
    
    aodHandles.menuCloseAllWindows = uimenu( ...
        'Parent', aodHandles.menuWindows, ...
        'Tag', 'menuCloseAllWindows', ...
        'Label', 'Close All', ...
        'Checked', 'off', ...
        'Callback', {@menuCloseAllWindows_Callback,parentWindow});
    
    aodHandles.menuOpenedWindows(1) = uimenu( ...
        'Parent', aodHandles.menuWindows, ...
        'Tag', 'menuOpenedWindows', ...
        'Label', 'Opened Window List', ...
        'Separator','on',...
        'Checked', 'off');
    %------------------------------------------------------------------------
    
    aodHandles.menuHelp = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuHelp', ...
        'Label', 'Help', ...
        'Checked', 'off', ...
        'Callback', {@menuHelp_Callback,parentWindow});
    
    aodHandles.menuAbout = uimenu( ...
        'Parent', aodHandles.menuHelp, ...
        'Tag', 'menuAbout', ...
        'Label', 'About', ...
        'Checked', 'off', ...
        'Callback', {@menuAbout_Callback,parentWindow});
    
    aodHandles.menuUserManual = uimenu( ...
        'Parent', aodHandles.menuHelp, ...
        'Tag', 'menuUserManual', ...
        'Label', 'User Manual', ...
        'Checked', 'off', ...
        'Callback', {@menuUserManual_Callback,parentWindow});
    
    aodHandles.menuProgrammingAndAlgorithmsReference = uimenu( ...
        'Parent', aodHandles.menuHelp, ...
        'Tag', 'menuProgrammingAndAlgorithmsReference', ...
        'Label', 'Programming and Algorithms Reference', ...
        'Checked', 'off', ...
        'Callback', {@menuProgrammingAndAlgorithmsReference_Callback,parentWindow});
    aodHandles.menuSourceCodeExplorer = uimenu( ...
        'Parent', aodHandles.menuHelp, ...
        'Tag', 'menuSourceCodeExplorer', ...
        'Label', 'Source Code Explorer', ...
        'Checked', 'off', ...
        'Callback', {@menuSourceCodeExplorer_Callback,parentWindow});
    
    
    parentWindow.ParentHandles = aodHandles;
    %% Toolbar Icons
end
%% Menu Item Callbacks

% ---------------------------------------------------------------------
function menuFile_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuEdit_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuOptimization_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuPolarizationAnalysis_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuHybridDiffraction_Callback(~,~,parentWindow)
    
end
% ---------------------------------------------------------------------
function menuWavefrontAtExitPupil_Callback(~,~,parentWindow)
    ChildWindow('wavefrontAtExitPupil',parentWindow);
end
% ---------------------------------------------------------------------
function menuPupilApodization_Callback(~,~,parentWindow)
    ChildWindow('pupilApodization',parentWindow);
end
% ---------------------------------------------------------------------
function menuFFTPSF_Callback(~,~,parentWindow)
    ChildWindow('FFTPSF',parentWindow);
end

% ---------------------------------------------------------------------
function menuHelp_Callback(~,~,parentWindow)
end

% ---------------------------------------------------------------------

function menuCloseAllWindows_Callback(~,~,parentWindow)
    [ childsclosed ] = closeAllChildWindows(parentWindow);
end
function menuWindows_Callback(~,~,parentWindow)
end


% ---------------------------------------------------------------------
function menuView_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuScalarRayTrace_Callback(~,~,parentWindow)
    ChildWindow('scalarRayTrace',parentWindow);
end
% ---------------------------------------------------------------------
function menuSurfaceProperties_Callback(~,~,parentWindow)
    
end
% ---------------------------------------------------------------------
function menuSystemConfiguration_Callback(~,~,parentWindow)
    updateSystemConfigurationWindow( parentWindow )
    set(parentWindow.ParentHandles.SystemConfigurationFigureHandle,'Visible','on');
end
% ---------------------------------------------------------------------
function menuComponents_Callback(~,~,parentWindow)
    
end
% ---------------------------------------------------------------------


function menuNew_Callback(~,~,parentWindow)
    parentWindow.openNewOpticalSystem;
end

% ---------------------------------------------------------------------
function menuOpen_Callback(~,~,parentWindow)
    
    [FileName,PathName] = uigetfile('*.mat','Select Optical System file');
    if (FileName~=0) % FileName=0 when no file is selected
        fullFileName = [PathName, FileName];
        parentWindow.openFromMATFile(fullFileName);
    else
        return
    end
end
% ---------------------------------------------------------------------
function menuSave_Callback(~,~,parentWindow)
    parentWindow.saveMySystem;
end

% ---------------------------------------------------------------------
function menuSavaAs_Callback(~,~,parentWindow)
    parentWindow.saveMySystemAs;
end

% ---------------------------------------------------------------------
function menuClose_Callback(~,~,parentWindow)
    parentWindow.closeAllWindows();
end

% ---------------------------------------------------------------------
function menu2DSystemLayout_Callback(~,~,parentWindow)
    ChildWindow('system2DLayoutDiagram',parentWindow);
end
% ---------------------------------------------------------------------
function menu3DSystemLayout_Callback(~,~,parentWindow)
    ChildWindow('system3DLayoutDiagram',parentWindow);
end
% ---------------------------------------------------------------------
function menuUserManual_Callback(~,~,parentWindow)
    winopen(which('User Manual MATLAB Based Optical Analysis Toolbox V 3.0.chm'))
end

% ---------------------------------------------------------------------
function menuAbout_Callback(~,~,parentWindow)
    aodHandles = parentWindow.ParentHandles;
    fontSize = aodHandles.FontSize;
    fontName = aodHandles.FontName;
    aboutWindow(fontName);
end

% ---------------------------------------------------------------------
function menuImportGlassCatalogue_Callback(~,~,parentWindow)
    
end
% ---------------------------------------------------------------------
function menuImportGlassCatalogueFromSchottXLS_Callback(~,~,parentWindow)
    %Read from excel sheet downloaded from Schott website
    [~,catFullFileName] = importXLSSchottGlassCatalogue();
    
    % Add the new imported catalogue to glass catalogue list
    addGlassCatalogue(parentWindow,catFullFileName);
    
end    % ---------------------------------------------------------------------
function menuImportGlassCatalogueFromZemaxAGF_Callback(~,~,parentWindow)
    %Read from zemax AGF file
    [~,catFullFileName] = importAGFGlassCatalogue();
    % Add the new imported catalogue to glass catalogue list
    addGlassCatalogue(parentWindow,catFullFileName);
    
end



% ---------------------------------------------------------------------
function menuCoatingCatalogue_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuImportZMXFile_Callback(~,~,parentWindow)
    [FileName,PathName] = uigetfile('*.zmx','Select Zemax file');
    if (FileName~=0) % FileName=0 when no file is selected
        zmxFullFileName = [PathName,'\',FileName];
        parentWindow.openFromZemaxFile(zmxFullFileName)
    else
        return
    end
end

% ---------------------------------------------------------------------
function menuPolarizationRayTrace_Callback(~,~,parentWindow)
    ChildWindow('polarizationRayTrace',parentWindow);
end

% ---------------------------------------------------------------------
function menuCoatingAnalysis_Callback(~,~,parentWindow)
    
end
% ---------------------------------------------------------------------
function menuRefractiveIndexProfile_Callback(~,~,parentWindow)
    ChildWindow('coatingRefractiveIndexProfile',parentWindow);
end
% ---------------------------------------------------------------------
function menuTransmissionVsAngle_Callback(~,~,parentWindow)
    ChildWindow('coatingTransmissionVsAngle',parentWindow);
end

% ---------------------------------------------------------------------
function menuReflectionVsAngle_Callback(~,~,parentWindow)
    ChildWindow('coatingReflectionVsAngle',parentWindow);
end
% ---------------------------------------------------------------------
function menuDiattenuationVsAngle_Callback(~,~,parentWindow)
    ChildWindow('coatingDiattenuationVsAngle',parentWindow);
end
% ---------------------------------------------------------------------
function menuRetardanceVsAngle_Callback(~,~,parentWindow)
    ChildWindow('coatingRetardanceVsAngle',parentWindow);
end

% ---------------------------------------------------------------------
function menuTransmissionVsWavelength_Callback(~,~,parentWindow)
    ChildWindow('coatingTransmissionVsWavelength',parentWindow);
end
% ---------------------------------------------------------------------
function menuReflectionVsWavelength_Callback(~,~,parentWindow)
    ChildWindow('coatingReflectionVsWavelength',parentWindow);
end

% ---------------------------------------------------------------------
function menuDiattenuationVsWavelength_Callback(~,~,parentWindow)
    ChildWindow('coatingDiattenuationVsWavelength',parentWindow);
end

% ---------------------------------------------------------------------
function menRetardanceVsWavelength_Callback(~,~,parentWindow)
    ChildWindow('coatingRetardanceVsWavelength',parentWindow);
end

% ---------------------------------------------------------------------
function menuOpticalSystem_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuFootprintDiagram_Callback(~,~,parentWindow)
    ChildWindow('FootprintDiagram',parentWindow);
end
% ---------------------------------------------------------------------
function menuPolarizationEllipseMap_Callback(~,~,parentWindow)
    ChildWindow('polarizationEllipseMap',parentWindow);
end
% ---------------------------------------------------------------------
function menuParaxialAnalysis_Callback(~,~,parentWindow)
    ChildWindow('paraxialAnalysis',parentWindow);
end

% ---------------------------------------------------------------------
function menuTransverseRayAberration_Callback(~,~,parentWindow)
    ChildWindow('transverseRayAberration',parentWindow);
end

% ---------------------------------------------------------------------
function menuPolarizationAberration_Callback(~,~,parentWindow)
end

% ---------------------------------------------------------------------
function menuAmplitudeTransmissionMap_Callback(~,~,parentWindow)
    ChildWindow('amplitudeTransmissionMap',parentWindow);
end
% ---------------------------------------------------------------------
function menuPhaseMap_Callback(~,~,parentWindow)
    ChildWindow('phaseMap',parentWindow);
end
% ---------------------------------------------------------------------
function menuWavefrontDiattenuationMap_Callback(~,~,parentWindow)
    ChildWindow('wavefrontDiattenuationMap',parentWindow);
end
% ---------------------------------------------------------------------
function menuWavefrontRetardanceMap_Callback(~,~,parentWindow)
    ChildWindow('wavefrontRetardanceMap',parentWindow);
end

% ---------------------------------------------------------------------
function menuCoating_Callback(~,~,parentWindow)
    
end



function menuGlassDataEditor_Callback(~,~,parentWindow)
    [ currentOpticalSystem,saved] = ...
        parentWindow.getCurrentOpticalSystem;
    aodHandles = parentWindow.ParentHandles;
    if saved % valid system and saved
        % Glass Catalogue
        tableData1 = get(aodHandles.tblGlassCatalogues,'data');
        if ~isempty(tableData1)
            % Take only the selected ones
            selectedRows1 = find(cell2mat(tableData1(:,1)));
            if ~isempty(selectedRows1)
                glassCatalogueListFullNames = tableData1(selectedRows1,3);
            else
                glassCatalogueListFullNames = '';
            end
        else
            glassCatalogueListFullNames = '';
        end
        fontSize = aodHandles.FontSize;
        fontName = aodHandles.FontName;
        
        glassDataInputDialog(glassCatalogueListFullNames,fontName,fontSize);
    else
    end
end

% ---------------------------------------------------------------------
function menuCoatingDataEditor_Callback(~,~,parentWindow)
    [ currentOpticalSystem,saved] = ...
        parentWindow.getCurrentOpticalSystem;
    aodHandles = parentWindow.ParentHandles;
    if saved % Valid system and saved
        % Coating Catalogue
        tableData1 = get(aodHandles.tblCoatingCatalogues,'data');
        if ~isempty(tableData1)
            % Take only the selected ones
            selectedRows1 = find(cell2mat(tableData1(:,1)));
            if ~isempty(selectedRows1)
                coatingCatalogueListFullNames = tableData1(selectedRows1,3);
            else
                coatingCatalogueListFullNames = '';
            end
        else
            coatingCatalogueListFullNames = '';
        end
        fontSize = aodHandles.FontSize;
        fontName = aodHandles.FontName;
        primaryWavLenInUm = getPrimaryWavelength(currentOpticalSystem)*10^6;
        coatingDataInputDialog(primaryWavLenInUm,coatingCatalogueListFullNames,fontName,fontSize);
    else
        
    end
end

% ---------------------------------------------------------------------
function menuImportOpticalSystem_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuExportOpticalSystem_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuNewCoatingCatalogue_Callback(~,~,parentWindow)
    addCoatingCatalogue(parentWindow);
end


% ---------------------------------------------------------------------
function menuCoatingCatalogueAnalysis_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuImportCoatingCatalogue_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuExportCoatingCatalogue_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuGlass_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuProgrammingAndAlgorithmsReference_Callback(~,~,parentWindow)
    winopen(which('Programming and Algorithms Reference MATLAB Based Optical Analysis Toolbox V 3.0.chm'))
end
% ---------------------------------------------------------------------
function menuSourceCodeExplorer_Callback(~,~,parentWindow)
    web(which('SourceCodeExplorerIndexV3.html'))
end
% ---------------------------------------------------------------------
function menuNewGlass_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuGlassAnalysis_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuGlassCatalogue_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuNewGlassCatalogue_Callback(~,~,parentWindow)
    addGlassCatalogue(parentWindow);
end


% ---------------------------------------------------------------------
function menuExportGlassCatalogue_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuGlassCatalogueAnalysis_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuDispersionGraph_Callback(~,~,~)
    
end

% ---------------------------------------------------------------------
function menuOpticalSystemAnalysis_Callback(~,~,~)
    
end

% ---------------------------------------------------------------------
function menuImageAtBfp_Callback(~,~,~,parentWindow)
    aodHandles = parentWindow.ParentHandles;
    % determine the back focal length of the optical system
    SavedOpticalSystem = parentWindow.getCurrentOpticalSystem;
    bfl = SavedOpticalSystem.getBackFocalLength;
    
    % set the last thickness = bfl
    tblData1 = get(aodHandles.tblStandardData,'data');
    imgSurfIndex = SavedOpticalSystem.NumberOfSurface;
    tblData1{imgSurfIndex-1,7} = num2str(bfl);
    set(aodHandles.tblStandardData, 'Data', tblData1);
end

% ---------------------------------------------------------------------
function menuRayAberration_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuLongitudinalRayAberration_Callback(~,~,parentWindow)
    opticalSystem = parentWindow.ParentHandles.OpticalSystem;
    [ success ] = plotLongitudinalAberration(opticalSystem);
%     try
%         testLongitudinalAberration;
%     catch
%         disp('Error: The Longitudinal Ray Aberration function is not defined.');
%     end
end

% ---------------------------------------------------------------------
function menuPulseAnalysis_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuPulseAnalysisParaxial_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuKostenbauderMatrix_Callback(~,~,parentWindow)
    ChildWindow('KostenbauderMatrix',parentWindow);
end

% ---------------------------------------------------------------------
function menuGDDVsWavelength_Callback(~,~,parentWindow)
    ChildWindow('GDDVsWavelength',parentWindow);
end
% ---------------------------------------------------------------------
function menuSpatialChirpVsWavelength_Callback(~,~,parentWindow)
    ChildWindow('SpatialChirpVsWavelength',parentWindow);
end
% ---------------------------------------------------------------------
function menuAngularDispersionVsWavelength_Callback(~,~,parentWindow)
    ChildWindow('AngularDispersionVsWavelength',parentWindow);
end

% ---------------------------------------------------------------------
function menuGaussianPulsePropagation_Callback(~,~,parentWindow)
    ChildWindow('GaussianPulsePropagation',parentWindow);
end

% ---------------------------------------------------------------------
function menuPulseAnalysisGeometric_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuPulseFrontEvolutionGeometric_Callback(~,~,parentWindow)
    ChildWindow('PulseFrontEvolutionGeometric',parentWindow);
end

% ---------------------------------------------------------------------
function menuPulseAnalysisHybridDiffraction_Callback(~,~,parentWindow)
    
end

% ---------------------------------------------------------------------
function menuFFTFocusedPulse_Callback(~,~,parentWindow)
    ChildWindow('FFTFocusedPulse',parentWindow);
end

