function [ surfaceStruct ] = SurfaceStruct(surfType)
    
        % Connect the surface definition function
    surfaceDefinitionHandle = str2func(surfType);
    returnFlag = 'SSPB';
    [fieldNames,fieldFormat,defaultUniqueParamStruct] = surfaceDefinitionHandle(returnFlag);
    
    surfaceStruct = struct(...
    'ObjectSurface', 0,...
    'ImageSurface',0,...
    'Stop',0,...
    'Comment','',...
    'Type',surfType,...
    'Thickness',5,...
    'ExtraData',[],...
    'Glass',Glass(),...
    'UniqueParameters',defaultUniqueParamStruct,...
    'Aperture',Aperture(),...
    'Coating',Coating(),...
    'TiltDecenterOrder',{{'Dx','Dy','Dz','Tx','Ty','Tz'}},...
    'Tilt',[0 0 0],...
    'Decenter',[0 0],...
    'TiltMode','DAR',...
    'SurfaceCoordinateTM', [1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1],...
    'ReferenceCoordinateTM',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1],...
    'SurfaceColor','',...
    'Hidden',0,...
    'Ignored',0,...
    'getRadiusOfCurvatureStruct',{@getRadiusOfCurvatureStruct});
end

