function figureHandle = aboutWindow(fontName)
% About Window

% Default Input
if nargin < 1
    fontName = 'FixedWidth';      
end

% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
figureHandle = handles.About;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

		% --- FIGURE -------------------------------------
		handles.About = figure( ...
			'Tag', 'About', ...
			'Units', 'normalized', ...
			'Position', [0.25 0.3 0.45 0.4], ...
			'Name', 'About', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
			'Color', get(0,'DefaultUicontrolBackgroundColor'));

		% --- STATIC TEXTS -------------------------------------
		handles.text1 = uicontrol( ...
			'Parent', handles.About, ...
			'Tag', 'text1', ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.1 0.8 0.8 0.1], ...
			'FontSize', 14,'FontName',fontName,...
			'String', 'MatLightTracer: Matlab Light Tracing Toolbox');
        handles.text4 = uicontrol( ...
			'Parent', handles.About, ...
			'Tag', 'text4', ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.1 0.7 0.8 0.1], ...
			'FontSize', 13,'FontName',fontName,...
			'String', 'Friedrich Schiller University of Jena');
		handles.text3 = uicontrol( ...
			'Parent', handles.About, ...
			'Tag', 'text3', ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.1 0.6 0.8 0.1], ...
			'FontSize', 12,'FontName',fontName,...
			'String', 'Institute of Applied Physics'); 
        
        handles.text2 = uicontrol( ...
			'Parent', handles.About, ...
			'Tag', 'text2', ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.1 0.5 0.8 0.1], ...
			'FontSize', 12,'FontName',fontName,...
			'String', 'Optical System Design Research Group');

		handles.text5 = uicontrol( ...
			'Parent', handles.About, ...
			'Tag', 'text5', ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.1 0.4 0.8 0.1], ...
			'FontSize', 11,'FontName',fontName,...
			'String', 'Version 1.0');

		handles.text6 = uicontrol( ...
			'Parent', handles.About, ...
			'Tag', 'text6', ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.1 0.3 0.8 0.1], ...
			'FontSize', 11,'FontName',fontName,...
			'String', 'Contact: Norman G. Worku (normangirma2012@gmail.com)');

		handles.text7 = uicontrol( ...
			'Parent', handles.About, ...
			'Tag', 'text7', ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.1 0.2 0.8 0.1], ...
			'FontSize', 11,'FontName',fontName,...
			'String', 'Date: June 01, 2015');



		% --- PUSHBUTTONS -------------------------------------
		handles.btnOk = uicontrol( ...
			'Parent', handles.About, ...
			'Tag', 'btnOk', ...
			'Style', 'pushbutton', ...
			'Units', 'normalized', ...
			'Position', [0.4 0.05 0.2 0.1], ...
			'String', 'Ok', ...
            'FontName',fontName,...
			'Callback', @btnOk_Callback);
	end

%% ---------------------------------------------------------------------------
	function btnOk_Callback(hObject,evendata) %#ok<INUSD>
       close(figureHandle);
	end

end
