Description of convertJVToPolVector
convertJVToPolVector
PURPOSE
convertJonesVectToPolVect Converts a given jones vector to polarization
SYNOPSIS
function polarizationVector = convertJVToPolVector(JV,dirK)
DESCRIPTION
 convertJonesVectToPolVect Converts a given jones vector to polarization
 vector. The function is vectorized so if the inputs are vectors then
 the output will also be vector of the same size.
 Inputs:
   JV: % 2xN matrix : complex valued jones vector in s-p axis
                      [Jsmag*exp(i*Jsphase);Jpmag*exp(i*Jpphase)]
   dirK: 3XN matrix : direction cosines of the ray
 Outputs:
   polarizationVector: 3XN matrix : The electric field vector
CROSS-REFERENCE INFORMATION
This function calls:
changeCoordinate changeCoordinate: Returns the point (ps,pp,pk) in spk in the new
directionSP directionSP returns direction cosines of local s and p vectors given k
This function is called by:
tracePolarizedRay tracePolarizedRay: main function of polarized ray tracer
Ray
SOURCE CODE
function polarizationVector = convertJVToPolVector(JV,dirK)
    % convertJonesVectToPolVect Converts a given jones vector to polarization
    % vector. The function is vectorized so if the inputs are vectors then
    % the output will also be vector of the same size.
    %
    % Inputs:
    %   JV: % 2xN matrix : complex valued jones vector in s-p axis
    %                      [Jsmag*exp(i*Jsphase);Jpmag*exp(i*Jpphase)]
    %   dirK: 3XN matrix : direction cosines of the ray
    % Outputs:
    %   polarizationVector: 3XN matrix : The electric field vector
    % <<<<<<<<<<<<<<<<<<<<<<< Algorithm Section>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %
    % <<<<<<<<<<<<<<<<<<<<<<<<< Example Usage>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %
    % <<<<<<<<<<<<<<<<<<<<<<<<< Author Section >>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %   Written By: Worku, Norman Girma
    %   Advisor: Prof. Herbert Gross
    %   Part of the RAYTRACE_TOOLBOX V3.0 (OOP Version)
    %    Optical System Design and Simulation Research Group
    %   Institute of Applied Physics
    %   Friedrich-Schiller-University of Jena
    % <<<<<<<<<<<<<<<<<<< Change History Section >>>>>>>>>>>>>>>>>>>>>>>>>>
    % Date----------Modified By ---------Modification Detail--------Remark
    % Oct 14,2013   Worku, Norman G.     Original Version       Version 3.0
    % Jan 18,2014   Worku, Norman G.     Vectorized inputs and outputs
    % <<<<<<<<<<<<<<<<<<<<< Main Code Section >>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    % Extract the S and P component from the jones vector
    fieldS = JV(1,:);
    fieldP = JV(2,:);
    [dirS,dirP] = directionSP(dirK);
    [Fx,Fy,Fz] = changeCoordinate(fieldS,fieldP,0,dirS,dirP,dirK);
    polarizationVector = [Fx;Fy;Fz];
end