Description of draw3DLens
draw3DLens
PURPOSE
draw3DLens: Plots the 3 dimensional lay out of alens in 3d Space
SYNOPSIS
function [ lensH,xyzPoints1, xyzPoints2] = draw3DLens(surf1CoordinateTM,rad1,conic1,semiDiam1,surf2CoordinateTM,rad2,conic2,semiDiam2,axesHandle,radSpacing,lensColor)
DESCRIPTION
 draw3DLens: Plots the 3 dimensional lay out of alens in 3d Space
 given its two surfaces
 Inputs
   surf1CoordinateTM,rad1,conic1,semiDiam1: coordinate transfer matrix
                        , radius, conic constant and
   semidiameter of the surface 1 ( the same is true for the second surface)
   axesHandle: axes to plot the lens
   radSpacing: radius sampling Spacing
 Output
   lensH:  height of the lens drawn
CROSS-REFERENCE INFORMATION
This function calls:
draw3DSurface draw3DSurface: Drwas a single surface in 3D layout diagram
This function is called by:
draw3DMirror draw3DSMirror: Drwas a single Mirror in 3D layout diagram
plot3DLayout plot3DSurface: Drwas a 3D layout diagram
SOURCE CODE
function [ lensH,xyzPoints1, xyzPoints2] = draw3DLens(surf1CoordinateTM,rad1,conic1,semiDiam1, ...
    surf2CoordinateTM,rad2,conic2,semiDiam2,axesHandle,radSpacing,lensColor )
    % draw3DLens: Plots the 3 dimensional lay out of alens in 3d Space
    % given its two surfaces
    % Inputs
    %   surf1CoordinateTM,rad1,conic1,semiDiam1: coordinate transfer matrix
    %                        , radius, conic constant and
    %   semidiameter of the surface 1 ( the same is true for the second surface)
    %   axesHandle: axes to plot the lens
    %   radSpacing: radius sampling Spacing
    % Output
    %   lensH:  height of the lens drawn
    % <<<<<<<<<<<<<<<<<<<<<<< Algorithm Section>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %
    % <<<<<<<<<<<<<<<<<<<<<<<<< Example Usage>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %
    % <<<<<<<<<<<<<<<<<<<<<<<<< Author Section >>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %   Written By: Worku, Norman Girma
    %   Advisor: Prof. Herbert Gross
    %   Part of the RAYTRACE_TOOLBOX V3.0 (OOP Version)
    %    Optical System Design and Simulation Research Group
    %   Institute of Applied Physics
    %   Friedrich-Schiller-University of Jena
    % <<<<<<<<<<<<<<<<<<< Change History Section >>>>>>>>>>>>>>>>>>>>>>>>>>
    % Date----------Modified By ---------Modification Detail--------Remark
    % Oct 14,2013   Worku, Norman G.     Original Version       Version 3.0
    % <<<<<<<<<<<<<<<<<<<<< Main Code Section >>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    lensHeight = max(min(abs([rad1,semiDiam1])),min(abs([rad2,semiDiam2])));
    actualSurfHeight1 = semiDiam1;
    drawnSurfHeight1 = lensHeight;
    actualSurfHeight2 = semiDiam2;
    drawnSurfHeight2 = lensHeight;
    % Compute the surface coordinate points for 2D plots with out plotting the
    % individual surfaces.
    [ surfH1,xyzPoints1 ] = draw3DSurface(surf1CoordinateTM,rad1,conic1,...
        actualSurfHeight1,drawnSurfHeight1,-1,radSpacing);
    [ surfH2,xyzPoints2 ] = draw3DSurface(surf2CoordinateTM,rad2,conic2,...
        actualSurfHeight2,drawnSurfHeight2,-1,radSpacing);
    x1 = xyzPoints1(:,:,1);
    y1 = xyzPoints1(:,:,2);
    z1 = xyzPoints1(:,:,3);
    x2 = xyzPoints2(:,:,1);
    y2 = xyzPoints2(:,:,2);
    z2 = xyzPoints2(:,:,3);
    % Draw the lens surfaces
    surf(axesHandle,x1,z1,y1,'facecolor',lensColor,...
        'edgecolor','none',...
        'facelighting','phong');
    hold on;
    surf(axesHandle,x2,z2,y2,'facecolor',lensColor,...
        'edgecolor','none',...
        'facelighting','phong');
    % Draw lens edges with black line
    borderColor = [0.6,0.6,0.6];
    plot3(x2(1,:),z2(1,:),y2(1,:),'Color',borderColor,'Parent',axesHandle)
    plot3(x1(1,:),z1(1,:),y1(1,:),'Color',borderColor,'Parent',axesHandle)
    % Draw lens edges surface
    surf(axesHandle,[x2(1,:); x1(1,:)],[z2(1,:); z1(1,:)],[y2(1,:); y1(1,:)],...
        'facecolor',lensColor,'edgecolor','none','facelighting','phong');
    hold off;
    lensH = lensHeight;