Description of AODParentWindow
AODParentWindow
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
AODParentWindow
resetParentParameters RESETOTHERPARAMETERS resets parameters of the parentWindow
This function is called by:
AODChildWindow
AODParentWindow
StartUp Simply call the parent window class
SUBFUNCTIONS
function parentWindow = AODParentWindow()
SOURCE CODE
classdef AODParentWindow < handle
    % AODParentWindow: Class definition for main window and all its components
    % More than one parent windows can be intiated at the same time and
    % work completely independantely.
    % Properties: 2
    %       AODParentHandles: Struct which has all components of the parent
    %                         window as its member
    %       AODChildWindows: Array of opened child windows of the parent
    %                        window.
    % Methods: 31
    %       All functions which involve the parent window are defined in
    %       the member functions of this class.
    properties
        AODParentHandles
        AODChildWindows
    end
    methods
        % Constructor function
        function parentWindow = AODParentWindow()
            parentWindow.AODParentHandles = struct();
            parentWindow.AODParentHandles.FontSize = 10.5;
            parentWindow.AODParentHandles.FontName = 'FixedWidth';
            parentWindow.AODParentHandles.nMainTab = 3;
            parentWindow.AODParentHandles.FigureHandle = figure( ...
                'Tag', 'parentWindowdow', ...
                'Units', 'normalized', ...
                'Position', [0 0.06 1 0.80], ...
                'Name', 'parentWindowdow', ...
                'MenuBar', 'none', ...
                'NumberTitle', 'off', ...
                'Color', get(0,'DefaultUicontrolBackgroundColor'), ...
                'Resize', 'on', ...
                'Visible', 'off');
            parentWindow = resetParentParameters(parentWindow);
            parentWindow.InitializePanels;
            %----------------- Initialize Panel Components -------------------
            parentWindow.InitializeOpenedWindowsPanel;
            parentWindow.InitializeWelcomePanel;
            parentWindow.InitializeSystemConfigurationPanel;
            parentWindow.InitializeSurfaceEditorPanel;
            % ---------------- MENU and TOOLBAR ITEMS -------------------------
            parentWindow.InitializeMenuAndToolbarItems;
            % Click Welcome tab programatically
            ind = 1;
            parentWindow.selectMainTab(ind);
            % Make the window visible
            set(parentWindow.AODParentHandles.FigureHandle,...
                'Visible', 'on')%,...
            %'CloseRequestFcn',{@parentWindow.closeParent});
        end
    end
end