Description of getCurrentOpticalSystem
getCurrentOpticalSystem
PURPOSE
getCurrentOpticalSystem: Constructs an optical system object from the AOD
SYNOPSIS
function [ SavedOpticalSystem,saved] = getCurrentOpticalSystem (parentWindow)
DESCRIPTION
 getCurrentOpticalSystem: Constructs an optical system object from the AOD
 Main Window
 Member of AODParentWindow class
CROSS-REFERENCE INFORMATION
This function calls:
extractObjectFromAODObjectCatalogue EXTRACTCOATINGFROMCOATINGCATALOGUE extracts a AOD object from the catalogue
Coating
Glass
OpticalSystem
This function is called by:
SOURCE CODE
function [ SavedOpticalSystem,saved] = getCurrentOpticalSystem (parentWindow)
% getCurrentOpticalSystem: Constructs an optical system object from the AOD
% Main Window
% Member of AODParentWindow class
aodHandles = parentWindow.AODParentHandles;
button='Yes';
if ~ parentWindow.validateOpticalSystem
     button = questdlg('Invalid input detected. Do you want to continue saving?',...
         'Invalid Input');
end
if strcmpi(button,'Yes')
    saved = aodHandles.Saved;
    pathName = aodHandles.PathName;
    fileName = aodHandles.FileName;
    %System Configuration
    %aperture
    tempSystemApertureType=get(aodHandles.popApertureType,'Value');
    tempSystemApertureValue=str2double(get(aodHandles.txtApertureValue,'String'));
    %general
    tempLensName=get(aodHandles.txtLensName,'String');
    tempLensNote=get(aodHandles.txtLensNote,'String');
    tempLensUnit=get(aodHandles.popLensUnit,'Value');
    tempWavelengthUnit=get(aodHandles.popWavelengthUnit,'Value');
    %wavelength
    nWavelength = str2double(get(aodHandles.txtTotalWavelengthsSelected,'String'));
    tempPrimaryWavelengthIndex = get(aodHandles.popPrimaryWavlenIndex,'Value');
    tempPredefinedWavlens      = get(aodHandles.popPredefinedWavlens,'Value');
    tblData = get(aodHandles.tblWavelengths,'data');
    tempWavelengthMatrix = reshape([tblData{:,:}],length([tblData{:,:}])/3,3);
    % Remove the 1st col (Selected Chekbox) and last row (just empty row)
    if tempWavelengthMatrix(end,1)== 0 % checks condn
       tempWavelengthMatrix = tempWavelengthMatrix(1:end-1,2:end);
    end
    %fields
    nFieldPoint = str2double(get(aodHandles.txtTotalFieldPointsSelected,'String'));
    tempAngle = get(aodHandles.radioAngle,'Value');
    tempObjectHeight = get(aodHandles.radioObjectHeight,'Value');
    tempImageHeight = get(aodHandles.radioImageHeight,'Value');
    if tempAngle
        tempFieldType = 'Angle';
    elseif tempObjectHeight
        tempFieldType = 'ObjectHeight';
    elseif tempImageHeight
        % Currently Imageheight is not supported so take as object heigth.
       tempFieldType = 'ObjectHeight';
    end
    tempFieldNormalizationList = cellstr (get(aodHandles.popFieldNormalization,'String'));
    tempFieldNormalization = (tempFieldNormalizationList{get(aodHandles.popFieldNormalization,'Value')});
    tblData2 = get(aodHandles.tblFieldPoints,'data');
    tempFieldPointMatrix = reshape([tblData2{:,:}],length([tblData2{:,:}])/4,4);
    % Remove the 1st col (Selected Chekbox) and last row (just empty row)
    if tempFieldPointMatrix(end,1)==0 % checks condn
       tempFieldPointMatrix = tempFieldPointMatrix(1:end-1,2:end);
    end
 % Coating Catalogue
 tableData1 = get(aodHandles.tblCoatingCatalogues,'data');
 if ~isempty(tableData1)
     % Take only the selected ones
     selectedRows1 = find(cell2mat(tableData1(:,1)));
     if ~isempty(selectedRows1)
         tempCoatingCataloguesList = tableData1(selectedRows1,3);
     else
         tempCoatingCataloguesList = [];
     end
 else
     tempCoatingCataloguesList = [];
 end
 % Glass Catalogue
 tableData2 = get(aodHandles.tblGlassCatalogues,'data');
 if ~isempty(tableData2)
     % Take only the selected ones
     selectedRows2 = find(cell2mat(tableData2(:,1)));
     if ~isempty(selectedRows2)
         tempGlassCataloguesList = tableData2(selectedRows2,3);
     else
         tempGlassCataloguesList = [];
     end
 else
     tempGlassCataloguesList = [];
 end
 % Pupil Apodization
 tempApodizationTypeList = cellstr (get(aodHandles.popApodizationType,'String'));
 tempApodizationType = (tempApodizationTypeList{get(aodHandles.popApodizationType,'Value')});
 tempApodizationParameters = struct();
 switch lower(tempApodizationType)
     case lower('None')
         tempApodizationParameters = '';
     case lower('Super Gaussian')
         tempApodizationParameters.MaximumIntensity = str2double(get(aodHandles.txtApodMaximumIntensity,'String'));
         tempApodizationParameters.Order = str2double(get(aodHandles.txtApodOrder,'String'));
         tempApodizationParameters.BeamRadius = str2double(get(aodHandles.txtApodBeamRadius,'String'));
 end
    %Surface Data
    tempStandardData = get(aodHandles.tblStandardData,'data');
    tempAsphericData= get(aodHandles.tblAsphericData,'data');
    tempApertureData= get(aodHandles.tblApertureData,'data');
    tempTiltDecenterData= get(aodHandles.tblTiltDecenterData,'data');
    sizeTblData = size(tempStandardData);
    nSurface = sizeTblData(1);
    % New optical system
    NewOpticalSystem = OpticalSystem;
    NewOpticalSystem.Saved = saved;
    NewOpticalSystem.PathName = pathName;
    NewOpticalSystem.FileName = fileName;
    %Set optical systems properties
    NewOpticalSystem.NumberOfSurfaces = nSurface;
    %set aperture
    NewOpticalSystem.SystemApertureType=tempSystemApertureType;
    NewOpticalSystem.SystemApertureValue=tempSystemApertureValue;
    %set general
    NewOpticalSystem.LensName=tempLensName;
    NewOpticalSystem.LensNote=tempLensNote;
    NewOpticalSystem.WavelengthUnit=tempWavelengthUnit;
    NewOpticalSystem.LensUnit=tempLensUnit;
    NewOpticalSystem.ObjectAfocal = 0;
    NewOpticalSystem.ImageAfocal = 0;
    NewOpticalSystem.ObjectTelecenteric = 0;
    NewOpticalSystem.ObjectTelecenteric = 0;
    %set wavelength
    NewOpticalSystem.NumberOfWavelengths=nWavelength;
    NewOpticalSystem.WavelengthMatrix=tempWavelengthMatrix;
    NewOpticalSystem.PrimaryWavelengthIndex=tempPrimaryWavelengthIndex;
    %set field
    % NewOpticalSystem.FieldType = tempAngle*1+tempObjectHeight*2+tempImageHeight*3; %1 angle, 2 obj height, 3 image height
    NewOpticalSystem.FieldType = tempFieldType;
    NewOpticalSystem.NumberOfFieldPoints = nFieldPoint;
    NewOpticalSystem.FieldPointMatrix = tempFieldPointMatrix;
    NewOpticalSystem.CoatingCataloguesList = tempCoatingCataloguesList;
    NewOpticalSystem.GlassCataloguesList = tempGlassCataloguesList;
    NewOpticalSystem.ApodizationType = tempApodizationType;
    NewOpticalSystem.ApodizationParameters = tempApodizationParameters;
    NewOpticalSystem.FieldNormalization = tempFieldNormalization;
    %create empty surface array
    Surface.empty(nSurface,0);
    %Set optical system surfaces.
    % Assume global ref is 1st surface of the lens
    NewOpticalSystem.SurfaceArray(1).DecenterParameter = [0 0];
    NewOpticalSystem.SurfaceArray(1).TiltParameter = [0 0 0];
    %NewOpticalSystem.SurfaceArray(1).Position = [0,0,0];
    objLocation = -1*str2double(char(tempStandardData(1,7)));
    if abs(objLocation) > 10^10 % Infinite object distance replaced with 0
        objLocation = 0;
    end
    for k = 1:1:nSurface
        %standard data
        surface = tempStandardData(k,1);
        if isequaln(char(surface),'OBJECT')
            NewOpticalSystem.SurfaceArray(k).ObjectSurface = 1;
        elseif isequaln(char(surface),'IMAGE')
            NewOpticalSystem.SurfaceArray(k).ImageSurface = 1;
        elseif isequaln(char(surface),'STOP')
            NewOpticalSystem.SurfaceArray(k).Stop = 1;
            NewOpticalSystem.StopIndex = k;
        else
            NewOpticalSystem.SurfaceArray(k).Stop = 0;
            NewOpticalSystem.SurfaceArray(k).ImageSurface = 0;
            NewOpticalSystem.SurfaceArray(k).ObjectSurface = 0;
        end
        NewOpticalSystem.SurfaceArray(k).Comment       = char(tempStandardData(k,2));%text
        NewOpticalSystem.SurfaceArray(k).Type          = char(tempStandardData(k,3));%text
        NewOpticalSystem.SurfaceArray(k).Radius        = str2double(char(tempStandardData(k,5)));
        NewOpticalSystem.SurfaceArray(k).Thickness     = str2double(char(tempStandardData(k,7)));
        % get glass name and then SellmeierCoefficients from file
        glassName = strtrim(char(tempStandardData(k,9)));% text
        if ~isempty(glassName)
            % check for its existance and extract the glass among selected catalogues
            objectType = 'glass';
            objectName = glassName;
            if isnan(str2double(glassName)) % If the glass name is specified
                % Glass Catalogue
                tableData1 = get(aodHandles.tblGlassCatalogues,'data');
                if ~isempty(tableData1)
                    % Take only the selected ones
                    selectedRows1 = find(cell2mat(tableData1(:,1)));
                    if ~isempty(selectedRows1)
                        glassCatalogueListFullNames = tableData1(selectedRows1,3);
                    else
                        glassCatalogueListFullNames = '';
                    end
                else
                    glassCatalogueListFullNames = '';
                end
                objectCatalogueListFullNames = glassCatalogueListFullNames;
                objectIndex = 0;
                for pp = 1:size(objectCatalogueListFullNames,1)
                    objectCatalogueFullName = objectCatalogueListFullNames{pp};
                    [ aodObject,objectIndex ] = extractObjectFromAODObjectCatalogue...
                        (objectType,objectName,objectCatalogueFullName );
                    if objectIndex ~= 0
                        break;
                    end
                end
                if  objectIndex ~= 0
                    NewOpticalSystem.SurfaceArray(k).Glass = aodObject;
                else
                    disp(['Error: The glass after surface ',num2str(k),' is not found so it is ignored.']);
                    NewOpticalSystem.SurfaceArray(k).Glass = Glass;
                end
            else
                aodObject = Glass(glassName);
                NewOpticalSystem.SurfaceArray(k).Glass = aodObject;
            end
        else
            NewOpticalSystem.SurfaceArray(k).Glass = Glass;
        end
        NewOpticalSystem.SurfaceArray(k).DeviationMode = (char(tempStandardData(k,11)));
        NewOpticalSystem.SurfaceArray(k).SemiDiameter  = str2double(char(tempStandardData(k,13)));
        % aperture data
        NewOpticalSystem.SurfaceArray(k).ApertureType      = char(tempApertureData(k,3));
        NewOpticalSystem.SurfaceArray(k).ApertureParameter = ...
            [str2double(char(tempApertureData(k,5))),str2double(char(tempApertureData(k,7))),...
            str2double(char(tempApertureData(k,9))),str2double(char(tempApertureData(k,11)))];
        % coating data
        coatName = (char(tempStandardData(k,15)));
        if ~isempty(coatName)
            % check for its existance and extract the coating among selected catalogues
            objectType = 'coating';
            objectName = coatName;
            % Coating Catalogue
            tableData1 = get(aodHandles.tblCoatingCatalogues,'data');
            if ~isempty(tableData1)
                % Take only the selected ones
                selectedRows1 = find(cell2mat(tableData1(:,1)));
                if ~isempty(selectedRows1)
                    coatingCatalogueListFullNames = tableData1(selectedRows1,3);
                else
                    coatingCatalogueListFullNames = '';
                end
            else
                coatingCatalogueListFullNames = '';
            end
            objectCatalogueListFullNames = coatingCatalogueListFullNames;
            objectIndex = 0;
            for pp = 1:size(objectCatalogueListFullNames,1)
                objectCatalogueFullName = objectCatalogueListFullNames{pp};
                [ aodObject,objectIndex ] = extractObjectFromAODObjectCatalogue...
                    (objectType,objectName,objectCatalogueFullName );
                if objectIndex ~= 0
                    break;
                end
            end
            if  objectIndex ~= 0
                NewOpticalSystem.SurfaceArray(k).Coating = aodObject;
            else
                disp(['Error: The coating of surface ',num2str(k),' is not found so it is ignored.']);
                NewOpticalSystem.SurfaceArray(k).Coating = Coating;
            end
        else
            NewOpticalSystem.SurfaceArray(k).Coating = Coating;
        end
        % aspheric data
        NewOpticalSystem.SurfaceArray(k).ConicConstant          = str2double(char(tempAsphericData(k,3)));
        NewOpticalSystem.SurfaceArray(k).PloynomialCoefficients = ...
            [str2double(char(tempAsphericData(k,5))),str2double(char(tempAsphericData(k,7))),str2double(char(tempAsphericData(k,9))),...
            str2double(char(tempAsphericData(k,11))),str2double(char(tempAsphericData(k,13))),str2double(char(tempAsphericData(k,15))),...
            str2double(char(tempAsphericData(k,17))),str2double(char(tempAsphericData(k,19))),str2double(char(tempAsphericData(k,21))),...
            str2double(char(tempAsphericData(k,23))),str2double(char(tempAsphericData(k,25))),str2double(char(tempAsphericData(k,27)))];
        % tilt decenter data
        NewOpticalSystem.SurfaceArray(k).TiltDecenterOrder = char(tempTiltDecenterData(k,3));
        NewOpticalSystem.SurfaceArray(k).DecenterParameter = ...
            [str2double(char(tempTiltDecenterData(k,5))),str2double(char(tempTiltDecenterData(k,7)))];
        NewOpticalSystem.SurfaceArray(k).TiltParameter     = ...
            [str2double(char(tempTiltDecenterData(k,9))),str2double(char(tempTiltDecenterData(k,11))),str2double(char(tempTiltDecenterData(k,13)))];
        NewOpticalSystem.SurfaceArray(k).TiltMode          = char(tempTiltDecenterData(k,15));
        % compute position from decenter and thickness
        if k==1 % Object surface
            objThickness = abs(NewOpticalSystem.SurfaceArray(k).Thickness);
            if objThickness > 10^10 % Replace Inf with INF_OBJ_Z = 0 for graphing
                objThickness = 0;
            end
            % since global coord but shifted by objThickness
            refCoordinateTM = [1,0,0,0;0,1,0,0;0,0,1,-objThickness;0,0,0,1];
            surfaceCoordinateTM = refCoordinateTM;
            referenceCoordinateTM = refCoordinateTM;
            % set surface property
            NewOpticalSystem.SurfaceArray(k).SurfaceCoordinateTM = ...
                surfaceCoordinateTM;
            NewOpticalSystem.SurfaceArray(k).ReferenceCoordinateTM = ...
                referenceCoordinateTM;
       else
            prevRefCoordinateTM = referenceCoordinateTM;
            prevSurfCoordinateTM = surfaceCoordinateTM;
            prevThickness = NewOpticalSystem.SurfaceArray(k-1).Thickness;
            if prevThickness > 10^10 % Replace Inf with INF_OBJ_Z = 0 for object distance
                prevThickness = 0;
            end
            [surfaceCoordinateTM,referenceCoordinateTM] = NewOpticalSystem. ...
                    SurfaceArray(k).TiltAndDecenter(prevRefCoordinateTM,...
                    prevSurfCoordinateTM,prevThickness);
            % set surface property
            NewOpticalSystem.SurfaceArray(k).SurfaceCoordinateTM = surfaceCoordinateTM;
            NewOpticalSystem.SurfaceArray(k).ReferenceCoordinateTM = referenceCoordinateTM;
        end
        NewOpticalSystem.SurfaceArray(k).Position = (surfaceCoordinateTM (1:3,4))';
    end
    SavedOpticalSystem = NewOpticalSystem;
    saved = 1;
else
    SavedOpticalSystem = [];
    saved = 0;
end
end