Description of InitializeMenuAndToolbarItems
InitializeMenuAndToolbarItems
PURPOSE
Defines all menu items and toolbar commands and all callbacks related
SYNOPSIS
function InitializeMenuAndToolbarItems(parentWindow)
DESCRIPTION
 Defines all menu items and toolbar commands and all callbacks related
 with the menu commands.
 Member of AODParentWindow class
CROSS-REFERENCE INFORMATION
This function calls:
addObjectToAODObjectCatalogue addObjectToAODObjectCatalogue: Adds the given AOD object to the given
createNewAODObjectCatalogue CREATENEWCOATINGCATALOGUE Create anew AOD object catalogue and intialize
AODChildWindow
Glass
coatingDataInputDialog COATINGDATAINPUTDIALOG Defines a dilog box which is used to input coating
aboutWindow About Window
glassDataInputDialog GLASSDATAINPUTDIALOG Defines a dilog box which is used to input glass
This function is called by:
SUBFUNCTIONS
function menuTry_Callback(~,~,myParent)
function menuFile_Callback(~,~,myParent)
function menuEdit_Callback(~,~,myParent)
function menuOptimization_Callback(~,~,myParent)
function menuRayTrace_Callback(~,~,myParent)
function menuDiffraction_Callback(~,~,myParent)
function menuWavefrontAtExitPupil_Callback(~,~,myParent)
function menuPupilApodization_Callback(~,~,myParent)
function menuFFTPSF_Callback(~,~,myParent)
function menuHelp_Callback(~,~,myParent)
function menuView_Callback(~,~,myParent)
function menuScalarRayTrace_Callback(~,~,myParent)
function menuSurfaceProperties_Callback(~,~,myParent)
function menuSystemConfiguration_Callback(~,~,myParent)
function menuNew_Callback(~,~,myParent)
function menuOpen_Callback(~,~,myParent)
function menuSave_Callback(~,~,myParent)
function menuSavaAs_Callback(~,~,myParent)
function menuClose_Callback(~,~,myParent)
function menu2DSystemLayout_Callback(~,~,myParent)
function menu3DSystemLayout_Callback(~,~,myParent)
function menuUserManual_Callback(~,~,myParent)
function menuAbout_Callback(~,~,myParent)
function menuImportGlassCatalogue_Callback(~,~,myParent)
function menuCoatingCatalogue_Callback(~,~,myParent)
function menuImportZMXFile_Callback(~,~,myParent)
function menuPolarizationRayTrace_Callback(~,~,myParent)
function menuCoatingAnalysis_Callback(~,~,myParent)
function menuRefractiveIndexProfile_Callback(~,~,myParent)
function menuTransmissionVsAngle_Callback(~,~,myParent)
function menuReflectionVsAngle_Callback(~,~,myParent)
function menuDiattenuationVsAngle_Callback(~,~,myParent)
function menuRetardanceVsAngle_Callback(~,~,myParent)
function menuTransmissionVsWavelength_Callback(~,~,myParent)
function menuReflectionVsWavelength_Callback(~,~,myParent)
function menuDiattenuationVsWavelength_Callback(~,~,myParent)
function menRetardanceVsWavelength_Callback(~,~,myParent)
function menuOpticalSystem_Callback(~,~,myParent)
function menuFootprintDiagram_Callback(~,~,myParent)
function menuPolarizationEllipseMap_Callback(~,~,myParent)
function menuParaxialAnalysis_Callback(~,~,myParent)
function menuTransverseRayAberration_Callback(~,~,myParent)
function menuPolarizationAbberation_Callback(~,~,myParent)
function menuAmplitudeTransmissionMap_Callback(~,~,myParent)
function menuPhaseMap_Callback(~,~,myParent)
function menuWavefrontDiattenuationMap_Callback(~,~,myParent)
function menuWavefrontRetardanceMap_Callback(~,~,myParent)
function menuCoating_Callback(~,~,myParent)
function menuGlassDataEditor_Callback(~,~,myParent)
function menuCoatingDataEditor_Callback(~,~,myParent)
function menuImportOpticalSystem_Callback(~,~,myParent)
function menuExportOpticalSystem_Callback(~,~,myParent)
function menuNewCoatingCatalogue_Callback(~,~,myParent)
function fullFileName = addNewCoatingCatalogue(myParent)
function menuCoatingCatalogueAnalysis_Callback(~,~,myParent)
function menuImportCoatingCatalogue_Callback(~,~,myParent)
function menuExportCoatingCatalogue_Callback(~,~,myParent)
function menuGlass_Callback(~,~,myParent)
function menuProgramminReference_Callback(~,~,myParent)
function menuNewGlass_Callback(~,~,myParent)
function menuGlassAnalysis_Callback(~,~,myParent)
function menuGlassCatalogue_Callback(~,~,myParent)
function menuNewGlassCatalogue_Callback(~,~,myParent)
function fullFileName = addNewGlassCatalogue(myParent)
function menuExportGlassCatalogue_Callback(~,~,myParent)
function menuGlassCatalogueAnalysis_Callback(~,~,myParent)
function menuDispersionGraph_Callback(~,~,~)
function menuOpticalSystemAnalysis_Callback(~,~,~)
function menuImageAtBfp_Callback(~,~,~,myParent)
function btnInsertSurface_ClickedCallback(~,~,myParent)
function btnRemoveSurface_ClickedCallback(~,~,myParent)
function RemoveThisSurface(aodHandles)
function InsertNewSurface(aodHandles)
SOURCE CODE
function InitializeMenuAndToolbarItems(parentWindow)
% Defines all menu items and toolbar commands and all callbacks related
% with the menu commands.
% Member of AODParentWindow class
aodHandles = parentWindow.AODParentHandles;
%   fontSize = str2double(get(aodHandles.fontSize,'String'));
    fontSize = aodHandles.FontSize;
    nMainTab = aodHandles.nMainTab;
    aodHandles.menuTry = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuTry', ...
        'Label', 'Try', ...
        'Checked', 'off', ...
        'visible', 'off', ...
        'Callback', {@menuTry_Callback,parentWindow});
    function menuTry_Callback(~,~,myParent)
        aodHandles = myParent.AODParentHandles;
        disp('try clicked');
    end
    %% Menu Items
    aodHandles.menuFile = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuFile', ...
        'Label', 'File', ...
        'Checked', 'off', ...
        'Callback', {@menuFile_Callback,parentWindow});
    aodHandles.menuNew = uimenu( ...
        'Parent', aodHandles.menuFile, ...
        'Tag', 'menuNew', ...
        'Label', 'New...', ...
        'Checked', 'off', ...
        'Callback', {@menuNew_Callback,parentWindow});
    aodHandles.menuOpen = uimenu( ...
        'Parent', aodHandles.menuFile, ...
        'Tag', 'menuOpen', ...
        'Label', 'Open', ...
        'Checked', 'off', ...
        'Callback', {@menuOpen_Callback,parentWindow});
    aodHandles.menuSave = uimenu( ...
        'Parent', aodHandles.menuFile, ...
        'Tag', 'menuSave', ...
        'Label', 'Save', ...
        'Checked', 'off', ...
        'Callback', {@menuSave_Callback,parentWindow});
    aodHandles.menuSavaAs = uimenu( ...
        'Parent', aodHandles.menuFile, ...
        'Tag', 'menuSavaAs', ...
        'Label', 'Save As...', ...
        'Checked', 'off', ...
        'Callback', {@menuSavaAs_Callback,parentWindow});
    aodHandles.menuClose = uimenu( ...
        'Parent', aodHandles.menuFile, ...
        'Tag', 'menuClose', ...
        'Label', 'Close', ...
        'Checked', 'off', ...
        'Callback', {@menuClose_Callback,parentWindow});
    aodHandles.menuEdit = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuEdit', ...
        'Label', 'Edit', ...
        'Checked', 'off', ...
        'Callback', {@menuEdit_Callback,parentWindow});
    aodHandles.menuSurfaceProperties = uimenu( ...
        'Parent', aodHandles.menuEdit, ...
        'Tag', 'menuSurfaceProperties', ...
        'Label', 'Surface Properties', ...
        'Checked', 'off', ...
        'Callback', {@menuSurfaceProperties_Callback,parentWindow});
    aodHandles.menuSystemConfiguration = uimenu( ...
        'Parent', aodHandles.menuEdit, ...
        'Tag', 'menuSystemConfiguration', ...
        'Label', 'System Configuration', ...
        'Checked', 'off', ...
        'Callback', {@menuSystemConfiguration_Callback,parentWindow});
    aodHandles.menuView = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuView', ...
        'Label', 'View', ...
        'Checked', 'off', ...
        'Callback', {@menuView_Callback,parentWindow});
    aodHandles.menu2DSystemLayout = uimenu( ...
        'Parent', aodHandles.menuView, ...
        'Tag', 'menu2DSystemLayout', ...
        'Label', '2D System Layout', ...
        'Checked', 'off', ...
        'Callback', {@menu2DSystemLayout_Callback,parentWindow});
    aodHandles.menu3DSystemLayout = uimenu( ...
        'Parent', aodHandles.menuView, ...
        'Tag', 'menu3DSystemLayout', ...
        'Label', '3D System Layout', ...
        'Checked', 'off', ...
        'Callback', {@menu3DSystemLayout_Callback,parentWindow});
    %---------------------------------------------------------------------
    % Ray Trace menu
    aodHandles.menuRayTrace = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuRayTrace', ...
        'Label', 'Ray Trace', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuRayTrace_Callback,parentWindow});
    aodHandles.menuScalarRayTrace = uimenu( ...
        'Parent', aodHandles.menuRayTrace, ...
        'Tag', 'menuScalarRayTrace', ...
        'Label', 'Scalar Ray Trace', ...
        'Checked', 'off', ...
        'Callback', {@menuScalarRayTrace_Callback,parentWindow});
    aodHandles.menuPolarizationRayTrace = uimenu( ...
        'Parent', aodHandles.menuRayTrace, ...
        'Tag', 'menuPolarizationRayTrace', ...
        'Label', 'Polarization Ray Trace', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuPolarizationRayTrace_Callback,parentWindow});
    %---------------------------------------------------------------------
    % Diffraction Analysis
    aodHandles.menuDiffraction = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuDiffraction', ...
        'Label', 'Diffraction', ...
        'Checked', 'off', ...
        'Callback', {@menuDiffraction_Callback,parentWindow});
    aodHandles.menuWavefrontAtExitPupil = uimenu( ...
        'Parent', aodHandles.menuDiffraction, ...
        'Tag', 'menuWavefrontAtExitPupil', ...
        'Label', 'Wavefront At Exit Pupil', ...
        'Checked', 'off', ...
        'Callback', {@menuWavefrontAtExitPupil_Callback,parentWindow});
    aodHandles.menuPupilApodization = uimenu( ...
        'Parent', aodHandles.menuDiffraction, ...
        'Tag', 'menuPupilApodization', ...
        'Label', 'Pupil Apodization', ...
        'Checked', 'off', ...
        'Callback', {@menuPupilApodization_Callback,parentWindow});
    aodHandles.menuFFTPSF = uimenu( ...
        'Parent', aodHandles.menuDiffraction, ...
        'Tag', 'menuFFTPSF', ...
        'Label', 'FFT PSF', ...
        'Checked', 'off', ...
        'Callback', {@menuFFTPSF_Callback,parentWindow});
    %---------------------------------------------------------------------
    aodHandles.menuOptimization = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuOptimization', ...
        'Label', 'Optimization', ...
        'Checked', 'off', ...
        'visible', 'off', ...
        'Callback', {@menuOptimization_Callback,parentWindow});
    aodHandles.menuImageAtBfp = uimenu( ...
        'Parent', aodHandles.menuOptimization, ...
        'Tag', 'menuImageAtBfp', ...
        'Label', 'Image @ BFP', ...
        'Checked', 'off', ...
        'Callback', {@menuImageAtBfp_Callback,parentWindow});
    aodHandles.menuOpticalSystem = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuOpticalSystem', ...
        'Label', 'Optical System', ...
        'Checked', 'off', ...
        'Callback', {@menuOpticalSystem_Callback,parentWindow});
    aodHandles.menuImportOpticalSystem = uimenu( ...
        'Parent', aodHandles.menuOpticalSystem, ...
        'Tag', 'menuImportOpticalSystem', ...
        'Label', 'Import Optical System', ...
        'Checked', 'off', ...
        'visible', 'off', ...
        'Callback', {@menuImportOpticalSystem_Callback,parentWindow});
    aodHandles.menuImportZMXFile = uimenu( ...
        'Parent', aodHandles.menuImportOpticalSystem, ...
        'Tag', 'menuImportZMXFile', ...
        'Label', 'From ZMX File', ...
        'Checked', 'off', ...
        'Callback', {@menuImportZMXFile_Callback,parentWindow});
    aodHandles.menuExportOpticalSystem = uimenu( ...
        'Parent', aodHandles.menuOpticalSystem, ...
        'Tag', 'menuExportOpticalSystem', ...
        'Visible', 'off', ...
        'Label', 'Export Optical System', ...
        'Checked', 'off', ...
        'Callback', {@menuExportOpticalSystem_Callback,parentWindow});
    aodHandles.menuOpticalSystemAnalysis = uimenu( ...
        'Parent', aodHandles.menuOpticalSystem, ...
        'Tag', 'menuOpticalSystemAnalysis', ...
        'Label', 'Optical System Analysis', ...
        'Checked', 'off', ...
        'Callback', {@menuOpticalSystemAnalysis_Callback,parentWindow});
    aodHandles.menuFootprintDiagram = uimenu( ...
        'Parent', aodHandles.menuOpticalSystemAnalysis, ...
        'Tag', 'menuFootprintDiagram', ...
        'Label', 'Footprint Diagram', ...
        'Checked', 'off', ...
        'Callback', {@menuFootprintDiagram_Callback,parentWindow});
    aodHandles.menuPolarizationEllipseMap = uimenu( ...
        'Parent', aodHandles.menuOpticalSystemAnalysis, ...
        'Tag', 'menuPolarizationEllipseMap', ...
        'Label', 'Polarization Ellipse Map', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuPolarizationEllipseMap_Callback,parentWindow});
    aodHandles.menuParaxialAnalysis = uimenu( ...
        'Parent', aodHandles.menuOpticalSystemAnalysis, ...
        'Tag', 'menuParaxialAnalysis', ...
        'Label', 'Paraxial Analysis', ...
        'Checked', 'off', ...
        'Callback', {@menuParaxialAnalysis_Callback,parentWindow});
    aodHandles.menuTransverseRayAberration = uimenu( ...
        'Parent', aodHandles.menuOpticalSystemAnalysis, ...
        'Tag', 'menuTransverseRayAberration', ...
        'Label', 'Transverse Ray Aberration', ...
        'Checked', 'off', ...
        'Callback', {@menuTransverseRayAberration_Callback,parentWindow});
    aodHandles.menuPolarizationAbberation = uimenu( ...
        'Parent', aodHandles.menuOpticalSystemAnalysis, ...
        'Tag', 'menuPolarizationAbberation', ...
        'Label', 'Polarization Abberation', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuPolarizationAbberation_Callback,parentWindow});
    aodHandles.menuAmplitudeTransmissionMap = uimenu( ...
        'Parent', aodHandles.menuPolarizationAbberation, ...
        'Tag', 'menuAmplitudeTransmissionMap', ...
        'Label', 'Amplitude Transmission Map', ...
        'Checked', 'off', ...
        'Callback', {@menuAmplitudeTransmissionMap_Callback,parentWindow});
    aodHandles.menuPhaseMap = uimenu( ...
        'Parent', aodHandles.menuPolarizationAbberation, ...
        'Tag', 'menuPhaseMap', ...
        'Label', 'Phase Map', ...
        'Checked', 'off', ...
        'Callback', {@menuPhaseMap_Callback,parentWindow});
    aodHandles.menuWavefrontDiattenuationMap = uimenu( ...
        'Parent', aodHandles.menuPolarizationAbberation, ...
        'Tag', 'menuWavefrontDiattenuationMap', ...
        'Label', 'Wavefront Diattenuation Map', ...
        'Checked', 'off', ...
        'Callback', {@menuWavefrontDiattenuationMap_Callback,parentWindow});
    aodHandles.menuWavefrontRetardanceMap = uimenu( ...
        'Parent', aodHandles.menuPolarizationAbberation, ...
        'Tag', 'menuWavefrontRetardanceMap', ...
        'Label', 'Wavefront Retardance Map', ...
        'Checked', 'off', ...
        'Callback', {@menuWavefrontRetardanceMap_Callback,parentWindow});
    aodHandles.menuCoating = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuCoating', ...
        'Label', 'Coating', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuCoating_Callback,parentWindow});
    aodHandles.menuCoatingDataEditor = uimenu( ...
        'Parent', aodHandles.menuCoating, ...
        'Tag', 'menuNewCoating', ...
        'Visible', 'on', ...
        'Label', 'Coating Data Editor', ...
        'Checked', 'off', ...
        'Callback', {@menuCoatingDataEditor_Callback,parentWindow});
    aodHandles.menuCoatingAnalysis = uimenu( ...
        'Parent', aodHandles.menuCoating, ...
        'Tag', 'menuCoatingAnalysis', ...
        'Label', 'CoatingAnalysis', ...
        'Checked', 'off', ...
        'Callback', {@menuCoatingAnalysis_Callback,parentWindow});
    aodHandles.menuRefractiveIndexProfile = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuRefractiveIndexProfile', ...
        'Label', 'Refractive Index Profile', ...
        'Checked', 'off', ...
        'Callback', {@menuRefractiveIndexProfile_Callback,parentWindow});
    aodHandles.menuTransmissionVsAngle = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuTransmissionVsAngle', ...
        'Label', 'Transmission Vs Angle', ...
        'Checked', 'off', ...
        'Callback', {@menuTransmissionVsAngle_Callback,parentWindow});
    aodHandles.menuReflectionVsAngle = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuReflectionVsAngle', ...
        'Label', 'Reflection Vs Angle', ...
        'Checked', 'off', ...
        'Callback', {@menuReflectionVsAngle_Callback,parentWindow});
    aodHandles.menuDiattenuationVsAngle = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuDiattenuationVsAngle', ...
        'Label', 'Diattenuation Vs Angle', ...
        'Checked', 'off', ...
        'Callback', {@menuDiattenuationVsAngle_Callback,parentWindow});
    aodHandles.menuRetardanceVsAngle = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuRetardanceVsAngle', ...
        'Label', 'Retardance Vs Angle', ...
        'Checked', 'off', ...
        'Callback', {@menuRetardanceVsAngle_Callback,parentWindow});
    aodHandles.menuTransmissionVsWavelength = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuTransmissionVsWavelength', ...
        'Label', 'Transmission Vs Wavelength', ...
        'Checked', 'off', ...
        'Callback', {@menuTransmissionVsWavelength_Callback,parentWindow});
    aodHandles.menuReflectionVsWavelength = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuReflectionVsWavelength', ...
        'Label', 'Reflection Vs Wavelength', ...
        'Checked', 'off', ...
        'Callback', {@menuReflectionVsWavelength_Callback,parentWindow});
    aodHandles.menuDiattenuationVsWavelength = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menuDiattenuationVsWavelength', ...
        'Label', 'Diattenuation Vs Wavelength', ...
        'Checked', 'off', ...
        'Callback', {@menuDiattenuationVsWavelength_Callback,parentWindow});
    aodHandles.menRetardanceVsWavelength = uimenu( ...
        'Parent', aodHandles.menuCoatingAnalysis, ...
        'Tag', 'menRetardanceVsWavelength', ...
        'Label', 'Retardance Vs Wavelength', ...
        'Checked', 'off', ...
        'Callback', {@menRetardanceVsWavelength_Callback,parentWindow});
    aodHandles.menuCoatingCatalogue = uimenu( ...
        'Parent', aodHandles.menuCoating, ...
        'Tag', 'menuCoatingCatalogue', ...
        'Visible', 'on', ...
        'Label', 'Coating Catalogue', ...
        'Checked', 'off', ...
        'Callback', {@menuCoatingCatalogue_Callback,parentWindow});
    aodHandles.menuNewCoatingCatalogue = uimenu( ...
        'Parent', aodHandles.menuCoatingCatalogue, ...
        'Tag', 'menuNewCoatingCatalogue', ...
        'Visible', 'on', ...
        'Label', 'New Coating Catalogue', ...
        'Checked', 'off', ...
        'Callback', {@menuNewCoatingCatalogue_Callback,parentWindow});
    aodHandles.menuCoatingCatalogueAnalysis = uimenu( ...
        'Parent', aodHandles.menuCoatingCatalogue, ...
        'Tag', 'menuCoatingCatalogueAnalysis', ...
        'Visible', 'off', ...
        'Label', 'Coating Catalogue Analysis', ...
        'Checked', 'off', ...
        'Callback', {@menuCoatingCatalogueAnalysis_Callback,parentWindow});
    aodHandles.menuImportCoatingCatalogue = uimenu( ...
        'Parent', aodHandles.menuCoatingCatalogue, ...
        'Tag', 'menuImportCoatingCatalogue', ...
        'Visible', 'off', ...
        'Label', 'Import Coating Catalogue', ...
        'Checked', 'off', ...
        'Callback', {@menuImportCoatingCatalogue_Callback,parentWindow});
    aodHandles.menuExportCoatingCatalogue = uimenu( ...
        'Parent', aodHandles.menuCoatingCatalogue, ...
        'Tag', 'menuExportCoatingCatalogue', ...
        'Visible', 'off', ...
        'Label', 'Export Coating Catalogue', ...
        'Checked', 'off', ...
        'Callback', {@menuExportCoatingCatalogue_Callback,parentWindow});
    aodHandles.menuGlass = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuGlass', ...
        'Label', 'Glass', ...
        'Checked', 'off', ...
        'visible', 'on', ...
        'Callback', {@menuGlass_Callback,parentWindow});
    aodHandles.menuGlassDataEditor = uimenu( ...
        'Parent', aodHandles.menuGlass, ...
        'Tag', 'menuGlassDataEditor', ...
        'Label', 'Glass Data Editor', ...
        'Checked', 'off', ...
        'Callback', {@menuGlassDataEditor_Callback,parentWindow});
    aodHandles.menuGlassAnalysis = uimenu( ...
        'Parent', aodHandles.menuGlass, ...
        'Tag', 'menuGlassAnalysis', ...
        'Visible', 'off', ...
        'Label', 'Glass Analysis', ...
        'Checked', 'off', ...
        'Callback', {@menuGlassAnalysis_Callback,parentWindow});
    aodHandles.menuDispersionGraph = uimenu( ...
        'Parent', aodHandles.menuGlassAnalysis, ...
        'Tag', 'menuDispersionGraph', ...
        'Visible', 'off', ...
        'Label', 'Dispersion Graph', ...
        'Checked', 'off', ...
        'Callback', {@menuDispersionGraph_Callback,parentWindow});
    aodHandles.menuGlassCatalogue = uimenu( ...
        'Parent', aodHandles.menuGlass, ...
        'Tag', 'menuGlassCatalogue', ...
        'Label', 'Glass Catalogue', ...
        'Visible','on',...
        'Checked', 'off', ...
        'Callback', {@menuGlassCatalogue_Callback,parentWindow});
    aodHandles.menuNewGlassCatalogue = uimenu( ...
        'Parent', aodHandles.menuGlassCatalogue, ...
        'Tag', 'menuNewGlassCatalogue', ...
        'Visible', 'on', ...
        'Label', 'New Glass Catalogue', ...
        'Checked', 'off', ...
        'Callback', {@menuNewGlassCatalogue_Callback,parentWindow});
    aodHandles.menuImportGlassCatalogue = uimenu( ...
        'Parent', aodHandles.menuGlassCatalogue, ...
        'Tag', 'menuImportGlassCatalogue', ...
        'Label', 'Import Glass Catalogue', ...
        'Checked', 'off', ...
        'Visible', 'on', ...
        'Callback', {@menuImportGlassCatalogue_Callback,parentWindow});
    aodHandles.menuExportGlassCatalogue = uimenu( ...
        'Parent', aodHandles.menuGlassCatalogue, ...
        'Tag', 'menuExportGlassCatalogue', ...
        'Visible', 'off', ...
        'Label', 'Export Glass Catalogue', ...
        'Checked', 'off', ...
        'Callback', {@menuExportGlassCatalogue_Callback,parentWindow});
    aodHandles.menuGlassCatalogueAnalysis = uimenu( ...
        'Parent', aodHandles.menuGlassCatalogue, ...
        'Tag', 'menuGlassCatalogueAnalysis', ...
        'Visible', 'off', ...
        'Label', 'Glass Catalogue Analysis', ...
        'Checked', 'off', ...
        'Callback', {@menuGlassCatalogueAnalysis_Callback,parentWindow});
    aodHandles.menuHelp = uimenu( ...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'menuHelp', ...
        'Label', 'Help', ...
        'Checked', 'off', ...
        'Callback', {@menuHelp_Callback,parentWindow});
    aodHandles.menuAbout = uimenu( ...
        'Parent', aodHandles.menuHelp, ...
        'Tag', 'menuAbout', ...
        'Label', 'About', ...
        'Checked', 'off', ...
        'Callback', {@menuAbout_Callback,parentWindow});
    aodHandles.menuUserManual = uimenu( ...
        'Parent', aodHandles.menuHelp, ...
        'Tag', 'menuUserManual', ...
        'Label', 'User Manual', ...
        'Checked', 'off', ...
        'Callback', {@menuUserManual_Callback,parentWindow});
    aodHandles.menuProgramminReference = uimenu( ...
        'Parent', aodHandles.menuHelp, ...
        'Tag', 'menuProgramminReference', ...
        'Label', 'Programmin Reference', ...
        'Checked', 'off', ...
        'Callback', {@menuProgramminReference_Callback,parentWindow});
    %% Toolbar Icon
    aodHandles.toolBarHandle = uitoolbar(...
        'Parent', aodHandles.FigureHandle, ...
        'Tag', 'toolBar');
    % Toolbar Icon Images
    toolbarIcon = rand(19,19,3)*0;
    plusIcon = toolbarIcon;
    plusIcon(5:16,8:11,:) = 1;
    plusIcon(9:12,4:15,:) = 1;
    minusIcon = toolbarIcon;
    minusIcon(9:12,4:15,:) = 1;
    aodHandles.btnInsertSurface = uipushtool(...
        aodHandles.toolBarHandle,...
        'CData',plusIcon,...
        'TooltipString','Insert Surface',...
        'ClickedCallback',{@btnInsertSurface_ClickedCallback,parentWindow});
    aodHandles.btnRemoveSurface = uipushtool(...
        aodHandles.toolBarHandle,...
        'CData',minusIcon,...
        'TooltipString','Remove Surface',...
        'ClickedCallback',{@btnRemoveSurface_ClickedCallback,parentWindow});
  end
    %% Menu Item Callbacks
    % ---------------------------------------------------------------------
    function menuFile_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuEdit_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuOptimization_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuRayTrace_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuDiffraction_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuWavefrontAtExitPupil_Callback(~,~,myParent)
        AODChildWindow('wavefrontAtExitPupil',myParent);
    end
    % ---------------------------------------------------------------------
    function menuPupilApodization_Callback(~,~,myParent)
        AODChildWindow('pupilApodization',myParent);
    end
    % ---------------------------------------------------------------------
    function menuFFTPSF_Callback(~,~,myParent)
        AODChildWindow('FFTPSF',myParent);
    end
    % ---------------------------------------------------------------------
    function menuHelp_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuView_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuScalarRayTrace_Callback(~,~,myParent)
        AODChildWindow('scalarRayTrace',myParent);
    end
    % ---------------------------------------------------------------------
    function menuSurfaceProperties_Callback(~,~,myParent)
       aodHandles = myParent.AODParentHandles;
        % Make SystemConfiguration tab visible and all others invisible
%         nMainTab = str2double(get(aodHandles.nMainTab,'String'));
        nMainTab = aodHandles.nMainTab;
        for k = 1:nMainTab
            set(get(aodHandles.panelMainTab(k),'Children'),'Visible', 'off');
            set(aodHandles.btnMainTab(k),'BackgroundColor',[200,200,200]./256);
        end
        set(get(aodHandles.panelMainTab(2),'Children'),'Visible', 'on');
        set(aodHandles.btnMainTab(2),'BackgroundColor',[240,240,240]./256);
    end
    % ---------------------------------------------------------------------
    function menuSystemConfiguration_Callback(~,~,myParent)
    aodHandles = myParent.AODParentHandles;
        % Make SystemConfiguration tab visible and all others invisible
%         nMainTab = str2double(get(aodHandles.nMainTab,'String'));
        nMainTab = aodHandles.nMainTab;
        for k = 1:nMainTab
            set(get(aodHandles.panelMainTab(k),'Children'),'Visible', 'off');
            set(aodHandles.btnMainTab(k),'BackgroundColor',[200,200,200]./256);
        end
        set(get(aodHandles.panelMainTab(3),'Children'),'Visible', 'on');
        set(aodHandles.btnMainTab(3),'BackgroundColor',[240,240,240]./256);
    end
    % ---------------------------------------------------------------------
    function menuNew_Callback(~,~,myParent)
        myParent.openNewOpticalSystem;
    end
    % ---------------------------------------------------------------------
    function menuOpen_Callback(~,~,myParent)
    [FileName,PathName] = uigetfile('*.mat','Select Optical System file');
    if (FileName~=0) % FileName=0 when no file is selected
        fullFileName = [PathName '\' FileName];
        myParent.openFromMATFile(fullFileName);
    else
        return
    end
%         openSavedOpticalSystem(fullFileName);
%         OPTICAL_SYSTEM.Saved = true;
%         OPTICAL_SYSTEM.PathName = PathName;
%         OPTICAL_SYSTEM.FileName = FileName;
    end
    % ---------------------------------------------------------------------
    function menuSave_Callback(~,~,myParent)
        myParent.saveMySystem;
    end
    % ---------------------------------------------------------------------
    function menuSavaAs_Callback(~,~,myParent)
        myParent.saveMySystemAs;
    end
    % ---------------------------------------------------------------------
    function menuClose_Callback(~,~,myParent)
        myParent.closeAllWindows();
    end
    % ---------------------------------------------------------------------
    function menu2DSystemLayout_Callback(~,~,myParent)
        AODChildWindow('system2DLayoutDiagram',myParent);
    end
    % ---------------------------------------------------------------------
    function menu3DSystemLayout_Callback(~,~,myParent)
        AODChildWindow('system3DLayoutDiagram',myParent);
    end
    % ---------------------------------------------------------------------
    function menuUserManual_Callback(~,~,myParent)
        web(which('UserManualVersion10.html'))
    end
    % ---------------------------------------------------------------------
    function menuAbout_Callback(~,~,myParent)
        aodHandles = myParent.AODParentHandles;
        fontSize = aodHandles.FontSize;
        fontName = aodHandles.FontName;
        aboutWindow(fontName);
    end
    % ---------------------------------------------------------------------
    function menuImportGlassCatalogue_Callback(~,~,myParent)
        %Read from excel sheet downloaded from Schott website
        [FileName,PathName] = uigetfile('*.xls','Select Glasss Catalogue File');
        if (FileName~=0) % FileName=0 when no file is selected
            % 'G:\MSc Photonics 2st Semster Docs\OOP version of Basic Ray Tracer\...
            % Ray Tracer Toolbox 2.1 (OOP Version)\DatabaseFiles\...
            % schott_optical_glass_catalogue_excel_april_2013.xls';
            fullFileName = [PathName,'\',FileName];
            [~,~,alldata]  = xlsread(fullFileName,'A5:L200');
            tableSize = size(alldata);
            glassCatalogueFullFileName = addNewGlassCatalogue(myParent);
            %add each glass to the catalogue
            for kk = 1:tableSize(1)
                name = cell2mat(alldata(kk,1));
                if isnan(name)
                    break;
                end
                glassName = num2str(name);
                glassType = 'Sellmeier1';
                glassParameters = ...
                    [cell2mat(alldata(kk,7)),cell2mat(alldata(kk,8)),...
                    cell2mat(alldata(kk,9)),cell2mat(alldata(kk,10)),...
                    cell2mat(alldata(kk,11)),cell2mat(alldata(kk,12))]';
                newGlass = Glass(glassName,glassType,glassParameters);
                addObjectToAODObjectCatalogue...
               ('glass', newGlass,glassCatalogueFullFileName,'replace' );
            end
        else
            return;
        end
    end
        % ---------------------------------------------------------------------
    function menuCoatingCatalogue_Callback(~,~,myParent)
    end
        % ---------------------------------------------------------------------
    function menuImportZMXFile_Callback(~,~,myParent)
        [FileName,PathName] = uigetfile('*.zmx','Select Zemax file');
        if (FileName~=0) % FileName=0 when no file is selected
            zmxFullFileName = [PathName,'\',FileName];
            myParent.openFromZemaxFile(zmxFullFileName)
        else
            return
        end
    end
        % ---------------------------------------------------------------------
    function menuPolarizationRayTrace_Callback(~,~,myParent)
        AODChildWindow('polarizationRayTrace',myParent);
    end
        % ---------------------------------------------------------------------
    function menuCoatingAnalysis_Callback(~,~,myParent)
    end
        % ---------------------------------------------------------------------
    function menuRefractiveIndexProfile_Callback(~,~,myParent)
        AODChildWindow('coatingRefractiveIndexProfile',myParent);
    end
        % ---------------------------------------------------------------------
    function menuTransmissionVsAngle_Callback(~,~,myParent)
        AODChildWindow('coatingTransmissionVsAngle',myParent);
    end
        % ---------------------------------------------------------------------
    function menuReflectionVsAngle_Callback(~,~,myParent)
        AODChildWindow('coatingReflectionVsAngle',myParent);
    end
        % ---------------------------------------------------------------------
    function menuDiattenuationVsAngle_Callback(~,~,myParent)
        AODChildWindow('coatingDiattenuationVsAngle',myParent);
    end
        % ---------------------------------------------------------------------
    function menuRetardanceVsAngle_Callback(~,~,myParent)
        AODChildWindow('coatingRetardanceVsAngle',myParent);
    end
        % ---------------------------------------------------------------------
    function menuTransmissionVsWavelength_Callback(~,~,myParent)
        AODChildWindow('coatingTransmissionVsWavelength',myParent);
    end
        % ---------------------------------------------------------------------
    function menuReflectionVsWavelength_Callback(~,~,myParent)
        AODChildWindow('coatingReflectionVsWavelength',myParent);
    end
        % ---------------------------------------------------------------------
    function menuDiattenuationVsWavelength_Callback(~,~,myParent)
        AODChildWindow('coatingDiattenuationVsWavelength',myParent);
    end
        % ---------------------------------------------------------------------
    function menRetardanceVsWavelength_Callback(~,~,myParent)
        AODChildWindow('coatingRetardanceVsWavelength',myParent);
    end
        % ---------------------------------------------------------------------
    function menuOpticalSystem_Callback(~,~,myParent)
    end
        % ---------------------------------------------------------------------
    function menuFootprintDiagram_Callback(~,~,myParent)
        AODChildWindow('FootprintDiagram',myParent);
    end
        % ---------------------------------------------------------------------
    function menuPolarizationEllipseMap_Callback(~,~,myParent)
        AODChildWindow('polarizationEllipseMap',myParent);
    end
        % ---------------------------------------------------------------------
    function menuParaxialAnalysis_Callback(~,~,myParent)
        AODChildWindow('paraxialAnalysis',myParent);
    end
         % ---------------------------------------------------------------------
    function menuTransverseRayAberration_Callback(~,~,myParent)
        AODChildWindow('transverseRayAberration',myParent);
    end
        % ---------------------------------------------------------------------
    function menuPolarizationAbberation_Callback(~,~,myParent)
    end
        % ---------------------------------------------------------------------
    function menuAmplitudeTransmissionMap_Callback(~,~,myParent)
        AODChildWindow('amplitudeTransmissionMap',myParent);
    end
        % ---------------------------------------------------------------------
    function menuPhaseMap_Callback(~,~,myParent)
        AODChildWindow('phaseMap',myParent);
    end
        % ---------------------------------------------------------------------
    function menuWavefrontDiattenuationMap_Callback(~,~,myParent)
    AODChildWindow('wavefrontDiattenuationMap',myParent);
    end
        % ---------------------------------------------------------------------
    function menuWavefrontRetardanceMap_Callback(~,~,myParent)
        AODChildWindow('wavefrontRetardanceMap',myParent);
    end
        % ---------------------------------------------------------------------
    function menuCoating_Callback(~,~,myParent)
    end
  function menuGlassDataEditor_Callback(~,~,myParent)
  [ currentOpticalSystem,saved] = ...
                myParent.getCurrentOpticalSystem;
   aodHandles = myParent.AODParentHandles;
    % Glass Catalogue
    tableData1 = get(aodHandles.tblGlassCatalogues,'data');
    if ~isempty(tableData1)
        % Take only the selected ones
        selectedRows1 = find(cell2mat(tableData1(:,1)));
        if ~isempty(selectedRows1)
            glassCatalogueListFullNames = tableData1(selectedRows1,3);
        else
            glassCatalogueListFullNames = '';
        end
    else
        glassCatalogueListFullNames = '';
    end
    fontSize = aodHandles.FontSize;
    fontName = aodHandles.FontName;
    glassDataInputDialog(glassCatalogueListFullNames,fontName,fontSize);
  end
    % ---------------------------------------------------------------------
    function menuCoatingDataEditor_Callback(~,~,myParent)
    [ currentOpticalSystem,saved] = ...
                myParent.getCurrentOpticalSystem;
    aodHandles = myParent.AODParentHandles;
    % Coating Catalogue
    tableData1 = get(aodHandles.tblCoatingCatalogues,'data');
    if ~isempty(tableData1)
        % Take only the selected ones
        selectedRows1 = find(cell2mat(tableData1(:,1)));
        if ~isempty(selectedRows1)
            coatingCatalogueListFullNames = tableData1(selectedRows1,3);
        else
            coatingCatalogueListFullNames = '';
        end
    else
        coatingCatalogueListFullNames = '';
    end
    fontSize = aodHandles.FontSize;
    fontName = aodHandles.FontName;
    coatingDataInputDialog(coatingCatalogueListFullNames,fontName,fontSize);
    end
        % ---------------------------------------------------------------------
    function menuImportOpticalSystem_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuExportOpticalSystem_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuNewCoatingCatalogue_Callback(~,~,myParent)
        addNewCoatingCatalogue(myParent);
    end
    function fullFileName = addNewCoatingCatalogue(myParent)
        newCatlogueName = char(cellstr(inputdlg('Enter New Catalogue Name','New Catalogue Name',1,{'CoatingCat01'})));
        objectType = 'Coating';
        objectCatalogueFullName = [pwd,'\Catalogue_Files\',newCatlogueName,'.mat'];
        ask_replace = 'ask';
        [ fullFileName ] = createNewAODObjectCatalogue(objectType, objectCatalogueFullName,ask_replace );
        % Add a row with the new coating catalogue
        aodHandles = myParent.AODParentHandles;
        tblData1 = get(aodHandles.tblCoatingCatalogues,'data');
        newRow1 =  {[true],[newCatlogueName],[fullFileName]};
        newTable1 = [tblData1; newRow1];
        set(aodHandles.tblCoatingCatalogues, 'Data', newTable1);
        set(aodHandles.txtTotalCoatingCataloguesSelected, 'String',...
        str2double(get(aodHandles.txtTotalCoatingCataloguesSelected, 'String'))+1);
    end
    % ---------------------------------------------------------------------
    function menuCoatingCatalogueAnalysis_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuImportCoatingCatalogue_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuExportCoatingCatalogue_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuGlass_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuProgramminReference_Callback(~,~,myParent)
        web(which('index.html'))
    end
    % ---------------------------------------------------------------------
    function menuNewGlass_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuGlassAnalysis_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuGlassCatalogue_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuNewGlassCatalogue_Callback(~,~,myParent)
        addNewGlassCatalogue(myParent)
    end
   function fullFileName = addNewGlassCatalogue(myParent)
        newCatlogueName = char(cellstr(inputdlg('Enter New Catalogue Name','New Catalogue Name',1,{'GlassCat01'})));
        objectType = 'Glass';
        objectCatalogueFullName = [pwd,'\Catalogue_Files\',newCatlogueName,'.mat'];
        ask_replace = 'ask';
        [ fullFileName ] = createNewAODObjectCatalogue(objectType, objectCatalogueFullName,ask_replace );
        % Add a row with the new glass catalogue
        aodHandles = myParent.AODParentHandles;
        tblData1 = get(aodHandles.tblGlassCatalogues,'data');
        newRow1 =  {[true],[newCatlogueName],[fullFileName]};
        newTable1 = [tblData1; newRow1];
        set(aodHandles.tblGlassCatalogues, 'Data', newTable1);
        set(aodHandles.txtTotalGlassCataloguesSelected, 'String',...
        str2double(get(aodHandles.txtTotalGlassCataloguesSelected, 'String'))+1);
end
    % ---------------------------------------------------------------------
    function menuExportGlassCatalogue_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuGlassCatalogueAnalysis_Callback(~,~,myParent)
    end
    % ---------------------------------------------------------------------
    function menuDispersionGraph_Callback(~,~,~)
    end
    % ---------------------------------------------------------------------
    function menuOpticalSystemAnalysis_Callback(~,~,~)
    end
    % ---------------------------------------------------------------------
    function menuImageAtBfp_Callback(~,~,~,myParent)
        aodHandles = myParent.AODParentHandles;
        % determine the back focal length of the optical system
        SavedOpticalSystem = myParent.getCurrentOpticalSystem;
        bfl = SavedOpticalSystem.getBackFocalLength;
        % set the last thickness = bfl
        tblData1 = get(aodHandles.tblStandardData,'data');
        imgSurfIndex = SavedOpticalSystem.NumberOfSurface;
        tblData1{imgSurfIndex-1,7} = num2str(bfl);
        set(aodHandles.tblStandardData, 'Data', tblData1);
    end
    %% Toolbar Callbacks
    function btnInsertSurface_ClickedCallback(~,~,myParent)
        aodHandles = myParent.AODParentHandles;
        InsertNewSurface(aodHandles);
    end
    function btnRemoveSurface_ClickedCallback(~,~,myParent)
        aodHandles = myParent.AODParentHandles;
        RemoveThisSurface(aodHandles);
    end
    %% Local Function
    function RemoveThisSurface(aodHandles)
        global SELECTED_CELL
1000         global CAN_REMOVE
1001         if isempty(SELECTED_CELL)
1002             return
1003         end
1004
1005         if CAN_REMOVE
1006             removePosition = SELECTED_CELL(1);
1007
1008             %update standard data table
1009             tblData1 = get(aodHandles.tblStandardData,'data');
1010             sizeTblData1 = size(tblData1);
1011             parta1 = tblData1(1:removePosition-1,:);
1012             partb1 = tblData1(removePosition+1:sizeTblData1 ,:);
1013             newTable1 = [parta1; partb1];
1014             sysTable1 = aodHandles.tblStandardData;
1015             set(sysTable1, 'Data', newTable1);
1016
1017              %update aperture table
1018             tblData3 = get(aodHandles.tblApertureData,'data');
1019             sizeTblData3 = size(tblData3);
1020             parta3 = tblData3(1:removePosition-1,:);
1021             partb3 = tblData3(removePosition+1:sizeTblData3 ,:);
1022             newTable3 = [parta3; partb3];
1023             sysTable3 = aodHandles.tblApertureData;
1024             set(sysTable3, 'Data', newTable3);
1025
1026             %update Aspheric table
1027             tblData4 = get(aodHandles.tblAsphericData,'data');
1028             sizeTblData4 = size(tblData4);
1029             parta4 = tblData4(1:removePosition-1,:);
1030             partb4 = tblData4(removePosition+1:sizeTblData4 ,:);
1031             newTable4 = [parta4; partb4];
1032             sysTable4 = aodHandles.tblAsphericData;
1033             set(sysTable4, 'Data', newTable4);
1034
1035              %update tilt decenter table
1036             tblData5 = get(aodHandles.tblTiltDecenterData,'data');
1037             sizeTblData5 = size(tblData5);
1038             parta5 = tblData5(1:removePosition-1,:);
1039             partb5 = tblData5(removePosition+1:sizeTblData5 ,:);
1040             newTable5 = [parta5; partb5];
1041             sysTable5 = aodHandles.tblTiltDecenterData;
1042             set(sysTable5, 'Data', newTable5);
1043         end
1044     end
1045
1046
1047     function InsertNewSurface(aodHandles)
1048         global SELECTED_CELL
1049         global CAN_ADD
1050         if isempty(SELECTED_CELL)
1051             return
1052         end
1053         if CAN_ADD
1054             insertPosition = SELECTED_CELL(1);
1055             %update standard data table
1056             tblData1 = get(aodHandles.tblStandardData,'data');
1057             sizeTblData1 = size(tblData1);
1058             parta1 = tblData1(1:insertPosition-1,:);
1059             newRow1 =  {'Surf','','Plane','','Inf','','0','','','','+1 Refractive','','0','','',''};
1060             partb1 = tblData1(insertPosition:sizeTblData1 ,:);
1061             newTable1 = [parta1; newRow1; partb1];
1062             sysTable1 = aodHandles.tblStandardData;
1063             set(sysTable1, 'Data', newTable1);
1064
1065              %update aperture table
1066             tblData3 = get(aodHandles.tblApertureData,'data');
1067             sizeTblData3 = size(tblData3);
1068             parta3 = tblData3(1:insertPosition-1,:);
1069             newRow3 =  {'Surf','Plane','Floating','','0','','0','','0','','0',''};
1070             partb3 = tblData3(insertPosition:sizeTblData3 ,:);
1071             newTable3 = [parta3; newRow3; partb3];
1072             sysTable3 = aodHandles.tblApertureData;
1073             set(sysTable3, 'Data', newTable3);
1074
1075             %update Aspheric table
1076             tblData4 = get(aodHandles.tblAsphericData,'data');
1077             sizeTblData4 = size(tblData4);
1078             parta4 = tblData4(1:insertPosition-1,:);
1079             newRow4 =  {'Surf','Plane','0','','0','','0','','0','','0','','0','','0','','0','','0','','0','','0','','0','','0',''};
1080             partb4 = tblData4(insertPosition:sizeTblData4 ,:);
1081             newTable4 = [parta4; newRow4; partb4];
1082             sysTable4 = aodHandles.tblAsphericData;
1083             set(sysTable4, 'Data', newTable4);
1084
1085              %update tilt decenter table
1086             tblData5 = get(aodHandles.tblTiltDecenterData,'data');
1087             sizeTblData5 = size(tblData5);
1088             parta5 = tblData5(1:insertPosition-1,:);
1089             newRow5 =  {'Surf','Plane','DxDyDzTxTyTz','','0','','0','','0','','0','','0','','DAR',''};
1090             partb5 = tblData5(insertPosition:sizeTblData5 ,:);
1091             newTable5 = [parta5; newRow5; partb5];
1092             sysTable5 = aodHandles.tblTiltDecenterData;
1093             set(sysTable5, 'Data', newTable5);
1094
1095             % If possible add here a code to select the first cell of newly added row
1096             % automatically
1097         end
1098     end
1099