Description of InitializeSurfaceEditorPanel
InitializeSurfaceEditorPanel
PURPOSE
InitializeSurfaceEditorPanel: Define and initialized the uicontrols of the
SYNOPSIS
function InitializeSurfaceEditorPanel(parentWindow)
DESCRIPTION
 InitializeSurfaceEditorPanel: Define and initialized the uicontrols of the
 Surface Editor Panel
 Member of AODParentWindow class
CROSS-REFERENCE INFORMATION
This function calls:
extractObjectFromAODObjectCatalogue EXTRACTCOATINGFROMCOATINGCATALOGUE extracts a AOD object from the catalogue
resetSurfaceEditorPanel resetSurfaceEditorPanel: reset all surface editor tables
coatingDataInputDialog COATINGDATAINPUTDIALOG Defines a dilog box which is used to input coating
glassDataInputDialog GLASSDATAINPUTDIALOG Defines a dilog box which is used to input glass
isValidGeneralInput validInput: Validates user input to the toolbox depending on the type
This function is called by:
SUBFUNCTIONS
function tblStandardData_CellEditCallback(~, eventdata,aodHandles)
function tblAsphericData_CellEditCallback(~, eventdata,aodHandles)
function tblApertureData_CellEditCallback(~, ~,~)
function tblTiltDecenterData_CellEditCallback(~, eventdata,aodHandles)
function tblStandardData_CellSelectionCallback(~, eventdata,aodHandles)
function tblAsphericData_CellSelectionCallback(~, ~,~)
function tblApertureData_CellSelectionCallback(~, ~,~)
function tblTiltDecenterData_CellSelectionCallback(~, ~,~)
SOURCE CODE
function InitializeSurfaceEditorPanel(parentWindow)
% InitializeSurfaceEditorPanel: Define and initialized the uicontrols of the
% Surface Editor Panel
% Member of AODParentWindow class
aodHandles = parentWindow.AODParentHandles;
    fontSize = aodHandles.FontSize;
    fontName = aodHandles.FontName;
    nMainTab = aodHandles.nMainTab;
    aodHandles.surfEditorTabGroup = uitabgroup(...
        'Parent', aodHandles.panelMainTab(2), ...
        'Units', 'Normalized', ...
        'Position', [0, 0, 1.0, 1.0]);
    aodHandles.surfStandardDataTab = ...
        uitab(aodHandles.surfEditorTabGroup, 'title','Standard Data');
    aodHandles.surfApertureDataTab = ...
        uitab(aodHandles.surfEditorTabGroup, 'title','Aperture Data');
    aodHandles.surfAsphericDataTab = ...
        uitab(aodHandles.surfEditorTabGroup, 'title','Aspheric Data');
    aodHandles.surfTiltDecenterDataTab = ...
        uitab(aodHandles.surfEditorTabGroup, 'title','Tilt Decenter Data');
    % Initialize the panel and table for standard data
    aodHandles.tblStandardData = uitable('Parent',aodHandles.surfStandardDataTab,...
        'FontSize',fontSize,'FontName', fontName,'units','normalized','Position',[0 0 1 1]);
    % Initialize the panel and table for aperture data
    aodHandles.tblApertureData = ...
        uitable('Parent',aodHandles.surfApertureDataTab,'FontSize',fontSize,'FontName', fontName,...
                  'units','normalized','Position',[0 0 1 1]);
    % Initialize the panel and table for aspheric data
    aodHandles.tblAsphericData = ...
        uitable('Parent',aodHandles.surfAsphericDataTab,'FontSize',fontSize,'FontName', fontName,...
                  'units','normalized','Position',[0 0 1 1]);
    % Initialize the panel and table for tilt decenter data
    aodHandles.tblTiltDecenterData = ...
        uitable('Parent',aodHandles.surfTiltDecenterDataTab,'FontSize',fontSize,'FontName', fontName,...
                  'units','normalized','Position',[0 0 1 1]);
    % Give all tables initial data
    parentWindow.AODParentHandles = aodHandles;
    parentWindow = resetSurfaceEditorPanel(parentWindow);
    aodHandles = parentWindow.AODParentHandles;
    % Set all celledit and cellselection callbacks
    set(aodHandles.tblStandardData,...
        'CellEditCallback',{@tblStandardData_CellEditCallback,aodHandles},...
        'CellSelectionCallback',{@tblStandardData_CellSelectionCallback,aodHandles});
    set(aodHandles.tblApertureData,...
        'CellEditCallback',{@tblApertureData_CellEditCallback,aodHandles},...
        'CellSelectionCallback',{@tblApertureData_CellSelectionCallback,aodHandles});
    set(aodHandles.tblAsphericData,...
        'CellEditCallback',{@tblAsphericData_CellEditCallback,aodHandles},...
        'CellSelectionCallback',{@tblAsphericData_CellSelectionCallback,aodHandles});
    set(aodHandles.tblTiltDecenterData,...
        'CellEditCallback',{@tblTiltDecenterData_CellEditCallback,aodHandles},...
        'CellSelectionCallback',{@tblTiltDecenterData_CellSelectionCallback,aodHandles});
    parentWindow.AODParentHandles = aodHandles;
end
%% Callback Function Definitions
% CellEditCallback
% --- Executes when entered data in editable cell(s) in aodHandles.tblStandardData.
function tblStandardData_CellEditCallback(~, eventdata,aodHandles)
% hObject    handle to aodHandles.tblStandardData (see GCBO)
% eventdata  structure with the following fields (see UITABLE)
%    Indices: row and column indices of the cell(s) edited
%    PreviousData: previous data for the cell(s) edited
%    EditData: string(s) entered by the user
%    NewData: EditData or its converted form set on the Data property. Empty if Data was not changed
%    Error: error string when failed to convert EditData to appropriate value for Data
% aodHandles    structure with aodHandles and user data (see GUIDATA)
if eventdata.Indices(2) == 1    %if surface tag  is changed update all tables in the editor
    if (strcmpi(eventdata.PreviousData,'OBJECT'))||(strcmpi(eventdata.PreviousData,'IMAGE'))||(strcmpi(eventdata.PreviousData,'STOP'))
         tblData1 = get(aodHandles.tblStandardData,'data');
         tblData1{eventdata.Indices(1),1} = eventdata.PreviousData;
         set(aodHandles.tblStandardData, 'Data', tblData1);
    elseif (strcmpi(eventdata.NewData,'STOP')) ||(strcmpi(eventdata.NewData,'STO'))||(strcmpi(eventdata.NewData,'ST'))||(strcmpi(eventdata.NewData,'S'))
         tblData1 = get(aodHandles.tblStandardData,'data');
         tblData2 = get(aodHandles.tblApertureData,'data');
         tblData4 = get(aodHandles.tblAsphericData,'data');
         tblData5 = get(aodHandles.tblTiltDecenterData,'data');
         kk = 2;
         while ~strcmpi(tblData1{kk,1},'Image')
             if kk == eventdata.Indices(1)
                 surfTag = 'STOP';
             else
                 surfTag = 'Surf';
             end
             tblData1{kk,1} = surfTag;
             set(aodHandles.tblStandardData, 'Data', tblData1);
             tblData2{kk,1} = surfTag;
             set(aodHandles.tblApertureData, 'Data', tblData2);
             tblData4{kk,1} = surfTag;
             set(aodHandles.tblAsphericData, 'Data', tblData4);
             tblData5{kk,1} = surfTag;
             set(aodHandles.tblTiltDecenterData, 'Data', tblData5);
             kk = kk+1;
         end
    else
         tblData1 = get(aodHandles.tblStandardData,'data');
         tblData1{eventdata.Indices(1),1} = eventdata.PreviousData;
         set(aodHandles.tblStandardData, 'Data', tblData1);
    end
    columnEditable1 =  [false true true false true false true false true ...
        false true false true false true false];
    sysTable1 = aodHandles.tblStandardData;
    set(sysTable1,'ColumnEditable', columnEditable1);
elseif eventdata.Indices(2) == 3 && ~(strcmpi(eventdata.NewData,''))   %if surface type is changed update all tables in the editor
     if strcmpi(strtrim(eventdata.NewData),'Plane')
         tblData1 = get(aodHandles.tblStandardData,'data');
         tblData1{eventdata.Indices(1),5} = 'Inf';
         set(aodHandles.tblStandardData, 'Data', tblData1);
     end
     tblData2 = get(aodHandles.tblApertureData,'data');
     tblData2{eventdata.Indices(1),eventdata.Indices(2)-1} = eventdata.NewData;
     set(aodHandles.tblApertureData, 'Data', tblData2);
     tblData4 = get(aodHandles.tblAsphericData,'data');
     tblData4{eventdata.Indices(1),eventdata.Indices(2)-1} = eventdata.NewData;
     set(aodHandles.tblAsphericData, 'Data', tblData4);
     tblData5 = get(aodHandles.tblTiltDecenterData,'data');
     tblData5{eventdata.Indices(1),eventdata.Indices(2)-1} = eventdata.NewData;
     set(aodHandles.tblTiltDecenterData, 'Data', tblData5);
 elseif eventdata.Indices(2) == 5 % if radius field changes
     if isempty(str2num(eventdata.NewData))||any(imag(str2num(eventdata.NewData)))%if the radius field is not a number
         tblData1 = get(aodHandles.tblStandardData,'data');
         tblData1{eventdata.Indices(1),5} = 'Inf';
         tblData1{eventdata.Indices(1),3} = 'Plane';
         set(aodHandles.tblStandardData, 'Data', tblData1);
         %update other tables
         tblData2 = get(aodHandles.tblApertureData,'data');
         tblData2{eventdata.Indices(1),2} = 'Plane';
         set(aodHandles.tblApertureData, 'Data', tblData2);
         tblData4 = get(aodHandles.tblAsphericData,'data');
         tblData4{eventdata.Indices(1),2} = 'Plane';
         set(aodHandles.tblAsphericData, 'Data', tblData4);
         tblData5 = get(aodHandles.tblTiltDecenterData,'data');
         tblData5{eventdata.Indices(1),2} = 'Plane';
         set(aodHandles.tblTiltDecenterData, 'Data', tblData5);
     elseif strcmpi(strtrim(eventdata.NewData),'inf') % if radius is infinity
         tblData1 = get(aodHandles.tblStandardData,'data');
         tblData1{eventdata.Indices(1),3} = 'Plane';
         set(aodHandles.tblStandardData, 'Data', tblData1);
         %update other tables
         tblData2 = get(aodHandles.tblApertureData,'data');
         tblData2{eventdata.Indices(1),2} = 'Plane';
         set(aodHandles.tblApertureData, 'Data', tblData2);
         tblData4 = get(aodHandles.tblAsphericData,'data');
         tblData4{eventdata.Indices(1),2} = 'Plane';
         set(aodHandles.tblAsphericData, 'Data', tblData4);
         tblData5 = get(aodHandles.tblTiltDecenterData,'data');
         tblData5{eventdata.Indices(1),2} = 'Plane';
         set(aodHandles.tblTiltDecenterData, 'Data', tblData5);
     else
         tblData1 = get(aodHandles.tblStandardData,'data');
         if strcmpi(strtrim(tblData1{eventdata.Indices(1),3}),'Plane')
             tblData1{eventdata.Indices(1),3} = 'Spherical';
             set(aodHandles.tblStandardData, 'Data', tblData1);
         %update other tables
         tblData2 = get(aodHandles.tblApertureData,'data');
         tblData2{eventdata.Indices(1),2} = 'Spherical';
         set(aodHandles.tblApertureData, 'Data', tblData2);
         tblData4 = get(aodHandles.tblAsphericData,'data');
         tblData4{eventdata.Indices(1),2} = 'Spherical';
         set(aodHandles.tblAsphericData, 'Data', tblData4);
         tblData5 = get(aodHandles.tblTiltDecenterData,'data');
         tblData5{eventdata.Indices(1),2} = 'Spherical';
         set(aodHandles.tblTiltDecenterData, 'Data', tblData5);
         end
     end
elseif eventdata.Indices(1) == 1 && eventdata.Indices(2) == 7 % if first thickness is changed
    if isValidGeneralInput() % This returns 1 by default, but in the future
        % input validation code shall be defined
    else
         button = questdlg('Invalid input detected. Do you want to restore previous valid object thickness value?','Restore Object Thickness');
         if strcmpi(button,'Yes')
             tblData1 = get(aodHandles.tblStandardData,'data');
             tblData1{eventdata.Indices(1),7} = eventdata.PreviousData;
             set(aodHandles.tblStandardData, 'Data', tblData1);
         end
    end
elseif eventdata.Indices(2) == 9 % if glass is changed
    glassName = eventdata.NewData;
    % Check if the glass name is just the refractive index of the glass
    if ~isnan(str2double(glassName))
        tblData = get(aodHandles.tblStandardData,'data');
        tblData{eventdata.Indices(1),9} = num2str(str2double(glassName),'%.4f ');
        set(aodHandles.tblStandardData, 'Data', tblData);
        return;
    end
    % check for its existance among selected catalogues
    if ~isempty(glassName)
        objectType = 'glass';
        objectName = glassName;
        % Glass Catalogue
        tableData1 = get(aodHandles.tblGlassCatalogues,'data');
        if ~isempty(tableData1)
            % Take only the selected ones
            selectedRows1 = find(cell2mat(tableData1(:,1)));
            if ~isempty(selectedRows1)
                glassCatalogueListFullNames = tableData1(selectedRows1,3);
            else
                glassCatalogueListFullNames = '';
            end
        else
            glassCatalogueListFullNames = '';
        end
        objectCatalogueListFullNames = glassCatalogueListFullNames;
        objectIndex = 0;
        for kk = 1:size(objectCatalogueListFullNames,1)
            objectCatalogueFullName = objectCatalogueListFullNames{kk};
            [ aodObject,objectIndex ] = extractObjectFromAODObjectCatalogue...
                (objectType,objectName,objectCatalogueFullName );
            if objectIndex ~= 0
                break;
            end
        end
        % if exists capitalize its name else ask for new coating definition
        if objectIndex ~= 0
            tblData = get(aodHandles.tblStandardData,'data');
            tblData{eventdata.Indices(1),9} = upper(tblData{eventdata.Indices(1),9});
            set(aodHandles.tblStandardData, 'Data', tblData);
        else
            button = questdlg('The glass is not found in the catalogues. Do you want to add or choose another?','Glass Not Found');
            switch button
                case 'Yes'
                    glassEnteryFig = glassDataInputDialog(glassCatalogueListFullNames);
                    set(glassEnteryFig,'WindowStyle','Modal');
                    uiwait(glassEnteryFig);
                    try
                        load('tempglass.mat','glassObj');
                        selectedGlassName = glassObj.Name;
                        delete('tempglass.mat')
                    catch
                        selectedGlassName = '';
                    end
                    tblData = get(aodHandles.tblStandardData,'data');
                    tblData{eventdata.Indices(1),9} = upper(selectedGlassName);
                    set(aodHandles.tblStandardData, 'Data', tblData);
                case 'No'
                    % Do nothing
                    disp('Warning: Undefined glass used. It may cause problem in the analysis.');
                case 'Cancel'
                    tblData = get(aodHandles.tblStandardData,'data');
                    tblData{eventdata.Indices(1),9} = '';
                    set(aodHandles.tblStandardData, 'Data', tblData);
            end
        end
    end
elseif eventdata.Indices(2) == 13 %if semi diameter is changed update aperture
     % update aperture table if it is Floating Aperture
     tblData2 = get(aodHandles.tblApertureData,'data');
     if strcmpi(tblData2{eventdata.Indices(1),3},'Floating')
        tblData2{eventdata.Indices(1),5} = eventdata.NewData;
        tblData2{eventdata.Indices(1),7} = eventdata.NewData;
     end
     set(aodHandles.tblApertureData, 'Data', tblData2);
elseif eventdata.Indices(2) == 15 % if coating is changed
    % check for its existance among selected catalogues
    coatName = eventdata.NewData;
    objectType = 'coating';
    objectName = coatName;
    % Coating Catalogue
    tableData1 = get(aodHandles.tblCoatingCatalogues,'data');
    if ~isempty(tableData1)
        % Take only the selected ones
        selectedRows1 = find(cell2mat(tableData1(:,1)));
        if ~isempty(selectedRows1)
            coatingCatalogueListFullNames = tableData1(selectedRows1,3);
        else
            coatingCatalogueListFullNames = '';
        end
    else
        coatingCatalogueListFullNames = '';
    end
    objectCatalogueListFullNames = coatingCatalogueListFullNames;
    objectIndex = 0;
    for kk = 1:size(objectCatalogueListFullNames,1)
        objectCatalogueFullName = objectCatalogueListFullNames{kk};
        [ aodObject,objectIndex ] = extractObjectFromAODObjectCatalogue...
            (objectType,objectName,objectCatalogueFullName );
        if objectIndex ~= 0
            break;
        end
    end
    % if empty, replace with None. If it exists in the catal capitalize its
    % name else ask for new coating definition
    if isempty(coatName)
        coatName = 'None';
        tblData = get(aodHandles.tblStandardData,'data');
        tblData{eventdata.Indices(1),15} = upper(coatName);
        set(aodHandles.tblStandardData, 'Data', tblData);
    elseif objectIndex ~= 0
        tblData = get(aodHandles.tblStandardData,'data');
        tblData{eventdata.Indices(1),15} = upper(tblData{eventdata.Indices(1),15});
        set(aodHandles.tblStandardData, 'Data', tblData);
    else
        button = questdlg('The coating is not found in the catalogues. Do you want to add or choose another?','Coating Not Found');
        switch button
            case 'Yes'
                coatingEnteryFig = coatingDataInputDialog(coatingCatalogueListFullNames);
                set(coatingEnteryFig,'WindowStyle','Modal');
                uiwait(coatingEnteryFig);
                try
                    load('tempcoating.mat','coatingObj');
                    selectedCoatingName = coatingObj.Name;
                    delete('tempcoating.mat')
                catch
                    selectedCoatingName = 'None';
                end
                tblData = get(aodHandles.tblStandardData,'data');
                tblData{eventdata.Indices(1),15} = upper(selectedCoatingName);
                set(aodHandles.tblStandardData, 'Data', tblData);
            case 'No'
                % Do nothing Just leave it
                disp('Warning: Undefined caoting used. It may cause problem in the analysis.');
            case 'Cancel'
                tblData = get(aodHandles.tblStandardData,'data');
                tblData{eventdata.Indices(1),15} = 'NONE';
                set(aodHandles.tblStandardData, 'Data', tblData);
        end
    end
end
end
% --- Executes when entered data in editable cell(s) in aodHandles.tblAsphericData.
function tblAsphericData_CellEditCallback(~, eventdata,aodHandles)
if eventdata.Indices(2) == 3 % if conic constant is changed
     tblData4 = get(aodHandles.tblAsphericData,'data');
     if strcmpi(tblData4{eventdata.Indices(1),2},'Plane')||...
         strcmpi(tblData4{eventdata.Indices(1),2},'Spherical')
     if str2double(strtrim(eventdata.NewData)) ~= 0
         msgbox(['Conic constant is not defined for Plane and Spherical ',...
             'surfaces. Please change the surface type first.'],...
             'Change Surface Type');
         tblData4{eventdata.Indices(1),3} = '0';
         set(aodHandles.tblAsphericData, 'Data', tblData4);
     end
     end
elseif eventdata.Indices(2) > 3 % if polynomial coefficnets are changed
     tblData4 = get(aodHandles.tblAsphericData,'data');
     if strcmpi(tblData4{eventdata.Indices(1),2},'Plane')||...
         strcmpi(tblData4{eventdata.Indices(1),2},'Spherical')||...
         strcmpi(tblData4{eventdata.Indices(1),2},'Conic Aspherical')
     if str2double(strtrim(eventdata.NewData)) ~= 0
         msgbox(['Polynomial coefficients are not defined for Plane, Spherical ',...
             'and Conic Aspherical surfaces. Please change the surface type first.'],...
             'Change Surface Type');
         tblData4{eventdata.Indices(1),eventdata.Indices(2)} = '0';
         set(aodHandles.tblAsphericData, 'Data', tblData4);
     end
     end
end
end
% --- Executes when entered data in editable cell(s) in aodHandles.tblApertureData.
function tblApertureData_CellEditCallback(~, ~,~)
end
% --- Executes when entered data in editable cell(s) in aodHandles.tblTiltDecenterData.
function tblTiltDecenterData_CellEditCallback(~, eventdata,aodHandles)
if eventdata.Indices(2) == 3  % 3rd row / tiltanddecenter data
    if isempty(eventdata.NewData) || ...
            ~isValidGeneralInput(eventdata.NewData,'TiltDecenterOrder')
        % restore previous data
        tblData = get(aodHandles.tblTiltDecenterData,'data');
        tblData{eventdata.Indices(1),3} = eventdata.PreviousData;
        set(aodHandles.tblTiltDecenterData, 'Data', tblData);
    else
        % valid input so format the text
        orderStr = upper(eventdata.NewData);
        formatedOrder(1:2:11) = upper(orderStr(1:2:11));
        formatedOrder(2:2:12) = lower(orderStr(2:2:12));
        tblData = get(aodHandles.tblTiltDecenterData,'data');
        tblData{eventdata.Indices(1),3} = formatedOrder;
        set(aodHandles.tblTiltDecenterData, 'Data', tblData);
    end
end
end
% --- Executes when selected cell(s) is changed in aodHandles.tblStandardData.
function tblStandardData_CellSelectionCallback(~, eventdata,aodHandles)
global SELECTED_CELL
global CAN_ADD
global CAN_REMOVE
SELECTED_CELL = cell2mat(struct2cell(eventdata)); %struct to matrix
if isempty(SELECTED_CELL)
    return
end
tblData = get(aodHandles.tblStandardData,'data');
sizeTblData = size(tblData);
if SELECTED_CELL(2)==1 % only when the first column selected
    if SELECTED_CELL(1)==1
        CAN_ADD = 0;
        CAN_REMOVE = 0;
        columnEditable1 =  [false true true false true false true false true false true false true false true false];
        sysTable1 = aodHandles.tblStandardData;
        set(sysTable1,'ColumnEditable', columnEditable1);
    elseif SELECTED_CELL(1)== sizeTblData(1)
        CAN_ADD = 1;
        CAN_REMOVE = 0;
        columnEditable1 =  [false true true false true false true false true false true false true false true false];
        sysTable1 = aodHandles.tblStandardData;
        set(sysTable1,'ColumnEditable', columnEditable1);
    else
        CAN_ADD = 1;
        CAN_REMOVE = 1;
        columnEditable1 =  [true true true false true false true false true false true false true false true false];
        sysTable1 = aodHandles.tblStandardData;
        set(sysTable1,'ColumnEditable', columnEditable1);
    end
end
end
% --- Executes when selected cell(s) is changed in aodHandles.tblAsphericData.
function tblAsphericData_CellSelectionCallback(~, ~,~)
end
% --- Executes when selected cell(s) is changed in aodHandles.tblApertureData.
function tblApertureData_CellSelectionCallback(~, ~,~)
end
% --- Executes when selected cell(s) is changed in aodHandles.tblTiltDecenterData.
function tblTiltDecenterData_CellSelectionCallback(~, ~,~)
end