Description of Glass
Glass
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Glass
This function is called by:
InitializeMenuAndToolbarItems Defines all menu items and toolbar commands and all callbacks related
getCurrentOpticalSystem getCurrentOpticalSystem: Constructs an optical system object from the AOD
Glass
displaySurfaceData Displays the surface properties of an optical system
Surface
glassDataInputDialog GLASSDATAINPUTDIALOG Defines a dilog box which is used to input glass
importZemaxFile importZemaxFile: imports lens data from .zmx file format generated by zemax.
SUBFUNCTIONS
function GLASS = Glass(glassName,glassType,glassParameters)
SOURCE CODE
classdef Glass
    % Glass Class:
    %   Glass Defines optical glass in the optical system
    %   The temprature dependance of refractive index of the glass is ignored
    %   in the current version
    % Properties:
    %     %standard data
    %     Name % None for free space and the name of the glass for other cases
    %     Type % 'FixedIndex', 'Sellmeier1'
    %     GlassParameters % Array of numbers vary depending on the type
    %                     % [B1,C1,B2,C2,B3,C3] for Sellmeier1 Formula
    %                     % [Nd,Vd,PgF] for FixedIndex Glass as in zemax (d line
    %                     % used)
    % Methods:
    %     %constructor
    %     function GLASS = Glass(glassName,glassType,glassParameters)
            % Glass: A function used to constract a new Glass object
    %     function [n] = getRefractiveIndex(Glass,wavLen)
    %         % getRefractiveIndex: Returns the refractive index of the glass
    %         % for a given wavelength. Uses sellmeir equation.
    %     function [abbeNumber] = getAbbeNumber(Glass,wavLenF,wavLenD,wavLenC)
    %         % getAbbeNumber: Returns abbe number of glass computed from
    %         % refractive indices at three different wavelengths
    % <<<<<<<<<<<<<<<<<<<<<<< Algorithm Section>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %
    % <<<<<<<<<<<<<<<<<<<<<<<<< Example Usage>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %
    % <<<<<<<<<<<<<<<<<<<<<<<<< Author Section >>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %   Written By: Worku, Norman Girma
    %   Advisor: Prof. Herbert Gross
    %   Part of the RAYTRACE_TOOLBOX V3.0 (OOP Version)
    %    Optical System Design and Simulation Research Group
    %   Institute of Applied Physics
    %   Friedrich-Schiller-University of Jena
    % <<<<<<<<<<<<<<<<<<< Change History Section >>>>>>>>>>>>>>>>>>>>>>>>>>
    % Date----------Modified By ---------Modification Detail--------Remark
    % Oct 14,2013   Worku, Norman G.     Original Version       Version 3.0
    % <<<<<<<<<<<<<<<<<<<<< Main Code Section >>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    properties
        %standard data
        Name % None for free space and the name of the glass for other cases
        Type % 'FixedIndex', 'Sellmeier1'
        GlassParameters % Array of numbers vary depending on the type
                        % [B1,C1,B2,C2,B3,C3] for Sellmeier1 Formula
                        % [Nd,Vd,PgF] for FixedIndex Glass as in zemax (d line
                        % used)
    end
    methods
        % Constructor
        function GLASS = Glass(glassName,glassType,glassParameters)
            % Glass: A function used to constract a new Glass object
            if  nargin == 0 % Enable construction  with no inputs
                GLASS.Name = 'None';
                GLASS.Type = 'FixedIndex';
                GLASS.GlassParameters = [1,0,0]';
            elseif nargin == 1
                GLASS.Name = glassName;
                GLASS.Type = 'FixedIndex';
                % Check if glassName is just the refractive index
                if isnan(str2double(glassName))
                    GLASS.GlassParameters = [1,0,0]';
                else
                    GLASS.GlassParameters = [str2double(glassName),0,0]';
                end
            elseif nargin == 2
                GLASS.Name = glassName;
                GLASS.Type = 'FixedIndex';
                GLASS.GlassParameters = [1,0,0]';
            elseif nargin == 3
                GLASS.Name = glassName;
                GLASS.Type = glassType;
                GLASS.GlassParameters = glassParameters;
            end
        end
    end
end