Description of AODChildWindow
AODChildWindow
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
AODChildWindow
AODParentWindow
This function is called by:
AODChildWindow
InitializeMenuAndToolbarItems Defines all menu items and toolbar commands and all callbacks related
SUBFUNCTIONS
function NewChild = AODChildWindow(myName,myParent)
function btnMainTab_Callback(childWindow,~, ~,tabInd)
function btnOk_Callback(childWindow,~,~, myParent)
function btnCancel_Callback(childWindow,~,~, myParent)
SOURCE CODE
classdef AODChildWindow < handle
    % AODChildWindow: class defining all child windows. Defining all
    % childwindows in the same class file enables shared usage of UI controls
    % among all windows and simplifies any future modifications.
    properties
        AODChildHandles
    end
    methods
        % Constructor method
        function NewChild = AODChildWindow(myName,myParent)
            fontSize = myParent.AODParentHandles.FontSize;
            [ currentOpticalSystem,saved] = ...
                myParent.getCurrentOpticalSystem;
            nSurface = currentOpticalSystem.NumberOfSurfaces;
            nField = currentOpticalSystem.NumberOfFieldPoints;
            nWavelength = currentOpticalSystem.NumberOfWavelengths;
            if nargin == 0
                % If nothing is given, then just abort the operation
                NewChild.AODChildHandles = struct();
                return;
            elseif nargin == 1
                % If only name of the child is given, then initialize a new parent window
                myParent = AODParentWindow;
            elseif nargin == 2
                % If both inputs given then continue normally
            end
            NewChild.AODChildHandles = struct();
            NewChild.AODChildHandles.Name = myName;
            NewChild.AODChildHandles.Index = size(myParent.AODChildWindows,2)+1;
            NewChild.AODChildHandles.FontSize = fontSize;
            NewChild.AODChildHandles.nMainTab = 4;
            NewChild.AODChildHandles.FigureHandle = figure( ...
                'Tag', 'AODChildWindow', ...
                'Units', 'normalized', ...
                'Name', myName, ...
                'MenuBar', 'figure', ...
                'Toolbar','figure',...
                'NumberTitle', 'on', ...
                'Units','normalized',...
                'Position',[0.2,0.2,0.5,0.6],...
                'Color', get(0,'DefaultUicontrolBackgroundColor'), ...
                'Resize', 'on', ...
                'Visible', 'off');
            % Add the child to the parent
            myParent.addChild(NewChild);
            % Build the GUI based on the myName
            % Common panels shared by multiple windows
            %% Edit Standard Toolbar by removing the first two toolbar buttons
            stdToolBar = (findall(...
                NewChild.AODChildHandles.FigureHandle,'Type','uitoolbar'));
            stdToolBarBtns = allchild(stdToolBar);
            set(stdToolBarBtns(end),'Visible','off');
            set(stdToolBarBtns(end-1),'Visible','off');
            % Add a refresh button at the end
            updateIcon = rand(19,23,3)*0;
            updateIcon(4:17,5:7,:) = 1;
            updateIcon(4:17,16:18,:) = 1;
            updateIcon(15:17,5:16,:) = 1;
            NewChild.AODChildHandles.btnRefresh = uitoggletool(stdToolBar,...
                'CData',updateIcon,...
                'Separator','on',...
                'TooltipString','Update',...
                'HandleVisibility','on',...
                'ClickedCallback', {@NewChild.btnOk_Callback,...
                myParent});
            % Define three tabs as combination  of button and panels
            NewChild.AODChildHandles.mainTabGroup = uipanel(...
                'Parent', NewChild.AODChildHandles.FigureHandle, ...
                'Units', 'Normalized', ...
                'Position', [0, 0, 1.0, 1.0]);
            tabBtnWidth = 0.12;
            tabBtnHeight = 0.04;
            for k = 1:NewChild.AODChildHandles.nMainTab
                switch k
                    case 1
                        tabString = 'Setting';
                    case 2
                        tabString = 'Graph';
                    case 3
                        tabString = 'Text';
                    case 4
                        tabString = 'Table';
                end
                NewChild.AODChildHandles.panelMainTab(k) = ....
                    uipanel(NewChild.AODChildHandles.mainTabGroup,...
                    'FontSize',fontSize,'FontName', 'FixedWidth',...
                    'Units', 'Normalized', ...
                    'Visible','off',...
                    'Position', [0, 0, 1.0, 0.95]);
                NewChild.AODChildHandles.btnMainTab(k) = ....
                    uicontrol(NewChild.AODChildHandles.mainTabGroup,...
                    'Units', 'Normalized', ...
                    'FontSize',fontSize,'FontName', 'FixedWidth',...
                    'Style','pushbutton',...
                    'BackgroundColor',[200,200,200]./256,...
                    'Position', [(k-1)*tabBtnWidth, 0.955, tabBtnWidth, tabBtnHeight],...
                    'String',tabString);
            end
            for k = 1:NewChild.AODChildHandles.nMainTab
                set(NewChild.AODChildHandles.btnMainTab(k),...
                    'Callback',{@NewChild.btnMainTab_Callback,k});
            end
            NewChild.AODChildHandles.axesHandle = axes( ...
                'parent',NewChild.AODChildHandles.panelMainTab(2),...
                'FontSize',fontSize,'FontName', 'FixedWidth',...
                'Units', 'Normalized',...
                'Position', [0.1,0.1, 0.8, 0.8]);
            NewChild.AODChildHandles.textHandle = uicontrol( ...
                NewChild.AODChildHandles.panelMainTab(3),...
                'Units', 'Normalized',...
                'Style','edit',...
                'Enable','inactive',...
                'FontSize',fontSize,...
                'FontName', 'FixedWidth',...
                'Min',0,...
                'Max',10000,...
                'HorizontalAlignment','left',...
                'BackgroundColor',[1,1,1],...
                'String','All text outputs will be displayed here . . . ',...
                'Position', [0,0,1,1]);
            NewChild.AODChildHandles.tableHandle = uitable( ...
                'Parent',NewChild.AODChildHandles.panelMainTab(4),...
                'FontSize',fontSize,'FontName', 'FixedWidth',...
                'Units', 'Normalized', ...
                'ColumnName', {['----------------------------------'...
                ' Data Table ------------------------------------']},...
                'Position', [0,0, 1, 1]);
            % Create all uicontrols which can be used in the setting
            % windows
            NewChild.BuildChildWindowSettingPanel(myParent,...
                fontSize, nSurface, nField, nWavelength);
            % Define Ok, Cancel and close buttons and add to Setting Tab
            btnWidth = .18;
            btnHeight = .06;
            NewChild.AODChildHandles.btnOk = uicontrol( ...
                NewChild.AODChildHandles.panelMainTab(1),...
                'Units', 'Normalized', ...
                'Style','pushbutton',...
                'FontSize',fontSize,'FontName', 'FixedWidth',...
                'Position', [0.6, 0.03, btnWidth, btnHeight],...
                'String','Ok',...
                'Callback', {@NewChild.btnOk_Callback,...
                myParent});
            NewChild.AODChildHandles.btnCancel = uicontrol( ...
                NewChild.AODChildHandles.panelMainTab(1),...
                'Units', 'Normalized', ...
                'Style','pushbutton',...
                'FontSize',fontSize,'FontName', 'FixedWidth',...
                'Position', [0.8, 0.03, btnWidth, btnHeight],...
                'String','Cancel',...
                'Callback', {@NewChild.btnCancel_Callback,...
                myParent});
            set(NewChild.AODChildHandles.FigureHandle,...
                'CloseRequestFcn',{@NewChild.btnCancel_Callback,...
                myParent})
            % Click setting tab programatically
            ind = 1;
            NewChild.selectMainTab(ind);
        end
        % Callbacks
        function btnMainTab_Callback(childWindow,~, ~,tabInd)
            childWindow.selectMainTab(tabInd)
        end
        % Function Callbacks for Ok and cancel buttons
        function btnOk_Callback(childWindow,~,~, myParent)
            childWindow.btnOkCallback(myParent);
        end
        function btnCancel_Callback(childWindow,~,~, myParent)
            myParent.RemoveFromOpenedWindowsList(childWindow);
            childWindow.closeChild;
        end
    end
end