function InitializePanels(parentWindow)
% InitializeOpenedWindowsPanel: Define and initialized the uicontrols of the 
% four panels of the parent window (panelWelcome,panelSurfaceEditorMain,
% panelSystemConfigurationData,panelOpenedWindows)
% Member of AODParentWindow class

    aodHandles = parentWindow.AODParentHandles;
    fontSize = aodHandles.FontSize;
    fontName = aodHandles.FontName;
    
    nMainTab = aodHandles.nMainTab;
    aodHandles.panelMain = uipanel(...
        'Parent',aodHandles.FigureHandle,...
        'FontSize',fontSize,'FontName', fontName,...
        'units','normalized',....
        'Position',[0.15,0.04,0.85,0.96]);    

    aodHandles.mainTabGroup = uipanel(...
        'Parent', aodHandles.panelMain, ...
        'Units', 'Normalized', ...
        'Position', [0, 0, 1.0, 1]); 
    tabBtnWidth = 0.18;
    tabBtnHeight = 0.04;
    for k = 1:nMainTab
        switch k
            case 1
                tabString = 'Welcome';
            case 2
                tabString = 'Surface Editor';
            case 3
                tabString = 'System Configuration';
            case 4
                tabString = 'Component Editor';
        end
        aodHandles.panelMainTab(k) = ....
            uipanel('Parent',aodHandles.mainTabGroup,...
            'FontSize',fontSize,'FontName', fontName,...
            'Units', 'Normalized', ...
            'Position', [0, 0, 1.0, 0.95]);
        aodHandles.btnMainTab(k) = ....
            uicontrol('Parent',aodHandles.mainTabGroup,...
            'Units', 'Normalized', ...
            'FontSize',fontSize,'FontName', fontName,...
            'Style','pushbutton',...
            'BackgroundColor',[200,200,200]./256,...
            'Position', [(k-1)*tabBtnWidth, 0.955, tabBtnWidth, tabBtnHeight],...
            'String',tabString);       
    end
   
    for k = 1:nMainTab
         set(aodHandles.btnMainTab(k),...
            'Callback',{@btnMainTab_Callback,parentWindow,k}); 
    end
    aodHandles.panelWelcome = uipanel(...
        'Parent',aodHandles.panelMainTab(1),...
        'FontSize',fontSize,'FontName', fontName,...
        'Units','Normalized',...
        'Position',[0,0,1,1]);
    aodHandles.panelSurfaceEditorMain = uipanel(...
        'Parent',aodHandles.panelMainTab(2),...
        'FontSize',fontSize,'FontName', fontName,...
        'Units','Normalized',...
        'Position',[0,0,1,1]);
    aodHandles.panelSystemConfigurationData = uipanel(...
        'Parent',aodHandles.panelMainTab(3),...
        'FontSize',fontSize,'FontName', fontName,...
        'Units','Normalized',...
        'Position',[0,0,1,1]);

    aodHandles.panelComponentEditorMain = uipanel(...
        'Parent',aodHandles.panelMainTab(4),...
        'FontSize',fontSize,'FontName', fontName,...
        'Units','Normalized',...
        'Position',[0,0,1,1]);
    
    aodHandles.panelLeftSide = uipanel(...
        'Parent',aodHandles.FigureHandle,...
        'FontSize',fontSize,'FontName', fontName,...
        'Units','Normalized',...
        'Position',[0,0.04,0.15,0.96]);
    
    aodHandles.panelOpenedWindows = uipanel(...
        'Parent',aodHandles.FigureHandle,...
        'FontSize',fontSize,'FontName', fontName,...
        'Units','Normalized',...
        'Position',[0,0.04,0.15,0.96]); 
    
    nTaskBar = 5;
    for k = 1:nTaskBar
        aodHandles.panelTaskBar(k) = uipanel(...
            'Parent',aodHandles.FigureHandle,...
            'FontSize',fontSize,'FontName', fontName,...
            'Units','Normalized',...
            'Position',[(k-1)/nTaskBar,0,1/nTaskBar,0.04]);
    end
   
   % Callbacks   
   function btnMainTab_Callback(~, ~, parentWindow,tabInd)
       selectMainTab(parentWindow,tabInd)
   end
parentWindow.AODParentHandles = aodHandles;
end

