function parentWindow = resetSSEditorPanel(parentWindow) 
% resetSSEditorPanel: reset all surface editor tables in sequence of
% surface editor.
% Member of AODParentWindow class

    aodHandles = parentWindow.AODParentHandles;
    % Initialize the panel and table for standard data    
    surfDefinition = 'Standard';
    surfaceDefinitionHandle = str2func(surfDefinition);
    returnFlag = 1;
    [fieldNames,fieldFormat,initialData] = surfaceDefinitionHandle(returnFlag);
    nColumns = size(fieldNames,2);
    columnNames = fieldNames;
    columnWidth = num2cell(100*ones(1,nColumns));
    columnEditable = num2cell(ones(1,nColumns));
    columnFormat = fieldFormat;
    
    hGetSupportedSurfaces = str2func('GetSupportedSurfaces');
    supportedSurfaces = hGetSupportedSurfaces();
    
    columnName1 =   {'Surface', 'Name/Note', 'Surface Type', '',...
       'Thickness', '', 'Glass', '','Coating', '',columnNames{:}};
    columnWidth1 = {80, 100, 120, 15, 80, 15, 80, 15, 80, 15,columnWidth{:}};
    columnEditable1 =  [false true true false true false true false true ...
        false columnEditable{:}];
    initialTable1 = {'STOP',  '','Standard','',[0],'','','','','',initialData{:}};    
    set(aodHandles.tblSSStandardData, 'ColumnFormat', ...
        {'char', 'char',{supportedSurfaces{:}},'char','numeric', 'char','char', 'char',...
        'char', 'char', columnFormat{:}});
    set(aodHandles.tblSSStandardData,'ColumnEditable', logical(columnEditable1),...
        'ColumnName', columnName1,'ColumnWidth',columnWidth1);
    set(aodHandles.tblSSStandardData, 'Data', initialTable1);
        
     
    % Initialize the panel and table for aperture data
    columnName2 =   ...
        {'Surface', 'Surface Type', 'Aperture Type', '', 'Aper Param1', '',...
        'Aper Param2', '', 'Aper Decent X', '', 'Aper Decent Y', '',...
        'Clear Aperture','Additional Edge','Draw Fixed'};
    columnWidth2 = ...
        {80, 120, 100, 15, 90, 15, 90, 15, 90, 15, 90, 15, 90, 90,80};
    columnEditable2 =  ...
        [false false true false true false true false true false true false,true,true,true];
    initialTable2 = ...
        {'Surf',  'Standard','Floating','',[0],'',[0],'',[0],'',[0],'',[1],[0],false};
    set(aodHandles.tblSSApertureData , 'ColumnFormat', ...
        {'char', 'char', {'Floating' 'Circular' 'Rectangular' 'Elliptical'},...
        'char', 'numeric', 'char','numeric', 'char', 'numeric', 'char', 'numeric', 'char',...
        'numeric', 'numeric','logical'});
    set(aodHandles.tblSSApertureData, 'Data', initialTable2,'ColumnEditable', columnEditable2,...
        'ColumnName', columnName2,'ColumnWidth',columnWidth2);

    % Initialize the panel and table for tilt decenter data              
    % Tilt and Decenter order = index of [dx,dy,tx,ty,tz]
    columnName5 =   ...
        {'  Surface  ', 'Surface Type', '    Order    ', '', ...
        'Decenter X', '', 'Decenter Y', '', 'Tilt X', '',...
        'Tilt Y', '', 'Tilt Z', '', 'Tilt Mode', ''};
    columnWidth5 =   {80, 120, 120, 15, 80, 15, 80, 15, 80, 15,...
        80,15, 80, 15, 80, 15};
    columnEditable5 =  ...
        [false false true false true false true false true false ...
        true false true false true false];
    initialTable5 = ...
        {'Surf',  'Standard','DxDyDzTxTyTz','',[0],'',[0],'',[0],'',[0],'',[0],'','DAR',''};
    set(aodHandles.tblSSTiltDecenterData , 'ColumnFormat', {'char', 'char', 'char','char', 'numeric',...
        'char','numeric', 'char', 'numeric', 'char', 'numeric', 'char', 'numeric', 'char', ...
        {'DAR' 'NAX' 'BEN'},'char'});
    set(aodHandles.tblSSTiltDecenterData, 'Data', initialTable5,'ColumnEditable', ...
        columnEditable5,'ColumnName', columnName5,'ColumnWidth',columnWidth5);
       
   parentWindow.AODParentHandles = aodHandles;
end