Description of glassDataInputDialog
glassDataInputDialog
PURPOSE
GLASSDATAINPUTDIALOG Defines a dilog box which is used to input glass
SYNOPSIS
function [ figureHandle ] = glassDataInputDialog(glassCatalogueListFullNames,fontName,fontSize)
DESCRIPTION
GLASSDATAINPUTDIALOG Defines a dilog box which is used to input glass
 data based on its type. And returns a glass object constructed from the
 input data.
CROSS-REFERENCE INFORMATION
This function calls:
addObjectToAODObjectCatalogue addObjectToAODObjectCatalogue: Adds the given AOD object to the given
extractObjectFromAODObjectCatalogue EXTRACTCOATINGFROMCOATINGCATALOGUE extracts a AOD object from the catalogue
getAllAODObjectCatalogues FINDALLCOATINGCATALOGUES Searches for all aodObject catalogue files in the
removeObjectFromAODObjectCatalogue REMOVECOATINGTOCOATINGCATALOGUE removes a object to the given
Glass
This function is called by:
objectDataInputDialog objectDataInputDialog: Defines a dilog box which is used to input object
InitializeMenuAndToolbarItems Defines all menu items and toolbar commands and all callbacks related
InitializeSurfaceEditorPanel InitializeSurfaceEditorPanel: Define and initialized the uicontrols of the
SUBFUNCTIONS
function build_gui(glassObj)
function popGlassCatalogueName_Callback(~,~,handles)
function refreshGlassDataInputDialog(handles)
function popGlassType_Callback(hObject,~,handles)
function tblGlassList_CellSelectionCallback(hObject,eventdata,handles)
function displayGlassData(selectedCatalogueFullName,selectedGlassIndex,handles)
function cmdDeleteGlass_Callback(hObject,evendata,handles)
function cmdClearAll_Callback(hObject,evendata,handles)
function cmdSaveGlass_Callback(~,~,handles)
function cmdOk_Callback(hObject,evendata,handles)
function currentGlass = getCurrentGlass(handles)
function cmdCancel_Callback(hObject,evendata,handles)
SOURCE CODE
function [ figureHandle ] = glassDataInputDialog(glassCatalogueListFullNames,fontName,fontSize)
%GLASSDATAINPUTDIALOG Defines a dilog box which is used to input glass
% data based on its type. And returns a glass object constructed from the
% input data.
% Default Input
if nargin < 1
    % Get all catalogues from current folder
    glassCatalogueListFullNames = getAllAODObjectCatalogues('glass');
    fontSize = 9.5;
    fontName = 'FixedWidth';
elseif nargin == 1
    fontSize = 9.5;
    fontName = 'FixedWidth';
elseif nargin == 2
    fontName = 'FixedWidth';
end
if isempty(glassCatalogueListFullNames)
    figureHandle = NaN;
    disp('Error: No glass catalogue is found in the current folder.');
    return;
else
    [~,catalogueListFileNames,~] = cellfun(@(x) fileparts(x),...
       glassCatalogueListFullNames,'UniformOutput',false);
   % extract the first catalogue and first glass from the catalogue
    firstCatalogueGlassArray = extractObjectFromAODObjectCatalogue...
    ('glass','all',glassCatalogueListFullNames{1});
    firstCatalogueGlassgNames =  {firstCatalogueGlassArray.Name};
    try
        firstGlass = firstCatalogueGlassArray(1);
    catch
        firstGlass = Glass;
    end
    firstType = firstGlass.Type;
    switch lower(firstType)
        case lower('FixedIndex')
            firstTypeIndex = 1;
            firstGlassFixedIndexParameters = firstGlass.GlassParameters;
            firstGlassSellmeier1Parameters = [0,0,0,0,0,0]';
            visibilityFixedIndexGlassPanel = 'on';
            visibilitySellmeier1Panel = 'off';
        case lower('Sellmeier1')
            firstTypeIndex = 2;
            firstGlassSellmeier1Parameters = firstGlass.GlassParameters;
            firstGlassFixedIndexParameters = [1,0,0]';
            visibilityFixedIndexGlassPanel = 'off';
            visibilitySellmeier1Panel = 'on';
    end
    firstName = firstGlass.Name;
end
% Initialize handles structure
handles = struct();
glassObj = Glass;
% Create all UI controls
build_gui(glassObj);
% Assign function output
figureHandle = handles.FigureHandle;
    function build_gui(glassObj)
        % Creation of all uicontrols
%         handles.glassObject = glass;
        % --- FIGURE -------------------------------------
        handles.FigureHandle = figure( ...
            'Tag', 'FigureHandle', ...
            'Units','Normalized',...
            'Position', [0.3,0.3,0.5,0.5], ...
            'Name', 'Glass Data Entry', ... %'WindowStyle','Modal',...
            'MenuBar', 'none', ...
            'NumberTitle', 'off', ...
            'Color', get(0,'DefaultUicontrolBackgroundColor'));
        % --- PANELS -------------------------------------
        handles.panelSellmeier1GlassData = uipanel( ...
            'Parent', handles.FigureHandle, ...
            'Tag', 'panelMultilayerData', ...
            'Units','Normalized',...
            'Position', [0.45,0.12,0.53,0.85], ...
            'FontSize',fontSize,'FontName',fontName,...
            'Visible',visibilitySellmeier1Panel,...
            'Title', 'Sellmeier1 Coefficients');
        handles.panelFixedIndexGlassData = uipanel( ...
            'Parent', handles.FigureHandle, ...
            'Tag', 'panelMultilayerData', ...
            'Units','Normalized',...
            'Position', [0.45,0.12,0.53,0.85], ...
             'FontSize',fontSize,'FontName',fontName,...
            'Visible',visibilityFixedIndexGlassPanel,...
            'Title', 'FixedIndex Glass Partameters');
        handles.panelGlassListing = uipanel( ...
            'Parent', handles.FigureHandle, ...
            'Tag', 'panelGlassListing', ...
            'Units','Normalized',...
            'Position', [0.02,0.02,0.43,0.94], ...
             'FontSize',fontSize,'FontName',fontName,...
            'Visible','On');
        % -----------------------------------------------------------------
        handles.lblGlassCatalogueName = uicontrol( ...
            'Parent', handles.panelGlassListing, ...
            'Tag', 'lblGlassCatalogueName', ...
            'Style', 'text', ...
            'HorizontalAlignment','left',...
            'Units','Normalized',...
            'Position', [0.02,0.9,0.48,0.05], ...
            'FontSize',fontSize,'FontName',fontName,...
            'String', 'Catalogue Name');
        handles.popGlassCatalogueName = uicontrol( ...
            'Parent', handles.panelGlassListing, ...
            'Tag', 'popGlassCatalogueName', ...
            'Style', 'popupmenu', ...
            'FontSize',fontSize,'FontName',fontName,...
            'HorizontalAlignment','left',...
            'Units','Normalized',...
            'Position', [0.50,0.9,0.48,0.055], ...
            'BackgroundColor', [1 1 1],...
            'String',catalogueListFileNames);
        %-----------------------------------------------------------------
        handles.lblGlassName = uicontrol( ...
            'Parent', handles.panelGlassListing, ...
            'Tag', 'lblGlassName', ...
            'Style', 'text', ...
            'HorizontalAlignment','left',...
            'Units','Normalized',...
            'Position', [0.02,0.8,0.48,0.05], ...
            'FontSize',fontSize,'FontName',fontName,...
            'String', 'Glass Name');
        handles.txtGlassName = uicontrol( ...
            'Parent', handles.panelGlassListing, ...
            'Tag', 'txtGlassName', ...
            'Style', 'edit', ...
            'HorizontalAlignment','left',...
            'Units','Normalized',...
            'Position', [0.50,0.79,0.48,0.065], ...
            'BackgroundColor', [1 1 1], ...
            'String', firstName, ...
            'FontSize',fontSize,'FontName',fontName);
        % -----------------------------------------------------------------
        handles.lblGlassType = uicontrol( ...
            'Parent', handles.panelGlassListing, ...
            'Tag', 'lblGlassType', ...
            'Style', 'text', ...
            'HorizontalAlignment','left',...
            'Units','Normalized',...
            'Position', [0.02,0.7,0.48,0.05], ...
            'FontSize',fontSize,'FontName',fontName,...
            'String', 'Glass Type');
        handles.popGlassType = uicontrol( ...
            'Parent', handles.panelGlassListing, ...
            'Tag', 'popGlassType', ...
            'Style', 'popupmenu', ...
            'FontSize',fontSize,'FontName',fontName,...
            'HorizontalAlignment','left',...
            'Units','Normalized',...
            'Position', [0.50,0.7,0.48,0.055], ...
            'BackgroundColor', [1 1 1],...
            'String',{'FixedIndex','Sellmeier1'},...
            'Value',firstTypeIndex);
        %------------------------------------------------------------------
        %-----------------------------------------------------------------
        handles.tblFixedIndexParameters = uitable( ...
            'Parent',handles.panelFixedIndexGlassData,...
            'Tag', 'tblFixedIndexParameters', ...
            'UserData', zeros(1,0), ...
            'Units','Normalized',...
            'Position', [0.15,0.1,0.7,0.85], ...
            'FontSize',fontSize,'FontName',fontName,... ...
            'BackgroundColor', [1 1 1;0.961 0.961 0.961], ...
            'ColumnEditable', [true], ...
            'ColumnFormat', {'numeric'}, ...
            'ColumnName', {'Fixed Index Glass Parameters'}, ...
            'ColumnWidth', {200}, ...
            'RowName', {'Nd','Vd','PgF'},...
            'Data',firstGlassFixedIndexParameters);
        handles.tblSellmeier1Parameters = uitable( ...
            'Parent',handles.panelSellmeier1GlassData,...
            'Tag', 'tblSellmeier1Parameters', ...
            'UserData', zeros(1,0), ...
            'Units','Normalized',...
            'Position', [0.15,0.1,0.7,0.85], ...
            'FontSize',fontSize,'FontName',fontName,... ...
            'BackgroundColor', [1 1 1;0.961 0.961 0.961], ...
            'ColumnEditable', [true], ...
            'ColumnFormat', {'numeric'}, ...
            'ColumnName', {'Sellmeier Coefficients (in sq. um)'}, ...
            'ColumnWidth', {200}, ...
            'RowName',  {'B1','C1','B2','C2','B3','C3'},...
            'Data',firstGlassSellmeier1Parameters);
        %-----------------------------------------------------------------
        handles.tblGlassList = uitable( ...
            'Parent', handles.panelGlassListing, ...
            'Tag', 'tblGlassList', ...
            'Units','Normalized',...
            'Position', [0.02,0.02,0.96,0.65], ...
            'FontSize',fontSize,'FontName',fontName,... ...
            'BackgroundColor', [1 1 1;0.961 0.961 0.961], ...
            'ColumnEditable', [false], ...
            'ColumnFormat', {'char'}, ...
            'ColumnName', {'Glass Names'}, ...
            'ColumnWidth', {220}, ...
            'RowName', 'numbered',...
            'Data',firstCatalogueGlassgNames');
      %-------------------------------------------------------------------
      % Callbacks
       set(handles.popGlassCatalogueName,...
           'Callback',{@popGlassCatalogueName_Callback,handles});
       set(handles.popGlassType,...
           'Callback',{@popGlassType_Callback,handles});
       set(handles.tblGlassList,...
           'CellSelectionCallback',{@tblGlassList_CellSelectionCallback,handles});
      %------------------------------------------------------------------
      handles.cmdDeleteGlass = uicontrol( ...
            'Parent', handles.FigureHandle, ...
            'Tag', 'cmdDeleteGlass', ...
            'Style', 'pushbutton', ...
            'Units','Normalized',...
            'Position', [0.45,0.02,0.12,0.065], ...
            'FontSize',fontSize,'FontName',fontName,...
            'String', 'Delete', ...
            'Callback', {@cmdDeleteGlass_Callback,handles});
       handles.cmdSaveGlass = uicontrol( ...
            'Parent', handles.FigureHandle, ...
            'Tag', 'cmdSaveGlass', ...
            'Style', 'pushbutton', ...
            'Units','Normalized',...
            'Position', [0.59,0.02,0.12,0.065], ...
            'FontSize',fontSize,'FontName',fontName,...
            'String', 'Save', ...
            'Callback', {@cmdSaveGlass_Callback,handles});
       handles.cmdOk = uicontrol( ...
            'Parent', handles.FigureHandle, ...
            'Tag', 'cmdOk', ...
            'Style', 'pushbutton', ...
            'Units','Normalized',...
            'Position', [0.73,0.02,0.12,0.065], ...
            'FontSize',fontSize,'FontName',fontName,...
            'String', 'Ok', ...
            'Callback', {@cmdOk_Callback,handles});
       handles.cmdCancel = uicontrol( ...
            'Parent', handles.FigureHandle, ...
            'Tag', 'cmdCancel', ...
            'Style', 'pushbutton', ...
            'Units','Normalized',...
            'Position', [0.87,0.02,0.12,0.065], ...
            'FontSize',fontSize,'FontName',fontName,...
            'String', 'Cancel', ...
            'Callback', {@cmdCancel_Callback,handles});
    end
%% ---------------------------------------------------------------------------
    function popGlassCatalogueName_Callback(~,~,handles )
        refreshGlassDataInputDialog(handles);
    end
    function refreshGlassDataInputDialog(handles)
        selectedCatalogueFullName = glassCatalogueListFullNames{get(handles.popGlassCatalogueName,'Value')};
        % extract the selected catalogue and Glass from the catalogue
        selectedCatalogueGlassArray = extractObjectFromAODObjectCatalogue...
            ('Glass','all',selectedCatalogueFullName);
        selectedCatalogueGlassNames =  {selectedCatalogueGlassArray.Name};
        set(handles.tblGlassList,'Data',selectedCatalogueGlassNames');
        selectedGlassIndex = 1;
        displayGlassData(selectedCatalogueFullName,selectedGlassIndex,handles);
    end
%% ---------------------------------------------------------------------------
function popGlassType_Callback(hObject,~,handles)
    glassTypeList =  get(handles.popGlassType,'String');
    selectedGlassType = glassTypeList{get(hObject,'Value')};
    switch lower(selectedGlassType)
        case lower('FixedIndex')
            fixedIndexGlassPanelVisible = 'on';
            sellmeier1PanelVisible = 'off';
        case lower('Sellmeier1')
            fixedIndexGlassPanelVisible = 'off';
            sellmeier1PanelVisible = 'on';
    end
    set(handles.panelSellmeier1GlassData,...
        'Visible',sellmeier1PanelVisible);
    set(handles.panelFixedIndexGlassData,...
        'Visible',fixedIndexGlassPanelVisible);
end
function tblGlassList_CellSelectionCallback(hObject,eventdata,handles)
    selCell = eventdata.Indices;
    if ~isempty(selCell)
        selRow = selCell(1,1);
        selCol = selCell(1,2);
        selectedGlassIndex = selRow;
        selectedCatalogueFullName = glassCatalogueListFullNames...
            {get(handles.popGlassCatalogueName,'Value')};
        displayGlassData(selectedCatalogueFullName,selectedGlassIndex,handles)
    end
end
function displayGlassData(selectedCatalogueFullName,selectedGlassIndex,handles)
    % extract the selected Glass from the catalogue
    catalogueGlassArray = extractObjectFromAODObjectCatalogue...
        ('Glass','all',selectedCatalogueFullName);
    if isempty(catalogueGlassArray)
        catalogueGlassArray = Glass;
    end
    catalogueGlassNames =  {catalogueGlassArray.Name};
    if ~isempty(catalogueGlassNames)
        selectedGlassObject = catalogueGlassArray(selectedGlassIndex);
        selectedGlassType = selectedGlassObject.Type;
        selectedGlassParameters = selectedGlassObject.GlassParameters;
        selectedGlassName = selectedGlassObject.Name;
        switch lower(selectedGlassType)
            case lower('FixedIndex')
                selectedGlassTypeIndex = 1;
                fixedIndexGlassPanelVisible = 'on';
                sellmeier1PanelVisible = 'off';
                set(handles.tblFixedIndexParameters ,'Data',selectedGlassParameters);
            case lower('Sellmeier1')
                selectedGlassTypeIndex = 2;
                fixedIndexGlassPanelVisible = 'off';
                sellmeier1PanelVisible = 'on';
                set(handles.tblSellmeier1Parameters,'Data',selectedGlassParameters);
        end
        % Update all data
        set(handles.panelSellmeier1GlassData,...
            'Visible',sellmeier1PanelVisible);
        set(handles.panelFixedIndexGlassData,...
            'Visible',fixedIndexGlassPanelVisible);
        set(handles.popGlassType,'Value',selectedGlassTypeIndex);
        set(handles.txtGlassName,'String',selectedGlassName);
    end
end
%% ---------------------------------------------------------------------------
    function cmdDeleteGlass_Callback(hObject,evendata,handles) %#ok<INUSD>
        glassCatalogueIndex = get(handles.popGlassCatalogueName,'Value');
        selectedGlassCatalogueFullName = glassCatalogueListFullNames{glassCatalogueIndex};
        objectType = 'Glass';
        objectName = get(handles.txtGlassName,'String');
        objectCatalogueFullName = selectedGlassCatalogueFullName;
        removeObjectFromAODObjectCatalogue(objectType, objectName,objectCatalogueFullName )
        refreshGlassDataInputDialog(handles);
    end
%% ---------------------------------------------------------------------------
    function cmdClearAll_Callback(hObject,evendata,handles) %#ok<INUSD>
        set(handles.txtGlassName,'String','New');
        set(handles.tblSellmeier1Parameters,'Data',[0,0,0,0,0,0]');
        set(handles.tblFixedIndexParameters,'Data',[1,0,0]');
    end
%% ---------------------------------------------------------------------------
    function cmdSaveGlass_Callback(~,~,handles) %#ok<INUSD>
        objectType = 'Glass';
        aodObject = getCurrentGlass(handles);
        glassCatalogueIndex = get(handles.popGlassCatalogueName,'Value');
        objectCatalogueFullName = glassCatalogueListFullNames{glassCatalogueIndex};
        addObjectToAODObjectCatalogue(objectType, aodObject,objectCatalogueFullName,'ask');
        refreshGlassDataInputDialog(handles);
    end
%% ---------------------------------------------------------------------------
    function cmdOk_Callback(hObject,evendata,handles) %#ok<INUSD>
        objectType = 'Glass';
        aodObject = getCurrentGlass(handles);
        glassCatalogueIndex = get(handles.popGlassCatalogueName,'Value');
        objectCatalogueFullName = glassCatalogueListFullNames{glassCatalogueIndex};
        addObjectToAODObjectCatalogue(objectType, aodObject,objectCatalogueFullName,'replace');
        refreshGlassDataInputDialog(handles);
        glassObj = aodObject;
        save('tempglass.mat','glassObj');
        close(handles.FigureHandle);
    end
function currentGlass = getCurrentGlass(handles)
    glassTypeList = get(handles.popGlassType,'String');
    glassType = glassTypeList{get(handles.popGlassType,'Value')};
    glassName = get(handles.txtGlassName,'String');
    switch lower(glassType)
        case lower('FixedIndex')
             glassParameters = (get(handles.tblFixedIndexParameters,'Data'));
        case lower('Sellmeier1')
            glassParameters = (get(handles.tblSellmeier1Parameters,'Data'));
    end
    currentGlass = Glass(glassName,glassType,glassParameters);
end
%% ---------------------------------------------------------------------------
    function cmdCancel_Callback(hObject,evendata,handles) %#ok<INUSD>
        currentGlass = Glass;
        refreshGlassDataInputDialog(handles);
%         glassObj = Glass;
%         save('tempglass.mat','glassObj');
        close(handles.FigureHandle);
    end
end