Description of getAllFiles
getAllFiles
PURPOSE
getAllFiles: Searches for all files in the given directory. And
SYNOPSIS
function [ fileList ] = getAllFiles(dirName)
DESCRIPTION
getAllFiles: Searches for all  files in the given directory. And
 returns their full file names.
CROSS-REFERENCE INFORMATION
This function calls:
getAllFiles getAllFiles: Searches for all files in the given directory. And
This function is called by:
getAllAODObjectCatalogues FINDALLCOATINGCATALOGUES Searches for all aodObject catalogue files in the
getAllFiles getAllFiles: Searches for all files in the given directory. And
SOURCE CODE
function [ fileList ] = getAllFiles(dirName)
    %getAllFiles: Searches for all  files in the given directory. And
    % returns their full file names.
    % Default directory is caurrent directory
    if nargin < 1
        dirName = pwd;
    end
    dirData = dir(dirName);      % Get the data for the current directory
    dirIndex = [dirData.isdir];  % Find the index for directories
    fileList = {dirData(~dirIndex).name}';  % Get a list of the files
    if ~isempty(fileList)
        fileList = cellfun(@(x) fullfile(dirName,x),...  % Prepend path to files
            fileList,'UniformOutput',false);
    end
    subDirs = {dirData(dirIndex).name};  % Get a list of the subdirectories
    validIndex = ~ismember(subDirs,{'.','..'});  % Find index of subdirectories
    %   that are not '.' or '..'
    for iDir = find(validIndex)                  % Loop over valid subdirectories
        nextDir = fullfile(dirName,subDirs{iDir});    % Get the subdirectory path
        fileList = [fileList; getAllFiles(nextDir)];  % Recursively call getAllFiles
    end
end