Description of getAllAODObjectCatalogues
getAllAODObjectCatalogues
PURPOSE
FINDALLCOATINGCATALOGUES Searches for all aodObject catalogue files in the
SYNOPSIS
function [ aodObjectCatalogueFileList ] = getAllAODObjectCatalogues(objectType, dirName)
DESCRIPTION
FINDALLCOATINGCATALOGUES Searches for all aodObject catalogue files in the
 given directory. And returns their full file names.
CROSS-REFERENCE INFORMATION
This function calls:
createNewAODObjectCatalogue CREATENEWCOATINGCATALOGUE Create anew AOD object catalogue and intialize
getAllFiles getAllFiles: Searches for all files in the given directory. And
isValidAODObjectCatalogue ISVALIDCOATINGCATALOGUE Retruns whether the object catalogue is vlaid or
This function is called by:
openSavedOpticalSystem extract all data from a given OpticalSystem object "SavedOpticalSystem"
resetSystemConfigurationPanel resetSystemConfigurationPanel: reset all system configuration data
coatingDataInputDialog COATINGDATAINPUTDIALOG Defines a dilog box which is used to input coating
glassDataInputDialog GLASSDATAINPUTDIALOG Defines a dilog box which is used to input glass
SOURCE CODE
function [ aodObjectCatalogueFileList ] = getAllAODObjectCatalogues(objectType, dirName)
%FINDALLCOATINGCATALOGUES Searches for all aodObject catalogue files in the
% given directory. And returns their full file names.
% make the current path the default search path
if nargin < 1
    disp('Error: The getAllAODObjectCatalogues needs atleast objectType as argument');
    return;
elseif nargin == 1
    dirName = [pwd,'\Catalogue_Files'];
    if ~exist(dirName)
         mkdir(dirName);
         addpath(dirName);
         createNewAODObjectCatalogue('coating', ...
             [dirName,'\Coating_Catalogue00.mat'],'replace' );
         createNewAODObjectCatalogue('glass', ...
             [dirName,'\Glass_Catalogue00.mat'],'replace' );
    end
end
% get all files
fileList = getAllFiles(dirName);
validFileIndex = 0;
% loop through the file lists and check if they are valid aodObject catalogue
% files. NB. AODObject catalogue files have .MAT extension and have
% AODObjectArrry and FileInfoStruct variables. And FileInfoStruct.Type =
% 'Coating' or 'Glass' or 'OpticalSystem'
aodObjectCatalogueFileList{1,:} = [];
for k = 1:size(fileList,1)
    fullFileName = fileList{k,:};
    [pathstr,name,ext] = fileparts(fullFileName);
    if strcmpi(ext,'.mat') && ~ strcmpi(name(1),'$') % .mat files which are not hidden
        if isValidAODObjectCatalogue(objectType, fullFileName)
            validFileIndex = validFileIndex + 1;
            aodObjectCatalogueFileList{validFileIndex,:} = fullFileName;
        else
        end
    else
    end
end
disp([num2str(validFileIndex),' Valid AODObject Catalogue Files Found.']);
end