Description of OpticalSystem
OpticalSystem
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
OpticalSystem
Surface
This function is called by:
getCurrentOpticalSystem getCurrentOpticalSystem: Constructs an optical system object from the AOD
OpticalSystem
importZemaxFile importZemaxFile: imports lens data from .zmx file format generated by zemax.
Bundle_Oriented_Diffraction Clear command window
Bundle_Oriented_Polarization_Ray_Trace Clear command window
Bundle_Oriented_Scalar_Ray_Trace Clear command window
Coating_Analysis Clear command window
Single_Polarization_Ray_Trace Clear command window
System_Data_Display Clear command window
System_Diattenuation_Map Clear command window
TestVectorizedCodeSingleLens Clear command window
testLongitudinalAberration Test script for plotLongitudinalAberration.m function
SUBFUNCTIONS
function NewOpticalSystem = OpticalSystem(fullFilePath)
SOURCE CODE
classdef OpticalSystem
    % OPTICALSYSTEM Class:
    %   Defines the whole optical system
    % Properties: 30
    %     % Basic Components
    %     NumberOfSurfaces % total number of surfaces including the object,
    %                      % image and stop
    %     SurfaceArray % Array of surfaces starting from Object->Image surface
    %
    %
    %     % General System Properties
    %     SystemApertureType % {1:'Enterance Pupil Diameter',2:'Object Space NA',...
    %                     % 3:'Object Space F#',4:'Image Space NA',5:'Image Space F#'}
    %     SystemApertureValue % Value of the system aperture specified
    %
    %     StopIndex % index of stop surface
    %     StopHeight % stop height (radius)
    %
    %     LensName % Lens Name
    %     LensNote % Notes about the Lens
    %     WavelengthUnit % Units of wavelengths used, {1:'nanometer(nm)',
    %                    % 2:'micrometer(um)'}
    %     LensUnit % Unit of dimesnsions of the lens {1:'milimeter(mm)',
    %              % 2:'centimeter(cm)',3:'meter(m)'}
    %
    %     NumberOfWavelengths % total number of wavelengths used
    %     WavelengthMatrix % matrix , wavelength, weight of Wavelength Used
    %     PrimaryWavelengthIndex % Index of the primary wavelength
    %
    %     FieldType % Type of field specified either 'ObjectHeight' or 'Angle'
    %     NumberOfFieldPoints % total number of field points used
    %     FieldPointMatrix % matrix of X field, Y field & Weight
    %                      % (either object height or angle)
    %     % Boolean to show image and object side afocal and telecentric side afocal system.
    %     ObjectAfocal
    %     ImageAfocal
    %     ObjectTelecenteric
    %     ImageTelecenetric
    %
    %     % Coating Catalogue Files
    %     CoatingCataloguesList
    %     % Array of Glass Catalogues Used in the system
    %     GlassCataloguesList
    %
    %     % Pupil Apodization parameters
    %     ApodizationType % String 'Super Gaussian','None',...
    %     ApodizationParameters % Struct with apodization parameters
    %     % Eg. For 'Super Gaussian' it will have fields
    %     % MaximumIntensity , Order and BeamRadius
    %
    %     FieldNormalization % 'Radial', 'Rectangular'
    %     % Others
    %     SystemMode % "SEQ" Sequential or "NSQ" Non Sequential system
    %     SoftwareVersion % String Version of the software created the system
    %
    %     Saved % boolean showing whether the optical system is already saved or not
    %     PathName % full path name of saved optical system
    %     FileName % file name of saved optical system
    % Methods: 39
    %     All functions which operate on the optical system object are
    %     included here
    % <<<<<<<<<<<<<<<<<<<<<<< Algorithm Section>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %
    % <<<<<<<<<<<<<<<<<<<<<<<<< Example Usage>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %
    % <<<<<<<<<<<<<<<<<<<<<<<<< Author Section >>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %   Written By: Worku, Norman Girma
    %   Advisor: Prof. Herbert Gross
    %   Part of the RAYTRACE_TOOLBOX V3.0 (OOP Version)
    %    Optical System Design and Simulation Research Group
    %   Institute of Applied Physics
    %   Friedrich-Schiller-University of Jena
    % <<<<<<<<<<<<<<<<<<< Change History Section >>>>>>>>>>>>>>>>>>>>>>>>>>
    % Date----------Modified By ---------Modification Detail--------Remark
    % Oct 14,2013   Worku, Norman G.     Original Version       Version 3.0
    % <<<<<<<<<<<<<<<<<<<<< Main Code Section >>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    properties
        % Basic Components
        NumberOfSurfaces % total number of surfaces including the object & image
        SurfaceArray % Array of surfaces starting from Object->Image surface
        % General System Properties
        SystemApertureType % {1:'Enterance Pupil Diameter',2:'Object Space NA',...
        % 3:'Object Space F#',4:'Image Space NA',5:'Image Space F#'}
        SystemApertureValue % Value of the system aperture specified
        StopIndex % index of stop surface
        StopHeight % stop height (radius)
        LensName % Lens Name
        LensNote % Notes about the Lens
        WavelengthUnit % Units of wavelengths used, {1:'nanometer(nm)',
        % 2:'micrometer(um)'}
        LensUnit % Unit of dimesnsions of the lens {1:'milimeter(mm)',
        % 2:'centimeter(cm)',3:'meter(m)'}
        NumberOfWavelengths % total number of wavelengths used
        WavelengthMatrix % matrix , wavelength, weight of Wavelength Used
        PrimaryWavelengthIndex % Index of the primary wavelength
        FieldType % Type of field specified either 'ObjectHeight' or 'Angle'
        NumberOfFieldPoints % total number of field points used
        FieldPointMatrix % matrix of X field, Y field & Weight
        % (either object height or angle)
        % Boolean to show image and object side afocal and telecentric side afocal system.
        ObjectAfocal
        ImageAfocal
        ObjectTelecenteric
        ImageTelecenetric
        % Array of Coating Catalogue Files Used in the system
        CoatingCataloguesList
        % Array of Glass Catalogues Used in the system
        GlassCataloguesList
        % Pupil Apodization parameters
        ApodizationType % String 'None','Super Gaussian'...
        ApodizationParameters % Struct with apodization parameters
        % Eg. For 'Super Gaussian' it will have fields
        % MaximumIntensity , Order and BeamRadius
        FieldNormalization % 'Radial', 'Rectangular'
        % Others
        SystemMode % "SEQ" Sequential or "NSQ" Non Sequential system
        SoftwareVersion % String Version of the software created the system
        Saved % boolean showing whether the optical system is already saved or not
        PathName % full path name of saved optical system
        FileName % file name of saved optical system
    end
    methods
        % Constructor Methods
        function NewOpticalSystem = OpticalSystem(fullFilePath)
            % Constructs a new Optical system object either from previously
            % saved file or empty
            if nargin < 1
                % default constructor with empty argument
                NewOpticalSystem.NumberOfSurfaces = 0;
                NewOpticalSystem.SurfaceArray = Surface;
                NewOpticalSystem.SystemApertureType = 1;
                NewOpticalSystem.SystemApertureValue = 0;
                NewOpticalSystem.StopIndex = 1;
                NewOpticalSystem.StopHeight = 0;
                NewOpticalSystem.LensName = '';
                NewOpticalSystem.LensNote = '';
                NewOpticalSystem.WavelengthUnit = 1;
                NewOpticalSystem.LensUnit = 1;
                NewOpticalSystem.NumberOfWavelengths = 1;
                NewOpticalSystem.WavelengthMatrix = [0.55 1];
                NewOpticalSystem.PrimaryWavelengthIndex = 0;
                NewOpticalSystem.FieldType = 'ObjectHeight';   % object height
                NewOpticalSystem.NumberOfFieldPoints = 1;
                NewOpticalSystem.FieldPointMatrix = [0 0 1];
                NewOpticalSystem.ObjectAfocal = 0;
                NewOpticalSystem.ImageAfocal = 0;
                NewOpticalSystem.ObjectTelecenteric = 0;
                NewOpticalSystem.ObjectTelecenteric = 0;
                NewOpticalSystem.CoatingCataloguesList = '';
                NewOpticalSystem.ApodizationType = 'None';
                NewOpticalSystem.ApodizationParameters = '';
                NewOpticalSystem.FieldNormalization = 'Rectangular';
                NewOpticalSystem.SystemMode = 'SEQ';
                NewOpticalSystem.GlassCataloguesList = '';
                NewOpticalSystem.SoftwareVersion = '';
                NewOpticalSystem.Saved = 0;
                NewOpticalSystem.PathName = '';
                NewOpticalSystem.FileName = '';
            else
                % Open previously saved optical system from file
                load(fullFilePath);
                % load the object SavedOpticalSystem object to new optical
                % system
                NewOpticalSystem = SavedOpticalSystem;
            end
        end
    end
end