Description of tracePolarizedRay
tracePolarizedRay
PURPOSE
tracePolarizedRay: main function of polarized ray tracer
SYNOPSIS
function polarizedRayTracerResult = tracePolarizedRay(optSystem, objectRay, considerSurfAperture)
DESCRIPTION
 tracePolarizedRay: main function of polarized ray tracer
 The function is vectorized so it can work on multiple sets of
 inputs once at the same time. That is array of ray objects.
 Inputs
   optSystem: data type "OpticalSystem"
   ObjectRay: data type "Ray" or array of Ray object
 Output:
   polarizedRayTracerResult: array of "RayTraceResult" or can be
   matrix of RayTraceResult objects if the input is array of Ray
   object. Size : nSurface X nTotalRay
CROSS-REFERENCE INFORMATION
This function calls:
getReflectionCoefficients Computes the amplitude and power coefficients of reflection using
getTransmissionCoefficients Computes the amplitude and power coefficients of
getRefractiveIndex getRefractiveIndex: Returns the refractive index of the glass
RayTraceResult
compute3dDot compute3dDot: computes the dot product of two 3xN vectors
multiplySliced3DMatrices multiplySliced3DMatrices: To perform slicewise multiplication of 3D
computeAccumulatedPhase computeAccumulatedPhase: Computs phase accumulated in agiven path by
computePhasePropagationFactors computePhasePropagationFactors: computes the cosine ans sign of the phase
convertJVToPolVector convertJonesVectToPolVect Converts a given jones vector to polarization
convertJonesMatrixToPolarizationMatrix convertJonesToPolarizationMatrix: Converts 2D Jones Matrix to 3D P Matrix
normalizeJonesVector normalizeJonesVector normalizes a given jones vector
computeAngleBetweenVectors computeAngleBetweenVectors: to calculate the angle inc (the angle betweent
globalToLocalCoordinate GLOBALTOLOCALCOORDINATE the transfer from the reference coordinate system
computeIntersectionPoint COMPUTEINTERSECTIONPOINT to calculate the intersection point of a ray on one surface
computePathLength COMPUTEPATHLENGTH to calculate the path length of the ray from the start
computeReflectedRayDirection COMPUTERELFLECTEDRAYDIRECTION to calculate the new direction after reflection
computeRefractedRayDirection COMPUTEREFRACTEDRAYDIRECTION to calculate the new direction after refraction
computeSurfaceNormal COMPUTESURFACENORMAL to calculate the normal vector at a point of the surface
localToGlobalCoordinate LOCALTOGLOBALCOORDINATE the transfer from the local coordinate system back to
This function is called by:
SOURCE CODE
function polarizedRayTracerResult = tracePolarizedRay(optSystem, objectRay, considerSurfAperture)
    % tracePolarizedRay: main function of polarized ray tracer
    % The function is vectorized so it can work on multiple sets of
    % inputs once at the same time. That is array of ray objects.
    % Inputs
    %   optSystem: data type "OpticalSystem"
    %   ObjectRay: data type "Ray" or array of Ray object
    % Output:
    %   polarizedRayTracerResult: array of "RayTraceResult" or can be
    %   matrix of RayTraceResult objects if the input is array of Ray
    %   object. Size : nSurface X nTotalRay
    % <<<<<<<<<<<<<<<<<<<<<<< Algorithm Section>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %
    % 1.    Normalize the jones vector of initial ray and convert to
    %       Polarization Vector ()
    % 2.    Initialize the total phase to 0, total P and Q matrices to unity
    % 3.    Record the initial ray data, (including total phase, total P
    %       and Q matrices) at the object surface to ray trace result
    %       structure. The initial diattenuation and retardance are not defined.
    % 4.    For surface index , k = 2 to Total number of surface, nTotal
    %   a)    Transfer current ray location, direction and polarization vector
    %       to local coordinates corresponding to kth surface
    %   b)    Compute local intersection point with the surface and path length
    %       to the intersection point
    %   c)    Compute the phase advancement from the path length
    %   d)    Compute the local polarization vector before the coating
    %   e)    Compute the local surface normal at the intersection point
    %   f)    Compute local reflected or refracted ray direction by using
    %       Snell’s law in 3D  based on the surface deviation mod
    %   g)    Compute the jones matrix (either transmission or reflection) of
    %       the coating
    %   h)    Convert the coating jones matrix to polarization matrix ()
    %   i)    Compute the new local polarization vector after the coating
    %   j)    Update the total polarization ray tracing matrix P for the ray
    %   k)    Compute the parallel ray transport matrix Q related to the
    %       incident and exit directions
    %   l)    Update the total parallel ray transport matrix Q for the ray
    %   m)    Compute the diattenuation and retardance associated with the coating
    %   n)    Transfer  all vectors in local coordinate system back to the
    %       global coordinate system
    %   o)    Record : Ray Intersection Point, Incident Ray Direction, Exit
    %       Ray Direction, Surface Normal , Incidence Angle , Exit Angle ,
    %       Path Length , Polarization Vector Initial ,
    %       Polarization Vector Before Coating , Polarization Vector After Coating ,
    %       Diattenuation, Retardance, Total P Matrix and Total Q Matrix
    %       to the ray tracing result object.
    % 5.    Go to next surface
    % <<<<<<<<<<<<<<<<<<<<<<<<< Example Usage>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %
    % <<<<<<<<<<<<<<<<<<<<<<<<< Author Section >>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %   Written By: Worku, Norman Girma
    %   Advisor: Prof. Herbert Gross
    %   Part of the RAYTRACE_TOOLBOX V3.0 (OOP Version)
    %    Optical System Design and Simulation Research Group
    %   Institute of Applied Physics
    %   Friedrich-Schiller-University of Jena
    % <<<<<<<<<<<<<<<<<<< Change History Section >>>>>>>>>>>>>>>>>>>>>>>>>>
    % Date----------Modified By ---------Modification Detail--------Remark
    % Oct 14,2013   Worku, Norman G.     Original Version       Version 3.0
    % Jan 18,2014   Worku, Norman G.     Vectorized inputs and outputs
    % <<<<<<<<<<<<<<<<<<<<< Main Code Section >>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    % Deafualt arguments
    if nargin < 2
        disp(['Error: Missing Input. The function tracePolarizedray needs '...
            ' atleast the optical system and an object ray as input argument.']);
        return;
    elseif nargin == 2
        considerSurfAperture = 1;
    else
    end
    nSurface = optSystem.NumberOfSurfaces;
    % determine the lens units and wavelength units factors
    lensUnit = optSystem.LensUnit; % 1:'(mm)',2:'(cm)',3:'(m)'
    wavUnit = optSystem.WavelengthUnit; % 1:'(nm)',2:'(um)'
    lensUnitFactor = (lensUnit==1)*(10^-3) + (lensUnit==2)*(10^-2) +...
        (lensUnit==3)*(1);
    wavUnitFactor = (wavUnit==1)*(10^-9) + (wavUnit==2)*(10^-6);
    nRay = length(objectRay);
    polarized = [objectRay.Polarized];
    % Determine the tracing method. Polarized objects need polarized ray
    % trace.
    polarized = polarized(1);
    wavlen  = [objectRay.Wavelength]; % wavlen is in m for Ray object
    currentRayDirection = [objectRay.Direction];
    currentRayPosition = [objectRay.Position];
    % Initialize the total phase to 0,
    totalPhase = zeros([1,nRay]);
    if polarized
        jonesVector = [objectRay.JonesVector];
        % normalize the given jones vector and convert to Polarization Vector
        normalizedJonesVector = normalizeJonesVector(jonesVector);
        %% Shall be changed or checked
         currentRayPolarizationVector = (convertJVToPolVector(normalizedJonesVector,...
         currentRayDirection));
% currentRayPolarizationVector = convertJonesVectorToPolarizationVectorNew...
%     (normalizedJonesVector,currentRayDirection,[0;0;1]);
       %%
        % initialize toatl P, Q and coatingJonesMatrix matrices to unity;
        totalPMatrix = repmat(eye(3),[1,1,nRay]);
        totalQMatrix = repmat(eye(3),[1,1,nRay]);
        coatingJonesMatrix = repmat(eye(2),[1,1,nRay]);
        coatingPMatrix = repmat(eye(3),[1,1,nRay]);
        coatingQMatrix = repmat(eye(3),[1,1,nRay]);
    end
    % Initialize the matrix of ray trace result object. Preallocation
    multipleRayTracerResult(nSurface,nRay) = RayTraceResult;
    % Add initial ray at the object surface to ray trace result structure
    %  All 1 D array are recorded as 3x1 vertical vector
    infThickness = abs(currentRayPosition(3,:)) > 10^10;
    currentRayPosition(3,infThickness) = 0;
    currentSurfaceNormal = repmat([0;0;1],[1,nRay]); % assume plane object surface.
    RayIntersectionPoint = currentRayPosition;
    IncidentRayDirection = repmat([NaN;NaN;NaN],[1,nRay]); % no ray is incident to object surface
    ExitRayDirection = currentRayDirection;
    SurfaceNormal = currentSurfaceNormal; % [0,0,1]; % assume plane object surface.
    IncidenceAngle = NaN([1,nRay]);
    ExitAngle = computeAngleBetweenVectors...
             (currentRayDirection,currentSurfaceNormal);
    PathLength = zeros([1,nRay]);
    OpticalPathLength = zeros([1,nRay]);
    NoIntersectionPoint = zeros([1,nRay]);
    OutOfAperture = zeros([1,nRay]);
    TotalInternalReflection = zeros([1,nRay]);
    if polarized
        PolarizationVectorBeforeCoating = repmat([NaN;NaN;NaN],[1,nRay]);
        %  object surface has no coating
        PolarizationVectorAfterCoating = currentRayPolarizationVector;
        TotalPMatrix = totalPMatrix;
        TotalQMatrix = totalQMatrix;
        CoatingJonesMatrix = coatingJonesMatrix;
        CoatingPMatrix = coatingPMatrix;
        CoatingQMatrix = coatingQMatrix;
        multipleRayTracerResult(1,:) = RayTraceResult(RayIntersectionPoint,SurfaceNormal,...
           IncidentRayDirection,IncidenceAngle,ExitRayDirection,ExitAngle,...
           NoIntersectionPoint,OutOfAperture,TotalInternalReflection,PathLength,OpticalPathLength,...
           PolarizationVectorBeforeCoating,PolarizationVectorAfterCoating,...
           CoatingJonesMatrix,CoatingPMatrix,CoatingQMatrix,TotalPMatrix,TotalQMatrix);
    else
        multipleRayTracerResult(1,:) = RayTraceResult(RayIntersectionPoint,SurfaceNormal,...
            IncidentRayDirection,IncidenceAngle,ExitRayDirection,ExitAngle,...
            NoIntersectionPoint,OutOfAperture,TotalInternalReflection,PathLength,OpticalPathLength);
    end
    for surfaceIndex = 2:1:nSurface
       % Transfer current ray location, direction and polarization vector
       % to local coordinates corresponding to kth surface
       globalRayPosition = currentRayPosition;
       globalRayDirection = currentRayDirection;
       if polarized
           globalRayPolarizationVector = currentRayPolarizationVector;
           globalRayData = cat(3,globalRayPosition,globalRayDirection,...
               globalRayPolarizationVector);
       else
           globalRayData = cat(3,globalRayPosition,globalRayDirection);
       end
       %% New Code for Global to Local Coordinate transformation using Coordinate Transfer Matrix
       prevRefCoordinateTM = optSystem.SurfaceArray(surfaceIndex-1).ReferenceCoordinateTM;
       prevSurfCoordinateTM = optSystem.SurfaceArray(surfaceIndex-1).SurfaceCoordinateTM;
       prevThickness = optSystem.SurfaceArray(surfaceIndex-1).Thickness;
       if abs(prevThickness) > 10^10
          prevThickness = 0;
       end
       [surfaceCoordinateTM,referenceCoordinateTM] = ...
           optSystem.SurfaceArray(surfaceIndex).TiltAndDecenter...
                (prevRefCoordinateTM,prevSurfCoordinateTM,prevThickness);
        localRayData = globalToLocalCoordinate(globalRayData,polarized,...
           surfaceCoordinateTM,referenceCoordinateTM);
       %% End of New code
       % from this point onwards  currentRay become localRay
       currentRayPosition = localRayData(:,:,1);
       currentRayDirection = localRayData(:,:,2);
       if polarized
            currentRayPolarizationVector = localRayData(:,:,3);
       end
       % Path length calculation
       surfaceType = optSystem.SurfaceArray(surfaceIndex).Type;
       surfaceRadius = optSystem.SurfaceArray(surfaceIndex).Radius;
       surfaceConic = optSystem.SurfaceArray(surfaceIndex).ConicConstant;
       refractiveIndexBefore = optSystem.SurfaceArray(surfaceIndex-1).Glass. ...
           getRefractiveIndex(wavlen);
        rayInitialPosition = currentRayPosition;
        rayDirection = currentRayDirection;
        % Correction for collimated inclined rays from infinity
        % The ray positions should be shifted bit in such away that the OPL
        % will be the same for all rays initially.
        if surfaceIndex == 2 && optSystem.SurfaceArray(1).Thickness > 10^10
            % If any point on a line passing through P and with unit vector u
            % is given by Lp = P + u*t. (t is scalar shift along the line)
            % t for point where a perpendicular line from orign (0,0,0) cross the
            % given line is given by t = -P.u
            t = - compute3dDot(rayInitialPosition,rayDirection);
            rayInitialPosition = rayInitialPosition + rayDirection.*repmat(t,[3,1]);
        end
        [geometricalPathLength, opticalPathLength,NoIntersectionPoint] = computePathLength ...
            (rayInitialPosition,rayDirection,surfaceType,surfaceRadius,...
            surfaceConic,refractiveIndexBefore);  % 2nd function
        totalNoIntersection = sum(NoIntersectionPoint);
        if totalNoIntersection > 0
            disp([num2str(totalNoIntersection) , ' rays do not intersect surface ',...
                num2str(surfaceIndex),'. They have no intersection point. They are',...
                ' ignored in other computations.']);
        else
            disp(['All of ',num2str(nRay),' rays intersect surface ',num2str(surfaceIndex),'.']);
        end
        % compute current accumulated phase
        accumulatedPhase = computeAccumulatedPhase...
            (geometricalPathLength*lensUnitFactor,wavlen);
        % add current phase to exsisting total phase
        totalPhase = totalPhase + accumulatedPhase;
        apertureType = optSystem.SurfaceArray(surfaceIndex).ApertureType;
        apertureParam = optSystem.SurfaceArray(surfaceIndex).ApertureParameter;
        [localIntersectionPoint,outOfAperture] = computeIntersectionPoint(rayInitialPosition,...
            rayDirection, geometricalPathLength,apertureType,apertureParam,considerSurfAperture); % 3rd function
        totalOutOfAperture = sum(outOfAperture);
        if totalOutOfAperture > 0
            disp([num2str(totalOutOfAperture) , ' rays are vignated at surface ',...
                num2str(surfaceIndex),'. They intersect the surface outside the ' ,...
                'aperture area. They are ignored in other computations.']);
        else
            disp(['All of ',num2str(nRay),' rays pass through surface ',num2str(surfaceIndex),'.']);
        end
        currentRayPosition = localIntersectionPoint;
        if polarized
            % phase advancement
            % Zemax method, just multiply the real part by cos(phase) and imaginary
            % by sin(phase)
            [pc,ps] = computePhasePropagationFactors...
                (geometricalPathLength*lensUnitFactor,wavlen);
            currentRayPolarizationVector = (currentRayPolarizationVector).*repmat((pc + 1i *ps),[3,1]);
            currentRayPolarizationVectorBefore = currentRayPolarizationVector;
        end
        % Compute Reflection and Refraction by solving Snells law in 3D
        surfaceType = optSystem.SurfaceArray(surfaceIndex).Type;
        surfaceRadius = optSystem.SurfaceArray(surfaceIndex).Radius;
        surfaceConic = optSystem.SurfaceArray(surfaceIndex).ConicConstant;
        localSurfaceNormal = computeSurfaceNormal(localIntersectionPoint,...
            surfaceType,surfaceRadius,surfaceConic); % 4th function
        % If the thickness is Negative => Mirrored Z axis => the Z
        % compinent of the normal vector shall be in -ve direction
        % and x and y
        if prevThickness == 0
            localSurfaceNormal = localSurfaceNormal;
        else
            localSurfaceNormal = sign(prevThickness)*localSurfaceNormal;
        end
        localIncidentRayDirection = currentRayDirection;
        localIncidenceAngle = computeAngleBetweenVectors (localIncidentRayDirection,...
            localSurfaceNormal); % new function replacing yi's 5th function
        if surfaceIndex < nSurface
           indexBefore = optSystem.SurfaceArray(surfaceIndex-1).Glass. ...
               getRefractiveIndex(wavlen);
           indexAfter =  optSystem.SurfaceArray(surfaceIndex).Glass. ...
               getRefractiveIndex(wavlen);
           if polarized
                coatingType = optSystem.SurfaceArray(surfaceIndex).Coating.Type;
           end
           Kqm1 = localIncidentRayDirection;
           if strcmp(optSystem.SurfaceArray(surfaceIndex).DeviationMode,...
                    '-1 Reflective') % reflection
                localReflectedRayDirection = computeReflectedRayDirection ...
                    (localIncidentRayDirection,localSurfaceNormal); % 6th function
                localReflectedRayAngle = localIncidenceAngle;
                % direction of reflected ray
                currentRayDirection = localReflectedRayDirection;
                localExitRayDirection = localReflectedRayDirection;
                localExitAngle = localReflectedRayAngle;
                Kq = currentRayDirection;
                if polarized
                    % jones matrix for multiple rays with localIncidenceAngle
                    % Wavelength shall be converted to um
                    primaryWaveLenInUm = optSystem.getPrimaryWavelength*10^6;
                    wavLenInUm = wavlen*10^6;
                    [ampRs,ampRp,powRs,powRp,jonesMatrix]=...
                        optSystem.SurfaceArray(surfaceIndex).Coating. ...
                        getReflectionCoefficients(wavLenInUm,localIncidenceAngle,...
                        indexBefore,indexAfter,primaryWaveLenInUm);
%                     % Jones matrix becomes 3D for multiple rays
%                     jonesMatrix(1,1,:) = ampRs; jonesMatrix(1,2,:) = 0;
%                     jonesMatrix(2,1,:) = 0; jonesMatrix(2,2,:) = ampRp;
                end
            elseif  strcmp(optSystem.SurfaceArray(surfaceIndex).DeviationMode,...
                    '+1 Refractive')% refraction
                [localTransmittedRayDirection,TIR] = computeRefractedRayDirection ...
                    (localIncidentRayDirection,localSurfaceNormal,indexBefore,indexAfter); % 7th function
                nTotIR = sum(TIR);
                if nTotIR > 0
                    disp([num2str(nTotIR) , ' rays encountered Total Internal Reflections at ' ,...
                        'surface ', num2str(surfaceIndex),'.']);
                else
                    disp(['All of ',num2str(nRay),' rays refracted through surface ',...
                        num2str(surfaceIndex),' with out Total Internal Reflections.']);
                end
                localTransmittedRayAngle = computeAngleBetweenVectors(localTransmittedRayDirection,...
                    localSurfaceNormal);
                currentRayDirection = localTransmittedRayDirection;
                localExitRayDirection = localTransmittedRayDirection;
                localExitAngle = localTransmittedRayAngle;
                Kq = currentRayDirection;
                if polarized
                    % new code
                    % Wavelength shall be converted to um
                    primaryWaveLenInUm = optSystem.getPrimaryWavelength*10^6;
                    wavLenInUm = wavlen*10^6;
                    [ampTs,ampTp,powTs,powTp,jonesMatrix] = ...
                        optSystem.SurfaceArray(surfaceIndex).Coating. ...
                        getTransmissionCoefficients(wavLenInUm,localIncidenceAngle,...
                         indexBefore,indexAfter,primaryWaveLenInUm);
%                     % Jones matrix becomes 3D for multiple rays
%                     jonesMatrix(1,1,:) = ampTs; jonesMatrix(1,2,:) = 0;
%                     jonesMatrix(2,1,:) = 0; jonesMatrix(2,2,:) = ampTp;
                end
            else
                disp('Surface must be either reflective or refractive');
            end
            % compute the new P matrix
            if polarized
%                 if strcmpi(optSystem.SurfaceArray(surfaceIndex).Coating.Type,'None')
%                     P = [1,0,0;0,1,0;0,0,1];
%                     Q = [1,0,0;0,1,0;0,0,1];
%                 else
                    P = convertJonesMatrixToPolarizationMatrix(jonesMatrix,Kqm1,Kq);
                    coatingJonesMatrix = jonesMatrix;
                    coatingPMatrix = P;
                    % compute the total P matrix
                    totalPMatrix = multiplySliced3DMatrices(P,totalPMatrix);
                    % compute new Polarization vector
                    % Convert to 3D vector to use the slice based 3D multiplier
                    % function
                    polVector3D = permute(currentRayPolarizationVector,[1,3,2]);
                    newPolVector3D = multiplySliced3DMatrices...
                        (P,polVector3D);
                    % change back to 2D matrix
                    newLocalPolarizationVector = permute(newPolVector3D,[1,3,2]);
                    currentRayPolarizationVector = newLocalPolarizationVector;
                    % compute the parallel ray transport matrix Q
                    qJonesMatrix = repmat([1,0;0,1],[1,1,nRay]);   % unity jones matrix for non polarizing element
                    Q = convertJonesMatrixToPolarizationMatrix(qJonesMatrix,Kqm1,Kq);
                    coatingQMatrix = Q;
                    % compute the total Q matrix
                    totalQMatrix = multiplySliced3DMatrices(Q,totalQMatrix);
%                 end
            end
        elseif surfaceIndex==nSurface
            % for image surface no refraction
            localExitRayDirection  = repmat([NaN;NaN;NaN],[1,nRay]);
            localExitAngle = NaN([1,nRay]);
            if polarized
                jonesMatrix = repmat(NaN*eye(2),[1,1,nRay]);
                P = repmat(NaN*eye(3),[1,1,nRay]);
                Q = repmat(NaN*eye(3),[1,1,nRay]);
                coatingJonesMatrix = jonesMatrix;
                coatingPMatrix = P;
                coatingQMatrix = Q;
            end
        end
        % Finally Transfer back to Global coordinate system
       localRayPosition = currentRayPosition;
       localRayDirection = currentRayDirection;
       if polarized
           localRayPolarizationVector = currentRayPolarizationVector;
           localRayPolarizationVectorBefore = currentRayPolarizationVectorBefore;
           localRayData = cat(3,localRayPosition,localRayDirection,...
               localRayPolarizationVectorBefore,localRayPolarizationVector);
       else
           localRayData = cat(3,localRayPosition,localRayDirection);
       end
       %% New Code for Global to Local Coordinate transformation
       [globalRayData,globalSurfaceNormal,globalIncidentRayDirection,...
           globalExitRayDirection] = localToGlobalCoordinate(localRayData,...
           polarized,localSurfaceNormal,localIncidentRayDirection,...
           localExitRayDirection,surfaceCoordinateTM,referenceCoordinateTM);
       %% End of New code
       % now the currentnt ray becomes global ray agin
       currentRayPosition = globalRayData(:,:,1);
       currentRayDirection = globalRayData(:,:,2);
       if polarized
            globalRayPolarizationVectorBefore = globalRayData(:,:,3);
            globalRayPolarizationVector = globalRayData(:,:,4);
       end
       globalIncidenceAngle = localIncidenceAngle;
       globalExitAngle = localExitAngle;
        % Record all neccessary outputs to trace the ray
        if polarized
            multipleRayTracerResult(surfaceIndex,:) = RayTraceResult...
               (currentRayPosition,globalSurfaceNormal,globalIncidentRayDirection,...
               globalIncidenceAngle,globalExitRayDirection,globalExitAngle,...
               NoIntersectionPoint,outOfAperture,TIR,geometricalPathLength,opticalPathLength,...
               globalRayPolarizationVectorBefore,globalRayPolarizationVector,...
               coatingJonesMatrix,coatingPMatrix,coatingQMatrix,totalPMatrix,totalQMatrix);
        else
            multipleRayTracerResult(surfaceIndex,:) =...
               RayTraceResult(currentRayPosition,globalSurfaceNormal,...
               globalIncidentRayDirection,globalIncidenceAngle,...
               globalExitRayDirection,globalExitAngle,NoIntersectionPoint,...
               outOfAperture,TIR,geometricalPathLength,opticalPathLength);
        end
    end
polarizedRayTracerResult = multipleRayTracerResult;