Description of Coating
Coating
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Coating
This function is called by:
getCurrentOpticalSystem getCurrentOpticalSystem: Constructs an optical system object from the AOD
Coating
Surface
coatingDataInputDialog COATINGDATAINPUTDIALOG Defines a dilog box which is used to input coating
SUBFUNCTIONS
function NEWCOATING = Coating(coatType,coatName,coatingParameters)
SOURCE CODE
classdef Coating < handle
    % Coating Class:
    %   Defines multilayer coating attached to the optical surfaces
    % Properties: 3
    %     Name % String. Name of the coating for the user defined coatings
    %     Type % String. 'None','BareGlass','JonesMatrix','Multilayer'
    %     CoatingParameters % Struct containg all the parameters used for
    %     % different types of coating. Parameters which are not defined
    %     % for a certain coating type have NaN values.
    %     %     % Parameters Defines for "JonesMatrix"  type coating
    %     %     TransmissionMatrix
    %     %     ReflectionMatrix
    %     %
    %     %     % Parameters Defines for "Multilayer"  type coating
    %     %     RefractiveIndexProfile % Matrix of thickness x refractive index.
    %     %     RepetetionNumber % Number of time the  index profile is repeated.
    %     %     UseInReverse % Use the coating in reverse order to the defined order.
    % Methods: 12
    %   Functions to analyse coating objects are
    % <<<<<<<<<<<<<<<<<<<<<<< Algorithm Section>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %
    % <<<<<<<<<<<<<<<<<<<<<<<<< Example Usage>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %
    % <<<<<<<<<<<<<<<<<<<<<<<<< Author Section >>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %   Written By: Worku, Norman Girma
    %   Advisor: Prof. Herbert Gross
    %   Part of the RAYTRACE_TOOLBOX V3.0 (OOP Version)
    %    Optical System Design and Simulation Research Group
    %   Institute of Applied Physics
    %   Friedrich-Schiller-University of Jena
    % <<<<<<<<<<<<<<<<<<< Change History Section >>>>>>>>>>>>>>>>>>>>>>>>>>
    % Date----------Modified By ---------Modification Detail--------Remark
    % Oct 14,2013   Worku, Norman G.     Original Version       Version 3.0
    % <<<<<<<<<<<<<<<<<<<<< Main Code Section >>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    properties
        Name % String. Name of the coating for the user defined coatings
        Type % String. 'None','BareGlass','JonesMatrix','Multilayer'
        CoatingParameters % Struct containg all the parameters used for
        % different types of coating. Parameters which are not defined
        % for a certain coating type have NaN values.
        %     % Parameters Defines for "JonesMatrix"  type coating
        %     TransmissionMatrix
        %     ReflectionMatrix
        %
        %     % Parameters Defines for "Multilayer"  type coating
        %     RefractiveIndexProfile % Matrix of thickness x refractive index.
        %     RepetetionNumber % Number of time the  index profile is repeated.
        %     UseInReverse % Use the coating in reverse order to the defined order.
    end
    methods
        % Constructors
        function NEWCOATING = Coating(coatType,coatName,coatingParameters)
            % A method used to construct a new coating object from its parameters.
                if nargin == 0 % Enable construction  with no inputs
                    coatType = 'None';
                    coatName = 'None';
                    coatingParameters.TransmissionMatrix = NaN*[1,0;0,1];
                    coatingParameters.ReflectionMatrix = NaN*[1,0;0,1];
                    coatingParameters.RefractiveIndexProfile = [NaN NaN (0)];
                    coatingParameters.RepetetionNumber = NaN*0;
                    coatingParameters.UseInReverse = NaN*0;
                elseif nargin <= 2 % if nargin == 1 or nargin == 2
                    if nargin == 1
                        coatName = 'None';
                    end
                    switch lower(coatType)
                        case lower('None')
                            coatingParameters.TransmissionMatrix = NaN*[1,0;0,1];
                            coatingParameters.ReflectionMatrix = NaN*[1,0;0,1];
                            coatingParameters.RefractiveIndexProfile = [NaN NaN (0)];
                            coatingParameters.RepetetionNumber = NaN*0;
                            coatingParameters.UseInReverse = NaN*0;
                        case lower({'BareGlass'})
                            coatingParameters.TransmissionMatrix = NaN*[1,0;0,1];
                            coatingParameters.ReflectionMatrix = NaN*[1,0;0,1];
                            coatingParameters.RefractiveIndexProfile = [NaN NaN (0)];
                            coatingParameters.RepetetionNumber = NaN*1;
                            coatingParameters.UseInReverse = NaN*0;
                        case lower({'Multilayer'})
                            coatingParameters.TransmissionMatrix = NaN*[1,0;0,1];
                            coatingParameters.ReflectionMatrix = NaN*[1,0;0,1];
                            coatingParameters.RefractiveIndexProfile = [1 0 (0)];
                            coatingParameters.RepetetionNumber = 1;
                            coatingParameters.UseInReverse = 0;
                        case lower('JonesMatrix')
                            coatingParameters.TransmissionMatrix = [1,0;0,1];
                            coatingParameters.ReflectionMatrix = [1,0;0,1];
                            coatingParameters.RefractiveIndexProfile = [NaN NaN (0)];
                            coatingParameters.RepetetionNumber = NaN*0;
                            coatingParameters.UseInReverse = NaN*0;
                        otherwise
                            disp('Error: Invalid coating type.');
                            return;
                    end
                elseif nargin == 3
                    switch lower(coatType)
                        case lower({'None','BareGlass'})
                            coatingParameters.TransmissionMatrix = NaN*[1,0;0,1];
                            coatingParameters.ReflectionMatrix = NaN*[1,0;0,1];
                            coatingParameters.RefractiveIndexProfile = [NaN NaN (0)];
                            coatingParameters.RepetetionNumber = NaN*0;
                            coatingParameters.UseInReverse = NaN*0;
                       case lower({'Multilayer'})
                            coatingParameters.TransmissionMatrix = NaN*[1,0;0,1];
                            coatingParameters.ReflectionMatrix = NaN*[1,0;0,1];
                            if ~isfield(coatingParameters, 'RefractiveIndexProfile')
                                coatingParameters.RefractiveIndexProfile = [0 0 0];
                            end
                            if ~isfield(coatingParameters, 'RepetetionNumber')
                                coatingParameters.RepetetionNumber = 1;
                            end
                            if ~isfield(coatingParameters, 'UseInReverse')
                                coatingParameters.UseInReverse = 0;
                            end
                        case lower('JonesMatrix')
                            if ~isfield(coatingParameters, 'TransmissionMatrix')
                                coatingParameters.TransmissionMatrix = [1,0;0,1];
                            end
                            if ~isfield(coatingParameters, 'ReflectionMatrix')
                                coatingParameters.ReflectionMatrix = [1,0;0,1];
                            end
                            coatingParameters.RefractiveIndexProfile = [NaN NaN (0)];
                            coatingParameters.RepetetionNumber = NaN*0;
                            coatingParameters.UseInReverse = NaN*0;
                        otherwise
                            disp('Error: Invalid coating type.');
                            return;
                    end
                end
                NEWCOATING.Type = coatType;
                NEWCOATING.Name = coatName;
                NEWCOATING.CoatingParameters.TransmissionMatrix = ...
                    coatingParameters.TransmissionMatrix;
                NEWCOATING.CoatingParameters.ReflectionMatrix = ...
                    coatingParameters.ReflectionMatrix;
                NEWCOATING.CoatingParameters.RefractiveIndexProfile = ...
                    coatingParameters.RefractiveIndexProfile;
                NEWCOATING.CoatingParameters.RepetetionNumber = ...
                    coatingParameters.RepetetionNumber;
                NEWCOATING.CoatingParameters.UseInReverse = ...
                    coatingParameters.UseInReverse;
        end
    end
end