function emptyCoating = createEmptyCoating()
    % returns an empty struct or object of class
    if isstruct(Coating())
        emptyCoating = struct(...
            'Type',{},...
            'Name',{},...
            'Parameters',{},...
            'ClassName',{});
    else
        emptyCoating = Coating.empty;
    end
end